with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\" coordsize=\"950,1071\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1071px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7EDAJ54200000000DEAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:595px;top:43px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FAN CONTROL RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A/C COMPRESSOR CLUTCH RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:791px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>VSA MODULATOR-<br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:623px;top:437px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:829px;top:954px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1px;top:1026px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>LHD type is shown, RHD type is similar.<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:934px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TRANSMISSION CONTROL MODULE (TCM)*<br>(Built into the clutch actuator)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1px;top:1042px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>*: i-SHIFT System<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}