with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E00F00000057145KDAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746px;top:305px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 x 1.25 mm<br>20 N·m<br>(2.0 kgf·m, 14 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:18px;top:202px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNECTOR BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:83px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m<br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:12px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TORQUE SENSOR 3P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296px;top:70px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:209px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MOTOR<br></b>If the motor is faulty,<br>replace it.<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298px;top:26px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GROUND TERMINAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769px;top:757px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>LOCKNUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:768px;top:823px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DISC WASHER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769px;top:942px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RACK GUIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:768px;top:894px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:768px;top:857px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:768px;top:790px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RACK GUIDE SCREW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:404px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TORQUE SENSOR ASSEMBLY<br></b>If the torque sensor<br>is damaged or faulty,<br>replace the gearbox as <br>an assembly.<br></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:633px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GEARBOX MOUNT CUSHION<br></b>Inspect for damage and<br>deterioration.<br></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:6px;top:478px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GEARBOX HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:5px;top:605px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MOUNT CUSHION<br></b>Inspect for damage and<br>deterioration.<br></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:855px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>LOCK WASHER<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:149px;top:918px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RACK END<br>93 N·m<br>(9.5 kgf·m, 69 lbf·ft)<br></b>Inspect for faulty<br>movement and damage.<br></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:978px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BOOT<br></b>Inspect for damage <br>and deterioration.<br></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:1035px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TIE-ROD CLIP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1px;top:1059px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>The illustration shows LHD type. RHD type is similar.<br></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:941px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BOOT BAND<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1px;top:808px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RUBBER STOP<br></b>Replace.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}