with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:975px;\" coordsize=\"950,975\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:975px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SMR7E55G24100000000DAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:975px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:565px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HVAC SUBDISPLAY UNIT<br>(Without audio system)<br><a href=\"javascript:CtsProc('0','000000000000113','i000')\"></b>Replacement,</a><br> in the Shop Manual,<br> P/N 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:15px;top:368px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SUNLIGHT SENSOR<br><a href=\"javascript:CtsProc('0','000000000000063','i000')\"></b>Test,</a><br> in the Shop Manual,<br> P/N 62SMR00B<br><a href=\"javascript:CtsProc('0','000000000000064','i000')\">Replacement,<br></a><br> in the Shop Manual,<br> P/N 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594px;top:143px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MODE CONTROL MOTOR<br><a href=\"javascript:CtsProc('0','000000000000059','i000')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:79px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>POWER TRANSISTOR<br><a href=\"javascript:CtsProc('0','000000000000066','i000')\"></b>Test,</a><br> in the Shop Manual, P/N 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:532px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BLOWER MOTOR<br><a href=\"javascript:CtsProc('0','000000000000065','i000')\"></b>Replacement,<br></a><br> in the Shop Manual,<br> P/N 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:64px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HEATER UNIT/CORE<br><a href=\"javascript:CtsProc('0','000000000001554','i000')\"></b>Replacement,<br></a><br> in the Shop Manual,<br> P/N 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:951px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>LHD type is shown, RHD type is symmetrical.<br></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:533px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>AUDIO HVAC SUBDISPLAY UNIT<br>(With audio system)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PTC HEATER CORE<br>(Located-in the heater unit)<br><a href=\"javascript:CtsProc('0','000000000001277','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:206px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RECIRCULATION CONTROL MOTOR<br><a href=\"javascript:CtsProc('0','000000000000062','i000')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:678px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>AIR MIX CONTROL <br>MOTOR<br><a href=\"javascript:CtsProc('0','000000000001551','i000')\"></b>Replacement,<br></a><br> in the Shop Manual,<br> P/N 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539px;top:844px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HEATER CONTROL UNIT<br><a href=\"javascript:CtsProc('0','000000000001553','i000')\"></b>Removal/Installation,<br></a><br> in the Shop Manual,<br> P/N 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:844px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>IN-CAR TEMPERATURE SENSOR<br><a href=\"javascript:CtsProc('0','000000000000057','i000')\"></b>Test,</a><br> in the Shop Manual, P/N 62SMR00B<br><a href=\"javascript:CtsProc('0','000000000000058','i000')\">Replacement,</a><br> in the Shop Manual, P/N 62SMR00B<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}