with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:735px;\" coordsize=\"950,735\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:735px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E40E34151100000CAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:735px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:163px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Return spring pulls back the<br>select lock pin<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:696px;top:357px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Interlock<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597px;top:479px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Locked position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:670px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Select lever<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275px;top:473px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>With reverse<br>selected<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:310px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Return spring<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:198px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Select lock pin<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:137px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Select lock cam<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:422px;top:702px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Direction of reverse selection<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:113px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Inhibitor OFF<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}