with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SMR7ET2A20300000000DBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:834px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ECT SENSOR<br>2 (19)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:834px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ECT SENSOR<br>1 (20)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:821px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SECONDARY<br>HO2S (SENSOR 2)<br>(21)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:833px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CKP SENSOR<br>(22)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:664px;top:821px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>A/F SENSOR<br>(SENSOR 1)<br>(23)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799px;top:835px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>OIL PRESSURE<br>SWITCH (24)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:684px;top:364px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ECM A (□) (14)*<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:35px;top:42px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>EGR VALVE<br>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:42px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>24P JUNCTION CONNECTOR<br>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:414px;top:42px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CMP SENSOR<br>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:30px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>EVAP CANISTER<br>PURGE VALVE<br>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:42px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>THROTTLE BODY<br>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:806px;top:17px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>OUTPUT SHAFT<br>(COUNTERSHAFT)<br>SPEED SENSOR<br>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:191px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>MAF SENSOR/<br>IAT SENSOR<br>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224px;top:206px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>23P CONNECTOR (8)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:364px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY<br>BOX D (12)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:440px;top:364px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX F (13)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:206px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ELD (10)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702px;top:194px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY<br>BOX E (11)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:420px;top:194px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>TEST<br>TACHOMETER<br>CONNECTOR (9)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:563px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ECM C (○) (16)*<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:563px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ECM B (△) (15)*<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653px;top:551px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CLUTCH<br>ACTUATOR<br>(TCM) (17)<br>(with i-SHIFT)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:803px;top:551px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>REVERSE<br>LOCK<br>SOLENOID <br>(18) (M/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3px;top:999px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br>*: Connector with female terminals (single outline): view from terminal side<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}