with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:1900px; height:1110px;\" coordsize=\"1900,1110\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:1900px;height:1110px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7EDAJ20100000000LEAD90.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:1900px;height:1110px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:629px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Front side frame locating hole φ16 (0.63)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:629px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>a<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:646px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>b1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:663px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>b2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:680px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>b3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:698px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>c1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:715px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>c2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:732px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>c3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:749px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>d1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:777px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>d2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:805px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>e1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:822px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>e2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:839px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>e3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:856px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>e4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:873px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>f1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:890px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>f2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:907px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>f3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:924px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>g1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:941px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>g2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:958px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>h<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:976px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>i1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:993px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>i2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:1010px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>j<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:1027px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>k1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:1044px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>k2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:1061px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>l1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:1078px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>l2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:646px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>For engine side mount φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:663px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>For engine side mount φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:680px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>For engine side mount φ12 (0.47)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:698px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>For transmission mount φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:715px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>For transmission mount φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:732px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>For transmission mount point<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:749px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>For torque rod mount upper<br>φ14.5 (0.57) x 19.5 (0.77) slot <br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:777px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>For torque rod mount lower<br>φ21 (0.83) x 29 (1.14) slot <br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:805px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>For front damper mount φ11.5 (0.45)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:822px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Front damper center point φ69.5 (2.74)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:839px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>For front damper mount φ11.5 (0.45)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:856px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>For front damper mount φ11.5 (0.45)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:873px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>For front subframe mount φ16 (0.63)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:890px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>For front subframe mount φ16 (0.63)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:907px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>For front subframe mount φ16 (0.63)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:924px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Right, outrigger locating hole φ16 (0.63)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:941px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Left, for front subframe mount φ16 (0.63) x 20 (0.8) slot<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:959px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Outrigger locating hole φ27.4 (1.08)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:976px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Right, front floor front cross-member locating hole φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:993px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Left, front floor front cross-member locating hole φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:1010px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Front floor locating hole φ50 (2.0) forward<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:1027px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Right, front floor frame locating hole φ20 (0.8) forward<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:1044px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Left, front floor frame locating hole φ20 (0.8) forward<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:1061px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Right, front floor frame locating hole φ15 (0.59) rearward<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:1078px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Left, front floor frame locating hole φ15 (0.59) rearward<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1439px;top:804px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>m1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1439px;top:821px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>m2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1439px;top:838px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>n<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1439px;top:856px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1439px;top:873px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>p<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1439px;top:890px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>q1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1439px;top:907px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>q2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1439px;top:924px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>r1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1439px;top:941px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>r2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1439px;top:958px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>s1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1439px;top:975px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>s2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1439px;top:992px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>t<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1439px;top:1010px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>u<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1439px;top:1027px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>v<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1439px;top:1044px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>w1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1439px;top:1061px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>w2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1439px;top:1078px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>x<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:804px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Right, front floor center cross-member locating hole φ20 (0.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:821px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Left, front floor center cross-member locating hole φ20 (0.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:838px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Front floor locating hole φ25 (1.0) rearward<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:856px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Front floor frame B locating hole φ11 (0.43) forward<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:890px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Right, trailing arm bracket locating hole φ20 (0.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:924px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Right, middle floor cross-member locating hole φ15 (0.59) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:958px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>For trailing arm mount φ15 (0.59) inside<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:992px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Spring base center point φ17 (0.67)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:1009px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Rear floor center cross-member locating hole φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:1027px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Rear damper center point φ24 (0.94)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:1044px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Right, rear floor cross-member locating hole φ11 (0.43)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:1078px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Rear frame B locating hole φ25 (0.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:873px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Front floor frame B locating hole φ11 (0.43) rearward<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:907px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Left, trailing arm bracket locating hole φ20 (0.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:941px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Left, middle floor cross-member locating hole φ15 (0.59) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:975px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>For trailing arm mount φ17 (0.67) outside<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1473px;top:1061px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>Left, rear floor cross-member locating hole φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562px;top:742px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>337 (13.3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:759px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>383 (15.1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:721px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>460 (18.1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405px;top:704px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>229 (9.02)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405px;top:686px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>181 (7.13)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405px;top:669px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>105 (4.13)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:426px;top:653px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>5 (0.2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:669px;font-weight:normal;font-size:6.31pt;\">");
write("<nobr><b>42 (1.65) e3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:687px;font-weight:normal;font-size:6.31pt;\">");
write("<nobr><b>43 (1.69) e2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:703px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>87 (3.4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:721px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>90 (3.5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:572px;top:777px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>403 (15.9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:794px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>450 (17.7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:812px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>640 (25.2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615px;top:829px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>765 (30.1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:846px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>970 (38.2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:864px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>1262 (49.69)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:882px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>1491 (58.70)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644px;top:900px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>1635 (64.37)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:651px;top:917px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>1724 (67.87)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659px;top:934px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>2002 (78.82)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:952px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>2065 (81.30)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:970px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>2165 (85.24)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:681px;top:988px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>2199 (86.57)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688px;top:1006px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>2245 (88.39)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:696px;top:1022px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>2597 (102.2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:703px;top:1041px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>2790 (109.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:1059px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>2859 (112.6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718px;top:1077px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>2945 (115.9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1330px;top:1021px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>7 (0.28)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:78px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>367 (14.4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:473px;top:96px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>215 (8.46)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:474px;top:115px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>166 (6.54)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428px;top:167px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>5 (0.2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:149px;font-weight:normal;font-size:6.31pt;\">");
write("<nobr><b>99 (3.9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:432px;top:117px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>112<br>(4.41)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:565px;top:79px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>90 (3.5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:565px;top:97px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>43 (1.69) e2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:565px;top:116px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>42 (1.65) e3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:189px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT a<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296px;top:148px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT b1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:301px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT b2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:172px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT b3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:531px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT c1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:420px;top:483px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT c2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:506px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT c3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367px;top:325px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT d1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:359px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT d2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:390px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT e2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:135px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT e1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:153px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT e4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:591px;top:170px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT e3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:606px;top:188px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT f1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:691px;top:118px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT f2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:143px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT g1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715px;top:166px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT f3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730px;top:187px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT h<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:811px;top:81px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT i1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833px;top:104px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT j<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:856px;top:125px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT k1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:879px;top:148px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT l1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:697px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT g2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:770px;top:680px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT i2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833px;top:660px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT k2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:855px;top:715px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT l2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:993px;top:75px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT m1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1029px;top:101px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT n<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1064px;top:130px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1094px;top:152px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT p<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1149px;top:90px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT q1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1178px;top:121px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT r1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1227px;top:151px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT s1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1245px;top:175px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT s2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1317px;top:81px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT t<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1359px;top:105px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT u<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1385px;top:134px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT v<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1434px;top:157px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT w1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1509px;top:175px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT x<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1067px;top:756px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT m2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1075px;top:692px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT q2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1230px;top:684px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT r2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1489px;top:669px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>POINT w2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:417px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>CENTER LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507px;top:52px;font-weight:normal;font-size:7.21pt;\">");
write("<nobr><b>VERTICAL LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:27px;top:30px;font-weight:normal;font-size:8.18pt;\">");
write("<nobr><b>Unit: mm (in.)<br>φ: Inner diameter<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("<v:line id=\"bl1_1\" name=\"prt_bl\" class=\"drag\" from=\"235,542\" to=\"234,437\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_1\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"548 (21.6)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_2\" name=\"prt_bl\" class=\"drag\" from=\"235,358\" to=\"234,259\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_2\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"667 (26.3)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_3\" name=\"prt_bl\" class=\"drag\" from=\"277,542\" to=\"276,444\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_3\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"477 (18.8)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_4\" name=\"prt_bl\" class=\"drag\" from=\"255,384\" to=\"254,284\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_4\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"484 (19.06)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_5\" name=\"prt_bl\" class=\"drag\" from=\"276,384\" to=\"275,290\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_5\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"481 (18.9)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_6\" name=\"prt_bl\" class=\"drag\" from=\"299,542\" to=\"298,444\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_6\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"475 (18.7)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_7\" name=\"prt_bl\" class=\"drag\" from=\"299,384\" to=\"298,288\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_7\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"478 (18.82)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_8\" name=\"prt_bl\" class=\"drag\" from=\"320,385\" to=\"319,291\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_8\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"454 (17.9)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_9\" name=\"prt_bl\" class=\"drag\" from=\"488,452\" to=\"487,359\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_9\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"1201 (47.28)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_10\" name=\"prt_bl\" class=\"drag\" from=\"553,452\" to=\"552,360\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_10\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"1036 (40.79)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_11\" name=\"prt_bl\" class=\"drag\" from=\"515,452\" to=\"514,356\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_11\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"1146 (45.12)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_12\" name=\"prt_bl\" class=\"drag\" from=\"573,446\" to=\"572,353\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_12\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"898 (35.4)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_13\" name=\"prt_bl\" class=\"drag\" from=\"594,452\" to=\"593,352\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_13\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"1036 (40.79)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_14\" name=\"prt_bl\" class=\"drag\" from=\"616,446\" to=\"615,335\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_14\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"963 (37.9)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_15\" name=\"prt_bl\" class=\"drag\" from=\"636,446\" to=\"635,338\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_15\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"751 (29.6)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_16\" name=\"prt_bl\" class=\"drag\" from=\"660,446\" to=\"659,341\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_16\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"940 (37.0)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_17\" name=\"prt_bl\" class=\"drag\" from=\"683,446\" to=\"682,339\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_17\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"530 (20.9)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_18\" name=\"prt_bl\" class=\"drag\" from=\"781,446\" to=\"780,342\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_18\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"680 (26.8)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_19\" name=\"prt_bl\" class=\"drag\" from=\"838,537\" to=\"837,461\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_19\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"522 (20.6)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_20\" name=\"prt_bl\" class=\"drag\" from=\"838,388\" to=\"837,291\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_20\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"487 (19.2)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_21\" name=\"prt_bl\" class=\"drag\" from=\"869,537\" to=\"868,458\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_21\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"537 (21.1)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_22\" name=\"prt_bl\" class=\"drag\" from=\"869,388\" to=\"868,289\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_22\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"496 (19.5)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_23\" name=\"prt_bl\" class=\"drag\" from=\"1015,491\" to=\"1014,394\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_23\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"280 (11.0)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_24\" name=\"prt_bl\" class=\"drag\" from=\"1016,396\" to=\"1015,293\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_24\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"400 (15.7)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_25\" name=\"prt_bl\" class=\"drag\" from=\"1036,446\" to=\"1035,344\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_25\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"900 (35.4)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_26\" name=\"prt_bl\" class=\"drag\" from=\"1080,446\" to=\"1079,345\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_26\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"683 (26.9)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_27\" name=\"prt_bl\" class=\"drag\" from=\"1154,492\" to=\"1153,404\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_27\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"270 (10.6)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_28\" name=\"prt_bl\" class=\"drag\" from=\"1155,414\" to=\"1154,332\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_28\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"255 (10.0)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_29\" name=\"prt_bl\" class=\"drag\" from=\"1546,446\" to=\"1545,339\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_29\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"450 (17.7)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_30\" name=\"prt_bl\" class=\"drag\" from=\"1566,446\" to=\"1565,341\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_30\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"600 (23.6)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_31\" name=\"prt_bl\" class=\"drag\" from=\"1585,452\" to=\"1584,348\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_31\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"1014 (39.92)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_32\" name=\"prt_bl\" class=\"drag\" from=\"1604,452\" to=\"1603,350\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_32\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"1089 (42.87)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_33\" name=\"prt_bl\" class=\"drag\" from=\"1624,452\" to=\"1623,347\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_33\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"1158 (45.59)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_34\" name=\"prt_bl\" class=\"drag\" from=\"1644,452\" to=\"1643,347\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_34\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"1197 (47.13)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_35\" name=\"prt_bl\" class=\"drag\" from=\"1663,452\" to=\"1662,349\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_35\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"1240 (48.82)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_36\" name=\"prt_bl\" class=\"drag\" from=\"1684,452\" to=\"1683,351\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_36\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"1357 (53.43)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_37\" name=\"prt_bl\" class=\"drag\" from=\"1127,446\" to=\"1126,354\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_37\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"683 (26.9)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.21pt;\"/>");
write("</v:line>");
write("</v:group>");
}