with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:1900px; height:950px;\" coordsize=\"1900,950\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:1900px;height:950px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7ET0000000000000EBAD13.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:1900px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1166px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1609px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1839px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:24px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:23px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>Audio System<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:728px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1585px;top:312px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1566px;top:339px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>79<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1566px;top:631px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>98<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1321px;top:738px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>155<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1455px;top:786px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1477px;top:418px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1135px;top:631px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>154<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1108px;top:631px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>153<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1055px;top:631px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>152<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1028px;top:631px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>151<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:953px;top:631px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>150<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:926px;top:631px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>149<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:855px;top:631px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>148<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:829px;top:631px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>147<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:802px;top:631px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>146<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731px;top:636px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>145<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:339px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>143<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:351px;top:339px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:179px;top:312px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:339px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>144<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:339px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>88<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:339px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>79<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:543px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>99<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:521px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:547px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>79<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:747px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>97<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562px;top:220px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WINDOW ANTENNA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276px;top:786px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G504<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277px;top:724px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:600px;top:588px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RADIO REMOTE SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:468px;top:516px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:582px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:659px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:669px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:669px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:630px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3.9 kΩ<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:582px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:516px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:662px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MODE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:669px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:662px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:655px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VOL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:655px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VOL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:662px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DOWN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:669px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:554px;top:659px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:619px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>100 Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:630px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>270 Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:630px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>470 Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:553px;top:630px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1.2 kΩ<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:631px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>10 kΩ<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:666px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(+)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:554px;top:666px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(−)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729px;top:666px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:360px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1660px;top:122px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*2 : UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1660px;top:115px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*1 : UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1707px;top:130px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>: Shielding<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:436px;top:339px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:312px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:502px;top:312px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484px;top:339px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>52<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1185px;top:339px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>52<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1202px;top:312px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ILL+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VSP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>NAVISCTY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>K−LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:390px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SCTY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>F3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>F2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:543px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>F1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:700px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR L+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR L−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:864px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:851px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR R+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:895px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:882px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR R−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1010px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:997px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR L+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1041px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1029px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR L−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1086px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1072px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR R+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1117px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1104px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR R−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ILL−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REMOTE SW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:478px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REMOTE GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:696px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:797px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RG R+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:811px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RG L+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:847px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RG GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:864px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:879px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:891px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:923px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BUS+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:935px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:950px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BUS−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:962px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:977px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:988px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1026px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1037px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1053px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1064px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1075px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1090px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1104px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MUTE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1117px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1131px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ICON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1143px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1574px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1564px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ILL−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1226px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1237px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1263px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1290px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1316px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1343px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1370px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1409px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1436px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1463px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1563px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ILL+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1574px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1645px;top:640px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>136<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1671px;top:640px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>135<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1680px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1669px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1653px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1639px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AC SO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(AM/FM)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:477px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RADIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:430px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BACK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RADIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:448px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:273px;top:475px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RADIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:475px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUDIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:681px;top:475px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUDIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:875px;top:475px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:882px;top:468px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:926px;top:475px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:953px;top:475px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:973px;top:475px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:977px;top:468px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BUS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1133px;top:475px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1106px;top:475px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1080px;top:475px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1049px;top:475px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TELEM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1022px;top:475px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TELEM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1076px;top:468px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TELEM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1225px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1227px;top:455px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BL+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1226px;top:448px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LCD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1253px;top:448px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LCD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1254px;top:455px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BL−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1251px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1252px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1281px;top:448px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1278px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1279px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1304px;top:448px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DATA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1305px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1306px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1328px;top:448px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1331px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1332px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1359px;top:448px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1358px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1359px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1394px;top:448px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1398px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1399px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1427px;top:448px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5 V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1425px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1425px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1451px;top:448px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1451px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1452px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1463px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1436px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1409px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1370px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1343px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1316px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1290px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1263px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1237px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1489px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1668px;top:475px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1330px;top:593px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1330px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1370px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1467px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206px;top:291px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206px;top:284px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:284px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM (3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206px;top:305px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1046px;top:656px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HANDS−FREE TELEPHONE <br>CONTROL UNIT <br>(14−C, D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:735px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CABLE <br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:611px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CABLE <br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:926px;top:656px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>NAVIGATION <br>DISPLAY <br>(14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1549px;top:312px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No.14 (7.5 A) <br>FUSE <br>(2−D) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1551px;top:651px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>(5−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1308px;top:758px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>NAVIGATION <br>UNIT (14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:704px;top:249px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT FRONT <br>DOOR SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:788px;top:249px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT <br>TWEETER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:855px;top:249px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT FRONT <br>DOOR SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1001px;top:249px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT <br>REAR SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:934px;top:249px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT <br>TWEETER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1076px;top:249px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT <br>REAR SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:291px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>NAVIGATION <br>UNIT (14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:144px;top:312px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No.14 (7.5 A) <br>FUSE <br>(2−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:563px;top:286px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANTENNA MODULE <br>(AMPLIFIER)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:562px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>(5−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:521px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No.14 (7.5 A) <br>FUSE <br>(2−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:496px;top:548px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CABLE <br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:548px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CABLE <br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_250\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:766px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>(5−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_251\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:312px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>NAVIGATION <br>DISPLAY <br>(14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_252\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:595px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VOICE <br>CONTROL SWITCH/ <br>HFL−VOICE <br>CONTROL SWITCH <br>(14−A, C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_253\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:416px;top:312px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No.16 (15 A) <br>FUSE <br>(1−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_254\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:312px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No.35 (7.5 A) <br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_255\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1166px;top:312px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No.35 (7.5 A) <br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_256\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1636px;top:656px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CIMATE CONTROL <br>UNIT (9−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_257\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:319px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MICU <br>(10−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_258\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:312px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DATA LINK <br>CONNECTOR <br>(3−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_259\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:305px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEADLIGHT <br>ADJUSTER <br>CONTROL <br>UNIT (6−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_260\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1443px;top:459px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUDIO UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_261\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1537px;top:686px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(With navigation system)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_262\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1563px;top:369px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_263\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1563px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_264\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1319px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_265\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1371px;top:635px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INTERFACE DIAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_266\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1457px;top:719px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_267\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1318px;top:706px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_268\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1359px;top:689px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_269\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1452px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_270\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1425px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_271\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1305px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_272\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1359px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_273\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1332px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_274\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1398px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_275\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1398px;top:347px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_276\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1221px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_277\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1252px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_278\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1279px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_279\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1479px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_280\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1309px;top:307px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUDIO−HVAC SUBDISPLAY−CLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_281\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:951px;top:225px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(With tweeter)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_282\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1093px;top:695px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(With navigation system)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_283\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:854px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_284\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:826px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_285\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_286\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:879px;top:547px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_287\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:792px;top:655px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>NAVIGATION UNIT (14−B, C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_288\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:977px;top:547px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_289\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:925px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_290\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:951px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_291\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1053px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_292\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1026px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_293\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1075px;top:547px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_294\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1129px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_295\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1106px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_296\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1106px;top:320px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_297\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1075px;top:320px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_298\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1031px;top:320px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_299\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:884px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_300\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:884px;top:320px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_301\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:955px;top:320px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_302\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:853px;top:320px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_303\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:853px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_304\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:924px;top:320px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_305\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_306\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_307\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773px;top:320px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_308\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698px;top:320px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_309\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:320px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_310\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1000px;top:320px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_311\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729px;top:320px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_312\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800px;top:225px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(With tweeter)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_313\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157px;top:382px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_314\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638px;top:458px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUDIO UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_315\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:382px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_316\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:382px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_317\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:383px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_318\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392px;top:382px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_319\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:382px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_320\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237px;top:515px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_321\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:559px;top:387px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANTENNA SUBLEAD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_322\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:565px;top:360px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANTENNA LEAD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_323\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:290px;top:383px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_324\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(With navigation system)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_325\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:703px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(With navigation system)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_326\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550px;top:334px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TAILGATE ANTENNA LEAD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_327\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1181px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_328\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1669px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_329\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1643px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_330\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1443px;top:808px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(With navigation system)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}