with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:831px;\" coordsize=\"950,831\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:831px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E00R11100000000YCAD18.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:831px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60px;top:273px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT INNER<br>LOWER PILLAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222px;top:153px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INSIDE SILL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:114px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CENTER INNER<br>PILLAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:685px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT SIDE FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:22px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>: New high-tension steel sheet<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:323px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INSIDE SILL<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:5px;top:376px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT SIDE<br>CROSS-MEMBER A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:151px;top:202px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT INNER<br>UPPER PILLAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778px;top:161px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>REAR FLOOR CENTER<br>CROSS-MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:810px;top:416px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CENTER PILLLAR<br>UPPER STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:606px;top:664px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT PILLAR UPPER STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:804px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>WHEELHOUSE LOWER EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:766px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SIDE FRAME GUSSET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646px;top:25px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT FLOOR CENTER<br>CROSS-MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694px;top:68px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MIDDLE FLOOR<br>CROSS-MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:118px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>REAR FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799px;top:467px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INSIDE SILL<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789px;top:509px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SIDE SILL<br>REAR STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:571px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CENTER PILLLAR<br>LOWER STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659px;top:634px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SIDE SILL STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:696px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT FLOOR FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:723px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT PILLAR LOWER STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:473px;top:752px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>WHEELHOUSE UPPER MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417px;top:778px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT DAMPER EXTENSION<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}