with(document) {
write("<v:group id=\"group4\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:415px;\" coordsize=\"950,415\">");
write("<v:rect id=\"rect4\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:415px;\">");
write("<img id=\"img4\" name=\"PrtImgId\" src=\"../img/SMR7ES0J36200000000CAAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:415px;border-color:#ffffff\">");
write("<p id=\"p4_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:21px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Enlarged view of sensor element<br></b></nobr>");
write("</p>");
write("<p id=\"p4_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:77px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DETECTING PIEZOELECTRIC<br>PARTS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:135px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>OSCILLATORS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:136px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>SUPPORT PIN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:227px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DRIVING <br>PIEZOELECTRIC<br>PART<br></b></nobr>");
write("</p>");
write("<p id=\"p4_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:378px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>METAL BLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:363px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>MONITORING PIEZOELECTRIC<br>PART<br></b></nobr>");
write("</p>");
write("<p id=\"p4_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:287px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Bend<br></b></nobr>");
write("</p>");
write("<p id=\"p4_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:198px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Oscillation<br></b></nobr>");
write("</p>");
write("<p id=\"p4_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:228px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Coriolis force<br></b></nobr>");
write("</p>");
write("<p id=\"p4_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603px;top:143px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Turn to<br>right<br></b></nobr>");
write("</p>");
write("<p id=\"p4_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736px;top:176px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Coriolis force<br></b></nobr>");
write("</p>");
write("<p id=\"p4_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:852px;top:197px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Oscillation<br></b></nobr>");
write("</p>");
write("<p id=\"p4_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:600px;top:22px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Sensor element top view<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}