with(document) {
write("<v:group id=\"group5\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1039px;\" coordsize=\"950,1039\">");
write("<v:rect id=\"rect5\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1039px;\">");
write("<img id=\"img5\" name=\"PrtImgId\" src=\"../img/SMR7EE0J54200000000DEAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1039px;border-color:#ffffff\">");
write("<p id=\"p5_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:25px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>IG2 CUT RELAY<br></b>Wire colors: ORN, GRY,<br>YEL and LT GRN*<sup>1</sup> (or WHT)*<sup>2</sup><br></nobr>");
write("</p>");
write("<p id=\"p5_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:76px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ACC CUT RELAY<br></b>Wire colors: RED, GRY,<br>GRN and LT GRN*<sup>1</sup> (or WHT)*<sup>2</sup><br></nobr>");
write("</p>");
write("<p id=\"p5_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658px;top:792px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>STARTER CUT RELAY<br></b>Wire colors: WHT, RED,<br>GRY and LT GRN<br></nobr>");
write("</p>");
write("<p id=\"p5_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658px;top:886px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INHIBITER RELAY<br></b>Wire colors: GRY, WHT,<br>BLK and GRN<br></nobr>");
write("</p>");
write("<p id=\"p5_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658px;top:846px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Wire colors: WHT, RED,<br>GRY, and WHT<br></nobr>");
write("</p>");
write("<p id=\"p5_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658px;top:938px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Wire colors: GRY, BLK,<br>BLK, and LT GRN<br></nobr>");
write("</p>");
write("<p id=\"p5_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:849px;top:807px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>*<sup>1</sup><br></nobr>");
write("</p>");
write("<p id=\"p5_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:853px;top:938px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>*<sup>2</sup><br></nobr>");
write("</p>");
write("<p id=\"p5_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:853px;top:901px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>*<sup>1</sup><br></nobr>");
write("</p>");
write("<p id=\"p5_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:850px;top:846px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>*<sup>2</sup><br></nobr>");
write("</p>");
write("<p id=\"p5_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:462px;top:726px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SRS UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298px;top:788px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HEADLIGHT WASHER CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:840px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>NAVIGATION UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:142px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HEADLIGHT AUTO LEVELING<br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:88px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>AUDIO UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3px;top:990px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>*<sup>1</sup>: M/T<br></nobr>");
write("</p>");
write("<p id=\"p5_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3px;top:1009px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>*<sup>2</sup>: i-SHIFT System<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}