with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E00R41100000000YDA191.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:66px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>Front side frame locating hole φ16 (0.63)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:66px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>a<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:83px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>b1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:100px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>b2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:117px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>b3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:135px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>c1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:152px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>c2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:169px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>c3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:186px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>d1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:213px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>d2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:240px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>e1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:257px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>e2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:274px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>e3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:291px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>e4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:308px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>f1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:325px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>f2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:342px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>f3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:359px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>g1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:376px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>g2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:66px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>h<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:83px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>i1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:100px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>i2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:117px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>j<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:134px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>k1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:151px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>k2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:169px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>l1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:186px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>l2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:83px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>For engine side mount φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:100px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>For engine side mount φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:117px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>For engine side mount φ12 (0.47)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:135px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>For transmission mount φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:152px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>For transmission mount φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:169px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>For transmission mount point<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:186px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>For torque rod mount upper<br>φ14.5 (0.57) x 19.5 (0.77) slot <br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:213px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>For torque rod mount lower<br>φ21 (0.83) x 29 (1.14) slot <br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:240px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>For front damper mount φ11.5 (0.45)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:257px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>Front damper center point φ69.5 (2.74)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:274px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>For front damper mount φ11.5 (0.45)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:291px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>For front damper mount φ11.5 (0.45)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:308px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>For front subframe mount φ16 (0.63)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:325px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>For front subframe mount φ16 (0.63)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:342px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>For front subframe mount φ16 (0.63)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:359px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>Right, outrigger locating hole φ16 (0.63)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:377px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>Left, for front subframe mount φ16 (0.63) x 20 (0.8) slot<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:66px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>Outrigger locating hole φ27.4 (1.08)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:83px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>Right, front floor front cross-member locating hole φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:100px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>Left, front floor front cross-member locating hole φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:117px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>Front floor locating hole φ50 (2.0) forward<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:135px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>Right, front floor frame locating hole φ20 (0.8) forward<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:152px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>Left, front floor frame locating hole φ20 (0.8) forward<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:169px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>Right, front floor frame locating hole φ15 (0.59) rearward<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:186px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>Left, front floor frame locating hole φ15 (0.59) rearward<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:227px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT e1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:249px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>3-φ11.5 (0.45)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:846px;top:281px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT e2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:854px;top:365px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>φ110 (4.33)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:860px;top:466px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT e3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659px;top:489px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT e2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:440px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT e4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:442px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>44.4 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820px;top:440px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>75.6 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:661px;top:319px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>120 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789px;top:499px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>6.1 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730px;top:596px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>φ69.5 (2.74)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:671px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT a<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:639px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT b1<br>M12 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:987px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT b2<br>M12 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339px;top:576px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT b3<br>M12 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:1023px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT c1<br>M12 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:951px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT c2<br>M12 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:607px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT c3<br>M8 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:501px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT d1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:541px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT d2<br>M12 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:591px;top:630px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT e2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:574px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT e1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:679px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT e4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604px;top:657px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT e3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:748px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT f1<br>M14 x 1.5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:794px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT f2<br>M14 x 1.5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:640px;top:1054px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT g1, g2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:1020px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT f3<br>M14 x 1.5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:993px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT h<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737px;top:941px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT i1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:780px;top:760px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT j<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:753px;top:989px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT k1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:841px;top:1070px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT l1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744px;top:914px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT i2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:781px;top:1035px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT k2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:887px;top:1042px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>POINT l2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:1077px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>VERTICAL LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42px;top:869px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>BASE LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:563px;top:629px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562px;top:842px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718px;top:633px;font-weight:normal;font-size:7.20pt;\">");
write("<nobr><b>[ SECTION: AA ]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:29px;font-weight:normal;font-size:8.17pt;\">");
write("<nobr><b>Unit: mm (in.)<br>φ: Inner diameter<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("<v:line id=\"bl1_1\" name=\"prt_bl\" class=\"drag\" from=\"135,829\" to=\"134,718\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_1\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"601 (23.7) e1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_2\" name=\"prt_bl\" class=\"drag\" from=\"156,829\" to=\"155,717\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_2\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"596 (23.5) e2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_3\" name=\"prt_bl\" class=\"drag\" from=\"176,829\" to=\"175,718\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_3\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"595 (23.43) e3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_4\" name=\"prt_bl\" class=\"drag\" from=\"196,829\" to=\"195,718\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_4\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"594 (23.39) e4\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_5\" name=\"prt_bl\" class=\"drag\" from=\"217,839\" to=\"216,732\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_5\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"508 (20.0) d1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_6\" name=\"prt_bl\" class=\"drag\" from=\"236,839\" to=\"235,733\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_6\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"463 (18.2) b3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_7\" name=\"prt_bl\" class=\"drag\" from=\"256,853\" to=\"255,746\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_7\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"437 (17.2) d2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_8\" name=\"prt_bl\" class=\"drag\" from=\"276,853\" to=\"275,748\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_8\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"387 (15.2) c3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_9\" name=\"prt_bl\" class=\"drag\" from=\"294,969\" to=\"293,874\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_9\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"267 (10.5) c2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_10\" name=\"prt_bl\" class=\"drag\" from=\"311,969\" to=\"310,865\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_10\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"265 (10.4) b2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_11\" name=\"prt_bl\" class=\"drag\" from=\"328,969\" to=\"327,867\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_11\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"263 (10.35) c1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_12\" name=\"prt_bl\" class=\"drag\" from=\"346,969\" to=\"345,858\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_12\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"258 (10.16) b1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_13\" name=\"prt_bl\" class=\"drag\" from=\"525,964\" to=\"524,840\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_13\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"143 (5.63) f1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_14\" name=\"prt_bl\" class=\"drag\" from=\"551,1013\" to=\"550,919\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_14\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"74 (2.9) h\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_15\" name=\"prt_bl\" class=\"drag\" from=\"568,1013\" to=\"567,920\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_15\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"46 (1.8) f3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_16\" name=\"prt_bl\" class=\"drag\" from=\"604,1013\" to=\"603,918\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_16\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"3 (0.12) f2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_17\" name=\"prt_bl\" class=\"drag\" from=\"701,980\" to=\"700,866\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_17\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"62 (2.4) i1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_18\" name=\"prt_bl\" class=\"drag\" from=\"718,980\" to=\"717,866\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_18\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"58 (2.3) i2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_19\" name=\"prt_bl\" class=\"drag\" from=\"851,982\" to=\"850,870\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_19\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"43 (1.7) k1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_20\" name=\"prt_bl\" class=\"drag\" from=\"870,982\" to=\"869,871\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_20\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"86 (3.4) k2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_21\" name=\"prt_bl\" class=\"drag\" from=\"891,982\" to=\"890,857\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_21\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"75 (2.95) l1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_22\" name=\"prt_bl\" class=\"drag\" from=\"937,988\" to=\"936,860\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_22\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"72 (2.83) l2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_23\" name=\"prt_bl\" class=\"drag\" from=\"399,952\" to=\"398,843\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_23\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"169 (6.65) a\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_24\" name=\"prt_bl\" class=\"drag\" from=\"586,1013\" to=\"585,837\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_24\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"42.9 (1.69) g1, g2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.20pt;\"/>");
write("</v:line>");
write("</v:group>");
}