with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\" coordsize=\"950,1071\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1071px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SMR7EE0J54200000000DEAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276px;top:20px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>IG2 CUT RELAY<br></b>Wire colors: ORN, GRY,<br>YEL and LT GRN*<sup>1</sup> (or WHT)*<sup>2</sup><br></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276px;top:71px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ACC CUT RELAY<br></b>Wire colors: RED, GRY,<br>GRN and LT GRN*<sup>1</sup> (or WHT)*<sup>2</sup><br></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:796px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>STARTER CUT RELAY<br></b>Wire colors: WHT, RED,<br>GRY and LT GRN<br></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:889px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INHIBITER RELAY<br></b>Wire colors: GRY, WHT,<br>BLK and GRN<br></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:850px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Wire colors: WHT, RED,<br>GRY and WHT<br></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:942px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Wire colors: GRY, BLK,<br>BLK and LT GRN<br></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:811px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>*<sup>1</sup><br></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:942px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>*<sup>2</sup><br></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:904px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>*<sup>1</sup><br></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:850px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>*<sup>2</sup><br></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360px;top:697px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SRS UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:739px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HEADLIGHT WASHER CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:712px;top:801px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>NAVIGATION UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732px;top:27px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HEADLIGHT AUTO LEVELING<br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:626px;top:79px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>AUDIO UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:18px;top:466px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>IMMOBILIZER-<br>KEYLESS CONTROL<br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3px;top:1023px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>*<sup>1</sup>: M/T<br></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3px;top:1042px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>*<sup>2</sup>: i-SHIFT System<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}