with(document) {
write("<v:group id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/SMR9EQP000000000000EBA303.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:81px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:81px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:81px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:88px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:88px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:88px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:95px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:95px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:109px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>M/T<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:116px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>With i−SHIFT system<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:102px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:102px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:109px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:109px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:131px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>R18A2 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:138px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>L13Z1 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:116px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:116px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:95px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>With inertia switch<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:102px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Without inertia switch<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:124px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:123px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:131px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:131px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:783px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ALTERNATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:588px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:588px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:588px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:588px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:571px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:551px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:538px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:766px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RECTIFIER<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:604px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VOLTAGE REGULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:571px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:571px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:571px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:571px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:538px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:538px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:538px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:464px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:524px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529px;top:463px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:174px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:247px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181px;top:247px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:313px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:210px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:313px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:402px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>STARTER<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:210px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:188px;top:135px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:135px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293px;top:503px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>74<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:494px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>79<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:494px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>80<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:503px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>75<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506px;top:494px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>46<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:115px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:122px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:477px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM (4−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:478px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:145px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>With super locking<br></b></nobr>");
write("</p>");
write("<p id=\"p3_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:152px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>With HID<br></b></nobr>");
write("</p>");
write("<p id=\"p3_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:159px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Without HID<br></b></nobr>");
write("</p>");
write("<p id=\"p3_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:138px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:138px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p3_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:145px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*10<br></b></nobr>");
write("</p>");
write("<p id=\"p3_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:145px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:152px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:152px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*11<br></b></nobr>");
write("</p>");
write("<p id=\"p3_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:477px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(5−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:477px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p3_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:421px;top:477px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(6−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:477px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p3_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:159px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:159px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*12<br></b></nobr>");
write("</p>");
write("<p id=\"p3_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:124px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>K20Z4 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p3_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278px;top:467px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 1 (100 A) <br>(BAT) FUSE <br>(1−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:467px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 3 (10 A) <br>FUSE <br>(3−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:178px;top:115px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BATTERY <br>(1−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:100px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>STARTER <br>CUT RELAY 2 <br>(2−B) <br>(2−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-105px;top:706px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEATER CONTROL UNIT/CLIMATE CONTROL UNIT (14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-105px;top:671px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HAZARD WARNING SWITCH LIGHT (10−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-105px;top:635px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEADLIGHT LEVELING SWITCH LIGHT (9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-105px;top:827px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DAYTIME RUNNING LIGHTS RELAY (KS model) (15−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-105px;top:806px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LICENSE PLATE LIGHTS (Except KS model) (10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-105px;top:798px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT FRONT POSITION LIGHT (Except KS model) (10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-105px;top:791px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT FRONT POSITION LIGHT (Except KS model) (10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-105px;top:813px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT TAILLIGHTS (Except KS model) (10−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-105px;top:820px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT TAILLIGHTS (Except KS model) (10−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-105px;top:742px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUDIO REMOTE SWITCH LIGHT (18−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-111px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S POWER WINDOW SWITCH (11−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-111px;top:227px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>POWER WINDOW MASTER SWICTH (11−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-105px;top:628px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SELECT/RESET/INFORMATION SWITCH LIGHT (7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-105px;top:692px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S SEAT HEATER SWITCH LIGHT (13−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-105px;top:699px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT PASSENGER'S SEAT HEATER SWITCH LIGHT (13−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-105px;top:685px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PARKING and BACK−UP SENSOR OFF SWITCH LIGHT (12−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-105px;top:678px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEADLIGHT WASHER SWITCH LIGHT (11−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-105px;top:664px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT PASSENGER'S FOOTWELL LIGHT (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-4px;top:449px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:13px;top:449px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*12<br></b></nobr>");
write("</p>");
write("<p id=\"p3_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-3px;top:502px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:13px;top:502px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*12<br></b></nobr>");
write("</p>");
write("<p id=\"p3_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-1px;top:553px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:15px;top:553px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*12<br></b></nobr>");
write("</p>");
write("<p id=\"p3_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-7px;top:582px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:9px;top:582px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*12<br></b></nobr>");
write("</p>");
write("<p id=\"p3_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-105px;top:777px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HFT−VOICE CONTROL SWITCH (19−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-105px;top:614px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CRUISE CONTROL MAIN SWITCH/ <br>SET/RESUME/CANCEL SWITCH LIGHT (7−C)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}