with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SMR9ERQA20300000000DBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:55px;top:204px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>12P JUNCTION CONNECTOR<br>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201px;top:37px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>FRP SENSOR<br>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:38px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>EGR CONTROL<br>SOLENOID VALVE<br>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:28px;top:36px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>MAP SENSOR/<br>IAT SENSOR 2<br>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458px;top:205px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>13P CONNECTOR (9)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96px;top:370px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>33P CONNECTOR (12)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:537px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX H (21)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:36px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CMP SENSOR<br>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:786px;top:36px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>TURBOCHARGER<br>BOOST CONTROL<br>SOLENOID VALVE<br>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302px;top:205px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>FUEL RAIL<br>PRESSURE CONTROL<br>VALVE (8)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:676px;top:205px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>MAF SENSOR/<br>IAT SENSOR 1<br>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:204px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>2P CONNECTOR<br>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:707px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>GLOW PLUG<br>CONTROL MODULE<br>(23)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:27px;top:875px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ECT<br>SENSOR 2 (29)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:802px;top:707px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>OUTPUT SHAFT<br>(COUNTERSHAFT)<br>SPEED SENSOR (28)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:707px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>FUEL <br>TEMPERATURE<br>SENSOR (24)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:707px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>FUEL HEATER<br>(25)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:541px;top:707px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>FUEL FILTER<br>SOLENOID VALVE<br>(26)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:707px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>REVERSE LOCK<br>SOLENOID VALVE<br>(27)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560px;top:369px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>TEST TACHOMETER<br>CONNECTOR (14)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:701px;top:370px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX G (15)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833px;top:369px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ELD A (16)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:876px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>IMRC POSITION<br>SENSOR (33)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:875px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>2P CONNECTOR<br>(31)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:537px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX D<br>(17)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:537px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX E<br>(18)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:369px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>23P CONNECTOR (13)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566px;top:537px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX K (19)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:699px;top:537px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX J (20)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:875px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ECT<br>SENSOR 1 (30)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:28px;top:706px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>10P CONNECTOR<br>(22)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:37px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>EGT SENSOR 1<br>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:875px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>INTAKE SHUTTER<br>VALVE (32)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:1006px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}