with(document) {
write("<v:group id=\"group6\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1023px;\" coordsize=\"950,1023\">");
write("<v:rect id=\"rect6\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1023px;\">");
write("<img id=\"img6\" name=\"PrtImgId\" src=\"../img/SMR9EQ2A20300000000DBAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1023px;border-color:#ffffff\">");
write("<p id=\"p6_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:431px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ECT SENSOR 2 <br>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:555px;top:232px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ECM A (□) (7)*<br></b></nobr>");
write("</p>");
write("<p id=\"p6_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:102px;top:53px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>23P CONNECTOR <br>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:77px;top:232px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY<br>BOX CONNECTOR D <br>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:233px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY<br>BOX CONNECTOR F <br>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:53px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ELD (3)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:695px;top:52px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY <br>BOX CONNECTOR E <br>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:53px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>TEST TACHOMETER<br>CONNECTOR <br>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:777px;top:232px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CLUTCH ACTUATOR <br>(TCM) (8) <br>(with i-SHIFT)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:431px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>A/C PRESSURE SENSOR <br>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:564px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br>*: Connector with female terminals (single outline): view from terminal side<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}