with(document) {
write("<v:group id=\"group10\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:995px;\" coordsize=\"950,995\">");
write("<v:rect id=\"rect10\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:995px;\">");
write("<img id=\"img10\" name=\"PrtImgId\" src=\"../img/SMR9EQPJ54230100000EAAD10.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:995px;border-color:#ffffff\">");
write("<p id=\"p10_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:958px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:958px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Engine compartment wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p10_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88px;top:957px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p10_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:957px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p10_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302px;top:958px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Combination switch wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p10_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:165px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:108px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:108px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:379px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p10_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:251px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:251px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638px;top:165px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G651<br></b></nobr>");
write("</p>");
write("<p id=\"p10_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:251px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Brake fluid level switch<br></b></nobr>");
write("</p>");
write("<p id=\"p10_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:290px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Hood switch (With security)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:622px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:622px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p10_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:572px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p10_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:572px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:622px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Starter switch<br></b></nobr>");
write("</p>");
write("<p id=\"p10_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:722px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G403<br></b></nobr>");
write("</p>");
write("<p id=\"p10_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:536px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:536px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p10_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:536px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Cable reel<br></b></nobr>");
write("</p>");
write("<p id=\"p10_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:758px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:758px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p10_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:829px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Memory erase signal (MES) connector<br></b></nobr>");
write("</p>");
write("<p id=\"p10_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:794px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:794px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p10_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:829px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:829px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p10_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:758px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SRS unit<br></b></nobr>");
write("</p>");
write("<p id=\"p10_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:886px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G404<br></b></nobr>");
write("</p>");
write("<p id=\"p10_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:479px;top:96px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:108px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:122px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:136px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:322px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:322px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:322px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Headlight washer motor*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p10_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:415px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>EPS control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p10_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:415px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:415px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:494px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G402<br></b></nobr>");
write("</p>");
write("<p id=\"p10_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:280px;top:958px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p10_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:794px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SRS unit<br></b></nobr>");
write("</p>");
write("<p id=\"p10_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:551px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Ignition key switch<br></b></nobr>");
write("</p>");
write("<p id=\"p10_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:586px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>VSA OFF switch*<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p10_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:572px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Headlight leveling switch (Without HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:958px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Floor wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p10_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:502px;top:957px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p10_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:165px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p10_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:486px;top:958px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p10_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:303px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Clutch pedal position switch A (M/T)*<sup>4</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p10_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:601px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>VSA OFF−headlight washer switch*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p10_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:658px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p10_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:658px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:658px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Inhibitor relay<br></b></nobr>");
write("</p>");
write("<p id=\"p10_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:672px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Inhibitor relay*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p10_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:208px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:208px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:208px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Power transistor<br></b></nobr>");
write("</p>");
write("<p id=\"p10_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:65px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p10_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:264px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Clutch pedal position switch B (M/T) <br>(With cruise control)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:29px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:29px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p10_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:29px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>With i−SHIFT system<br></b></nobr>");
write("</p>");
write("<p id=\"p10_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:40px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>With headlight washer<br></b></nobr>");
write("</p>");
write("<p id=\"p10_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:40px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p10_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:40px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:52px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:52px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p10_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:52px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Withont headlight washer<br></b></nobr>");
write("</p>");
write("<p id=\"p10_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:63px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>R18A2 engine and L13Z1 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p10_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:63px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p10_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:63px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}