with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:1900px; height:950px;\" coordsize=\"1900,950\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:1900px;height:950px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9ERP000000000000EBAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:1900px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1166px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1609px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1839px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:23px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>Gauge Control Module (Tach)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:498px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:648px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677px;top:529px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722px;top:529px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:675px;top:786px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G502<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:648px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:786px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821px;top:391px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MIAN CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:626px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:676px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:676px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUDIO UNIT (16−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:619px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:529px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:677px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:677px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:648px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HAZARD WARNING SWITCH LIGHT (8−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:670px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VSA OFF SWITCH LIGHT (14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:634px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:634px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:656px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:656px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:620px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:620px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:582px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:570px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:539px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:529px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:529px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:567px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:567px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:581px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:581px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:581px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUDIO UNIT (16−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:598px;top:555px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DIODE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:655px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:626px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AMBIENT LIGHT (8−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:258px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:458px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319px;top:225px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE (TACH) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:633px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:633px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S FOOTWELL LIGHT (8−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:648px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:670px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:670px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1648px;top:81px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1661px;top:81px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1667px;top:81px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1667px;top:88px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1661px;top:88px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1648px;top:88px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:655px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S SEAT HEATER SWITCH LIGHT (11−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:619px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEADLIGHT LEVELING SWITCH LIGHT (7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:669px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:669px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUNSHADE SWITCH LIGHT (14−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:801px;top:360px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INDICATOR DRIVE CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:788px;top:529px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1253px;top:360px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INDICATOR DRIVE CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1189px;top:391px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MAIN CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1135px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1135px;top:641px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1135px;top:681px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1123px;top:786px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1125px;top:715px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1285px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1390px;top:259px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1125px;top:529px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1271px;top:529px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:648px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEADLIGHT WASHER SWITCH LIGHT (9−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:640px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:640px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT PASSENGER'S FOOTWELL LIGHT (8−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:662px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:662px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT PASSENGER'S SEAT HEATER SWITCH LIGHT (11−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:691px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:691px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:684px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VOICE CONTROL SWITCH (17−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:684px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:684px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:677px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUDIO REMOTE SWITCH (16−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:691px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HFT−VOICE CONTROL SWITCH (17−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:609px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:556px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>108<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:582px;top:609px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>89<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790px;top:600px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:336px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FAIL−SAFE <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:432px;top:268px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>COMPULSORY <br>TURNING−ON <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:268px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>COMPULSORY <br>TURNING−OFF <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:314px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MALFUNCTION <br>INDICATOR <br>LAMP (MIL) <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:635px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CRUISE CONTROL MAIN/SET/RESUME/<br>CANCEL SWITCH LIGHT (5−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:567px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HVAC <br>SUBDISPLAY UNIT (12−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:656px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEATER CONTROL UNIT/ <br>CLIMATE CONTROL UNIT (12−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:811px;top:314px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VSA <br>ACTIVATION <br>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:873px;top:314px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VSA <br>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:988px;top:314px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SRS <br>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:931px;top:314px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ABS <br>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:314px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LOW <br>FUEL  <br>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:314px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>EPS <br>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1041px;top:314px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GLOW PLUG <br>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:771px;top:620px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VSA OFF SWITCH <br>(14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:314px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LOW TIRE <br>PRESSURE <br>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1117px;top:314px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CHARGING <br>SYSTEM <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1210px;top:314px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LOW OIL <br>PRESSURE <br>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1161px;top:314px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SEAT BELT <br>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1272px;top:314px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRAKE <br>SYSTEM <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1143px;top:650px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRAKE FLUID <br>LEVEL SWITCH <br>(Closed : <br>Float down) <br>(Open : <br>Float up)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1294px;top:650px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PARKING <br>BRAKE <br>SWITCH <br>(Closed : <br>Lever pulled)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1405px;top:310px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LIGHTS−ON <br>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1352px;top:239px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INDICATOR DIMMING CIRCUIT <br>(6−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1343px;top:309px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT <br>FOG LIGHT <br>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1467px;top:309px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REAR <br>FOG LIGHT <br>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:620px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SELECT/RESET/INFORMATION <br>SWITCH LIGHT (5−C)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}