with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:385px;\" coordsize=\"475,385\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:385px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9EQPJ14235000000FAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:385px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:48px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:357px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117px;top:340px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>AUDIO UNIT CONNECTOR B (20P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160px;top:83px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>TELM SIG+ (GRN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:308px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>TELM SIG+ (GRN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:212px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>TELM SIG— (RED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:170px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>TELM SIG— (RED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:17px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>HANDS FREE TELEPHONE CONTROL UNIT <br>28P CONNECTOR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}