with(document) {
write("<v:group id=\"group8\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:383px;\" coordsize=\"950,383\">");
write("<v:rect id=\"rect8\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:383px;\">");
write("<img id=\"img8\" name=\"PrtImgId\" src=\"../img/SMR7E81A20300000000DBID08.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:383px;border-color:#ffffff\">");
write("<p id=\"p8_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562px;top:171px;font-weight:normal;font-size:7.40pt;\">");
write("<nobr><b>SCATOLA DI DERIVAZIONE (8)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:25px;font-weight:normal;font-size:7.40pt;\">");
write("<nobr><b>SCATOLA DI GIUNZIONE (4)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:170px;font-weight:normal;font-size:7.40pt;\">");
write("<nobr><b>SCATOLA DI GIUNZIONE (6)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:38px;top:23px;font-weight:normal;font-size:7.40pt;\">");
write("<nobr><b>INTERRUTTORE INERZIALE (1)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:21px;font-weight:normal;font-size:7.40pt;\">");
write("<nobr><b>SCATOLA DI GIUNZIONE (3)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:211px;top:22px;font-weight:normal;font-size:7.40pt;\">");
write("<nobr><b>SCATOLA DI GIUNZIONE (2)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:753px;top:170px;font-weight:normal;font-size:7.40pt;\">");
write("<nobr><b>SCATOLA DI GIUNZIONE (9)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:772px;top:27px;font-weight:normal;font-size:7.40pt;\">");
write("<nobr><b>SCATOLA DI GIUNZIONE (5)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:165px;font-weight:normal;font-size:7.40pt;\">");
write("<nobr><b>SCATOLA DI GIUNZIONE (7)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1px;top:313px;font-weight:normal;font-size:8.67pt;\">");
write("<nobr><b></b>NOTA:<br>· Connettore con terminali maschio (cornice doppia): visto dal lato terminale<br>·Connettore con terminali femmina (cornice singola): visto dal lato cablaggio<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}