with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E55G24100000000DAID01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653px;top:832px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>VENTOLA RADIATORE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373px;top:992px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>VENTOLA CONDENSATORE A/C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575px;top:16px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RELÈ FRIZIONE COMPRESSORE A/C<br><a href=\"javascript:CtsProc('0','000000000002360','i000')\"></b>Verifica,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:67px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SCATOLA FUSIBILI/<br>RELÈ VANO MOTORE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:84px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RELÈ COMANDO VENTOLA<br><a href=\"javascript:CtsProc('0','000000000002360','iR05')\"></b>Verifica,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:882px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SENSORE TEMPERATURA ARIA ESTERNA<br><a href=\"javascript:CtsProc('0','000000000000060','i000')\"></b>Verifica,</a><br> nel manuale d'officina, numero categorico 62SMR00B<br><a href=\"javascript:CtsProc('0','000000000000061','i000')\">Sostituzione,</a><br> nel manuale d'officina, numero categorico 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206px;top:328px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1px;top:1056px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>In figura viene mostrato il modello con guida a sinistra, quello con guida a destra è simile.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}