with(document) {
write("<v:group id=\"group5\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:972px;\" coordsize=\"950,972\">");
write("<v:rect id=\"rect5\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:972px;\">");
write("<img id=\"img5\" name=\"PrtImgId\" src=\"../img/SMR7EG0J54230100000EAID05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:972px;border-color:#ffffff\">");
write("<p id=\"p5_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:73px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:74px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:374px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Massa radiante riscaldatore PTC<br></b></nobr>");
write("</p>");
write("<p id=\"p5_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:395px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Massa radiante riscaldatore PTC<br></b></nobr>");
write("</p>");
write("<p id=\"p5_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:352px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Massa radiante riscaldatore PTC<br></b></nobr>");
write("</p>");
write("<p id=\"p5_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:374px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:373px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:395px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:395px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:352px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:352px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:331px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Massa radiante riscaldatore PTC<br></b></nobr>");
write("</p>");
write("<p id=\"p5_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:330px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:331px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:309px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Riscaldatore carburante<br></b></nobr>");
write("</p>");
write("<p id=\"p5_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:274px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruttore sedimenti<br></b></nobr>");
write("</p>");
write("<p id=\"p5_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:245px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruttore B di posizione pedale frizione<br></b></nobr>");
write("</p>");
write("<p id=\"p5_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:231px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruttore A di posizione pedale frizione<br></b></nobr>");
write("</p>");
write("<p id=\"p5_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:195px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Transistor di potenza<br></b></nobr>");
write("</p>");
write("<p id=\"p5_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:194px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:195px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:923px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p5_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:130px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p5_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:922px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p5_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:924px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Cablaggio pianale<br></b></nobr>");
write("</p>");
write("<p id=\"p5_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:602px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruttore livellamento fari<br></b></nobr>");
write("</p>");
write("<p id=\"p5_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:617px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruttore disattivazione VSA<br></b></nobr>");
write("</p>");
write("<p id=\"p5_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:581px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruttore chiave di accensione<br></b></nobr>");
write("</p>");
write("<p id=\"p5_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:781px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Centralina SRS<br></b></nobr>");
write("</p>");
write("<p id=\"p5_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306px;top:923px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p5_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:545px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G402<br></b></nobr>");
write("</p>");
write("<p id=\"p5_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:488px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:487px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:488px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Centralina EPS<br></b></nobr>");
write("</p>");
write("<p id=\"p5_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:295px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Motorino lavafari<br></b></nobr>");
write("</p>");
write("<p id=\"p5_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:295px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:295px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:102px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:88px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:74px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:476px;top:62px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Presa scatola fusibili/relè)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:874px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G404<br></b></nobr>");
write("</p>");
write("<p id=\"p5_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:745px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Centralina SRS<br></b></nobr>");
write("</p>");
write("<p id=\"p5_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:816px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p5_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:817px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:780px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p5_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:781px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:817px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Connettore segnale cancellazione memoria (MES)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:745px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p5_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:745px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:567px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Arrotolatore<br></b></nobr>");
write("</p>");
write("<p id=\"p5_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:566px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p5_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:567px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:731px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G403<br></b></nobr>");
write("</p>");
write("<p id=\"p5_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:638px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruttore di avviamento<br></b></nobr>");
write("</p>");
write("<p id=\"p5_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:602px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:602px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p5_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:637px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p5_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:638px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:674px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Relè di inibizione<br></b></nobr>");
write("</p>");
write("<p id=\"p5_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:674px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:673px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p5_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:259px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruttore cofano (con antifurto)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:217px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruttore livello liquido freni<br></b></nobr>");
write("</p>");
write("<p id=\"p5_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:167px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Centralina lavafari<br></b></nobr>");
write("</p>");
write("<p id=\"p5_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:635px;top:131px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G651<br></b></nobr>");
write("</p>");
write("<p id=\"p5_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:217px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:216px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:467px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p5_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:166px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:167px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:74px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:73px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:131px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:924px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Cablaggio devioluci<br></b></nobr>");
write("</p>");
write("<p id=\"p5_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:922px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p5_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:922px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p5_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:121px;top:924px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Cablaggio vano motore<br></b></nobr>");
write("</p>");
write("<p id=\"p5_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96px;top:923px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:371px;top:31px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SCATOLA FUSIBILI/<br>RELÈ SOTTO PLANCIA<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}