with(document) {
write("<v:group id=\"group6\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:847px;\" coordsize=\"950,847\">");
write("<v:rect id=\"rect6\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:847px;\">");
write("<img id=\"img6\" name=\"PrtImgId\" src=\"../img/SMR7EE0J54200000000DEID06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:847px;border-color:#ffffff\">");
write("<p id=\"p6_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677px;top:18px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RELÈ ACCENDISIGARI<br></b>Colori fili: BLU, WHT,<br>BLK e PUR<br></nobr>");
write("</p>");
write("<p id=\"p6_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677px;top:67px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RELÈ PRESA DI CORRENTE ACCESSORI<br></b>Colori fili: RED, YEL,<br>BLK e PUR<br></nobr>");
write("</p>");
write("<p id=\"p6_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:91px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RELÈ FENDINEBBIA<br></b>Colori fili: WHT, RED,<br>BLU e WHT<br></nobr>");
write("</p>");
write("<p id=\"p6_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:644px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RELÈ SUPERBLOCCAGGIO LATO DESTRO<br></b>Colori fili: BLU, WHT,<br>RED, BLK e WHT<br></nobr>");
write("</p>");
write("<p id=\"p6_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:692px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RELÈ SUPERBLOCCAGGIO LATO SINISTRO<br></b>Colori fili: ORN, WHT,<br>GRN, BLK e WHT<br></nobr>");
write("</p>");
write("<p id=\"p6_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:786px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RELÈ SBRINATORE SPECCHIETTI ELETTRICI<br></b>Colori fili: WHT, ORN,<br>GRY e WHT<br></nobr>");
write("</p>");
write("<p id=\"p6_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:722px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RELÈ AVVISATORE<br>ACUSTICO (Con antifurto)<br></b>Colori fili: WHT, GRN,<br>ORN e WHT<br></nobr>");
write("</p>");
write("<p id=\"p6_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:111px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CENTRALINA RISCALDAMENTO/<br>CENTRALINA CLIMATIZZATORE<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}