with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:543px;\" coordsize=\"950,543\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:543px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E00J46636200000BBID01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:543px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:53px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Spia<br>immobilizzatore<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:23px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Funzionamento<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:50px;top:48px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Guasto linea<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372px;top:61px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Avviamento motore<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:54px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Registrazione<br>chiave<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:623px;top:54px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Comunicazione<br>tester<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:757px;top:63px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Funzionamento telecomando<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:121px;top:123px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Interruzione o<br>cortocircuito <br>linea +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:129px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Si accende,<br>quindi si spegne.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392px;top:135px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Possibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520px;top:135px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Possibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:135px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Possibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:801px;top:135px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Impossibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:137px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:177px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Interruzione o<br>cortocircuito <br>linea IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:186px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Lampeggio<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:186px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Impossibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:186px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Impossibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:640px;top:186px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Impossibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:186px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Possibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:187px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270px;top:237px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Lampeggio<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:237px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Impossibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:641px;top:237px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Impossibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:238px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Possibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520px;top:237px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Possibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:227px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Interruzione o<br>cortocircuito <br>linea S-NET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:239px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:302px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634px;top:277px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Immobilizzatore:<br>possibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624px;top:319px;font-weight:normal;font-size:5.73pt;\">");
write("<nobr><b>Sistema di accesso<br>con telecomando: impossibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:301px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Impossibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392px;top:301px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Possibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520px;top:301px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Possibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:293px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Si accende,<br>quindi si spegne.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:292px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Interruzione o<br>cortocircuito <br>linea B-CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:359px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Si accende,<br>quindi si spegne.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:365px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Impossibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:640px;top:364px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Impossibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:365px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Possibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392px;top:364px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Possibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:367px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:442px;font-weight:normal;font-size:5.73pt;\">");
write("<nobr><b>Interruzione o<br>cortocircuito linea KEYSW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:487px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Interruzione linea<br>GND (LG)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:430px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:494px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:759px;top:420px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>(nel commutatore di accensione<br>anziché nella chiave)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808px;top:402px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Possibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392px;top:429px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Possibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520px;top:429px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Possibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:650px;top:429px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Possibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:423px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Si accende,<br>quindi si spegne.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:405px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Interruzione linea<br>KEYSW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:121px;top:352px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Interruzione o<br>cortocircuito <br>linea K-LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:494px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Lampeggio<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:494px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Impossibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:640px;top:493px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Impossibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:493px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Impossibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800px;top:493px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Impossibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800px;top:456px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Impossibile<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:81px;font-weight:normal;font-size:8.32pt;\">");
write("<nobr><b>N.<br>terminale<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:79px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Causa<br>guasto<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}