with(document) {
write("<v:group id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/SMR7ET0000000000000EBI305.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:339px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:205px;top:582px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:848px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206px;top:702px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:582px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-59px;top:440px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CIRCUITO AZIONAMENTO INDICATORE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-39px;top:471px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CIRCUITO PRINCIPALE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:145px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*2 : SCATOLA FUSIBILI/RELÈ SOTTO PLANCIA<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:138px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*1 : SCATOLA FUSIBILI/RELÈ SOTTO PLANCIA<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:562px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:562px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:152px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*3 : Con antifurto<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:159px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4 : Senza antifurto<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:394px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SPIA<br>IMPIANTO<br>DI RICARICA<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:394px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SPIA BASSA<br>PRESSIONE<br>OLIO<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SPIA<br>CINTURE DI <br>SICUREZZA<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:318px;top:385px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SPIA<br>SISTEMA<br>FRENANTE<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:398px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SPIA<br>LUCI ACCESE<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:319px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CIRCUITO DI COMMUTAZIONE<br>LUCI ACCESE/FENDINEBBIA (5−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SPIA<br>FENDINEBBIA<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:390px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SPIA<br>RETRONEBBIA<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:647px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INTERRUTTORE<br>LIVELLO LIQUIDO FRENI<br>(Chiuso: <br>galleggiante in basso)<br>(Aperto: <br>galleggiante in alto)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:647px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INTERRUTTORE<br>FRENO DI<br>STAZIONAMENTO <br>(Chiuso: <br>leva tirata)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119px;top:403px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SPIA<br>SISTEMA SRS<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:399px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SPIA<br>ABS<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-49px;top:665px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INTERRUTTORE<br>DISATTIVAZIONE<br>SISTEMA VSA<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}