with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1085px;\" coordsize=\"950,1085\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1085px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SMR7E40J26346100000EAID02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1085px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:82px;top:606px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99px;top:538px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>T11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:1042px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G602<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:935px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99px;top:902px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99px;top:852px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:213px;top:852px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:213px;top:902px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:935px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:1042px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G602<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:213px;top:538px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>T12<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:606px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828px;top:42px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>: Linea CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275px;top:606px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:606px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:390px;top:606px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:606px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:318px;top:802px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>DEVIOSGANCIO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:449px;top:674px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:737px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:705px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:707px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:421px;top:734px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:734px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:724px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>AUTO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:674px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:674px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:674px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698px;top:720px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418px;top:136px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:412px;top:192px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:309px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Q6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:192px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:277px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:418px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B-CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:826px;top:606px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:566px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>R6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694px;top:1042px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G403<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698px;top:935px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:902px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:852px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698px;top:606px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:554px;top:606px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:566px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>E37<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731px;top:395px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:309px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SCATOLA FUSIBILI−RELÈ SOTTO PLANCIA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:538px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:449px;top:538px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:538px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:538px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:585px;top:850px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>INTERRUTTORE <br>PORTIERA<br>LATO CONDUCENTE<br>(Chiuso: <br>portiera aperta)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:728px;top:868px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>INTERRUTTORE<br>CHIAVE DI<br>ACCENSIONE<br>(Chiuso: <br>Chiave inserita)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:802px;top:496px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>CENTRALINA<br>IMMOBILIZZATORE−SISTEMA <br>DI ACCESSO<br>CON TELECOMANDO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:489px;top:93px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>CENTRALINA<br>IMMOBILIZZATORE−SISTEMA DI ACCESSO<br>CON TELECOMANDO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:104px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MODULO DI COMANDO<br>QUADRO STRUMENTI (CONTAGIRI)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:866px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>INTERRUTTORE<br>DI RECLINAZIONE<br>SCHIENALE SEDILE CONDUCENTE<br>(Chiuso: <br>leva tirata)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108px;top:896px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>INTERRUTTORE<br>DI RECLINAZIONE<br>SCHIENALE SEDILE <br>PASSEGGERO<br>(Chiuso: <br>leva tirata)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}