with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1063px;\" coordsize=\"950,1063\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1063px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7ETAJ54260462100EAID01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1063px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:891px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(100A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:422px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Modulatore−centralina VSA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:372px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Modulatore−centralina VSA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:193px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Modulo di comando cambio (TCM)*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:193px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:193px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:818px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLOCCO FUSIBILI MULTIPLI A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526px;top:929px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311px;top:868px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N.1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311px;top:879px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(EPS)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311px;top:891px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(70A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:879px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(BAT)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:868px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N.1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:886px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:930px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Centralina EPS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:797px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ALTERNATORE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:514px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:515px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Sensore rapporto aria/carburante (A/F)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:565px;top:514px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:676px;top:559px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:557px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743px;top:32px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>* : Cambio i-SHIFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:565px;top:686px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:676px;top:287px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:715px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Bobina di accensione N.3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:729px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Bobina di accensione N.4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:701px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Bobina di accensione N.2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:686px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:687px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Bobina di accensione N.1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:671px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N.14 (15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418px;top:816px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:601px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MODULO ECM (SUBRLY)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:600px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:499px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N.13 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:289px;top:332px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLOCCO FUSIBILI MULTIPLI C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:407px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N.3 (VSA FSR) (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:236px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:676px;top:237px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:221px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N.22 (10A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:108px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Motorino di avviamento<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:107px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:966px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:271px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N.21 (15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526px;top:286px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:290px;top:357px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N.3 (VSA MTR) (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:371px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526px;top:421px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:146px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SCATOLA FUSIBILI/RELÈ VANO MOTORE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:178px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N.5 (40 A)*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:82px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BATTERIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:150px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:57px;top:229px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707px;top:232px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SCATOLA FUSIBILI/RELÈ<br>SOTTO PLANCIA (HAZARD)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707px;top:282px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SCATOLA FUSIBILI/RELÈ<br>SOTTO PLANCIA (STOP, HORN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:307px;top:471px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RELÈ SECONDARIO<br>IMPIANTO PGM−FI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:307px;top:642px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RELÈ BOBINA<br>DI ACCENSIONE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:844px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MODULO ECM <br>(MRLY)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707px;top:553px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SCATOLA RELÈ/<br>FUSIBILI VANO MOTORE<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}