with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:447px;\" coordsize=\"950,447\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:447px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SMR7ES0D52100000000CAID03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:447px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:23px;top:218px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SENSORE RUOTA<br>POSTERIORE SINISTRA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:29px;top:142px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SENSORE RUOTA<br>POSTERIORE DESTRA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:372px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SENSORE RUOTA<br>ANTERIORE SINISTRA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:29px;top:296px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SENSORE RUOTA<br>ANTERIORE DESTRA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:218px;font-weight:normal;font-size:4.13pt;\">");
write("<nobr><b>Seleziona la bassa velocità<br>di rotazione della ruota<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353px;top:65px;font-weight:normal;font-size:5.72pt;\">");
write("<nobr><b>Rileva la<br>velocità della vettura<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:142px;font-weight:normal;font-size:5.72pt;\">");
write("<nobr><b>Aziona<br>l'elettrovalvola<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:143px;font-weight:normal;font-size:5.72pt;\">");
write("<nobr><b>ELETTROVALVOLA<br> POSTERIORE DESTRA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:218px;font-weight:normal;font-size:5.72pt;\">");
write("<nobr><b>ELETTROVALVOLA<br>POSTERIORE SINISTRA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:295px;font-weight:normal;font-size:5.72pt;\">");
write("<nobr><b>ELETTROVALVOLA<br> ANTERIORE DESTRA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:372px;font-weight:normal;font-size:5.72pt;\">");
write("<nobr><b>ELETTROVALVOLA<br> ANTERIORE SINISTRA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:17px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CENTRALINA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634px;top:142px;font-weight:normal;font-size:5.72pt;\">");
write("<nobr><b>Comando<br>sistema ABS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:547px;top:65px;font-weight:normal;font-size:5.72pt;\">");
write("<nobr><b>Entità di scorrimento<br>di riferimento<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:218px;font-weight:normal;font-size:5.72pt;\">");
write("<nobr><b>Aziona<br>l'elettrovalvola<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634px;top:218px;font-weight:normal;font-size:5.72pt;\">");
write("<nobr><b>Comando<br>sistema ABS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:295px;font-weight:normal;font-size:5.72pt;\">");
write("<nobr><b>Aziona<br>l'elettrovalvola<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634px;top:295px;font-weight:normal;font-size:5.72pt;\">");
write("<nobr><b>Comando<br>sistema ABS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:372px;font-weight:normal;font-size:5.72pt;\">");
write("<nobr><b>Aziona<br>l'elettrovalvola<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634px;top:372px;font-weight:normal;font-size:5.72pt;\">");
write("<nobr><b>Comando<br>sistema ABS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465px;top:274px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ANTERIORE DESTRO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:351px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ANTERIORE SINISTRO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:142px;font-weight:normal;font-size:4.59pt;\">");
write("<nobr><b>Rileva la<br>velocità di <br>rotazione della ruota<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:142px;font-weight:normal;font-size:4.50pt;\">");
write("<nobr><b>Rileva la<br>percentuale di <br>slittamento<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457px;top:122px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>POSTERIORE DESTRO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:196px;font-weight:normal;font-size:5.86pt;\">");
write("<nobr><b>POSTERIORE SINISTRO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:218px;font-weight:normal;font-size:4.50pt;\">");
write("<nobr><b>Rileva la<br>percentuale di <br>slittamento<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:295px;font-weight:normal;font-size:4.50pt;\">");
write("<nobr><b>Rileva la<br>percentuale di <br>slittamento<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:372px;font-weight:normal;font-size:4.50pt;\">");
write("<nobr><b>Rileva la<br>percentuale di <br>slittamento<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:218px;font-weight:normal;font-size:4.59pt;\">");
write("<nobr><b>Rileva la<br>velocità di <br>rotazione della ruota<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:372px;font-weight:normal;font-size:4.59pt;\">");
write("<nobr><b>Rileva la<br>velocità di <br>rotazione della ruota<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:295px;font-weight:normal;font-size:4.59pt;\">");
write("<nobr><b>Rileva la<br>velocità di <br>rotazione della ruota<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}