with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:433px;\" coordsize=\"475,433\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:433px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E20A18316217201KBID04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:433px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:7px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Alesaggio testa di biella <br>maggiorato<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:107px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Cuscinetto minorato (più spesso)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:65px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>1 o I<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:65px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>2 o II<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:64px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>3 o III<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:64px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>4 o IIII<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:203px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Giallo<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:148px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Rosa<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:10px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Codice alesaggio<br>testa<br>di biella<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:141px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Rosso/<br>Rosa<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:365px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Perno di<br>biella<br>minorato<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:149px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:98px;top:204px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:258px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:98px;top:312px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119px;top:365px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Cuscinetto<br>minorato<br>(più spesso)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:77px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Codice<br>perno di<br>biella<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:195px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Rosa/<br>Giallo<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:250px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Giallo/<br>Verde<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:304px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Verde/<br>Marrone<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:305px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Marrone/<br>Nero<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:309px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Verde<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:311px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Marrone<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:255px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Verde<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:250px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Verde/<br>Marrone<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:256px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Giallo<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:203px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Rosa<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:196px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Giallo/<br>Verde<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:141px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Rosa/<br>Giallo<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:147px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Rosso<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}