with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1023px;\" coordsize=\"950,1023\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1023px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E40A18300000000DAID01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1023px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583px;top:18px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PIASTRA DI PROTEZIONE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:117px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BLOCCO INFERIORE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:286px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PARAOLIO ALBERO MOTORE,<br>LATO CAMBIO<br><a href=\"javascript:CtsProc('0','000000000001094','i210')\"></b>Installazione,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:721px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RONDELLE REGGISPINTA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:917px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ALBERO MOTORE<br><a href=\"javascript:CtsProc('0','000000000001090','i000')\"></b>Gioco assiale,</a><br><a href=\"javascript:CtsProc('0','000000000001095','iT02')\">Eccentricità,</a><br><a href=\"javascript:CtsProc('0','000000000001095','iT01')\">Ovalizzazione,</a><br><a href=\"javascript:CtsProc('0','000000000001093','i000')\">Rimozione,</a><br><a href=\"javascript:CtsProc('0','000000000001094','i000')\">Installazione,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:923px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CUSCINETTI DI BANCO<br><a href=\"javascript:CtsProc('0','000000000001096','iR01')\"></b>Gioco olio,</a><br><a href=\"javascript:CtsProc('0','000000000001096','iR02')\">Selezione,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:25px;top:689px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PIASTRA IMPULSI CKP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162px;top:436px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SPINE DI CENTRAGGIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:57px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SENSORE POSIZIONE<br>ALBERO MOTORE (CKP)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}