with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7ETPJ32300000000EAID01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:466px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:466px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:94px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>G3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:94px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>E17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:559px;top:83px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>SCATOLA FUSIBILI−RELÈ SOTTO PLANCIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:811px;top:134px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>E38<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:134px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>K5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:178px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108px;top:349px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:760px;top:49px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>*2 : Senza tendina parasole tetto<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:760px;top:35px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>*1 : Con tendina parasole tetto<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:235px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:475px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96px;top:454px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96px;top:260px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:508px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:576px;top:508px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:576px;top:811px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:572px;top:1069px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:326px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:338px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:697px;top:369px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:708px;top:292px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>(2W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:697px;top:260px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:235px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:235px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:260px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:599px;top:292px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>(2W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:369px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:565px;top:338px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597px;top:326px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405px;top:940px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405px;top:900px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:355px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>PORTIERA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256px;top:343px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:343px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:203px;top:343px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:446px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:374px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:868px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:988px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:1069px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>G652<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:812px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405px;top:775px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>E36<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:695px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>E16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:796px;top:509px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:811px;top:346px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:811px;top:260px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:822px;top:315px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>(5W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:793px;top:178px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:188px;top:643px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:626px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>SCATOLA FUSIBILI−RELÈ SOTTO PLANCIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:812px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:775px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>E37<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302px;top:775px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>E3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284px;top:812px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:259px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>LUCE DI LETTURA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:626px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>K4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:454px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:209px;top:509px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:437px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>PORTIERA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:178px;top:437px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:578px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:178px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:178px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:149px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:260px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:260px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256px;top:304px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>(5W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:468px;top:292px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>(8W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:509px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:374px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:422px;top:326px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:466px;top:326px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:304px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>(5W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:103px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:102px;top:71px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>SCATOLA FUSIBILI/RELÈ VANO MOTORE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187px;top:91px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>N.17 (7,5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:102px;top:91px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>N.1 (BAT) (100A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:84px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>BATTERIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:468px;top:375px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>PLAFONIERA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:907px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>INTERRUTTORE<br>PORTIERA LATO <br>PASSEGGERO<br>(Chiuso: <br>Portiera aperta)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:211px;top:907px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>INTERRUTTORE<br>PORTIERA<br>LATO CONDUCENTE<br>(Chiuso: <br>Portiera aperta)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828px;top:347px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>LUCI<br>VANO DI<br>CARICO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417px;top:907px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>INTERRUTTORE<br>DISPOSITIVO DI CHIUSURA<br>PORTELLONE <br>(Chiuso: <br>portellone aperto)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:599px;top:370px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>LUCE<br>SPECCHIETTO<br>DI CORTESIA<br>LATO CONDUCENTE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:708px;top:370px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>LUCE<br>SPECCHIETTO<br>DI CORTESIA<br>LATO PASSEGGERO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60px;top:161px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>FUSIBILE N.14 (7,5A)<br>(SCATOLA FUSIBILI/RELÈ<br>SOTTO PLANCIA)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:33px;top:251px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>LUCI<br>ABITACOLO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:530px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>REGOLATORE<br>LUMINOSITÀ<br>LUCI PLANCIA<br>(Nel modulo di comando<br>quadro strumenti)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}