with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E40E34150100000LCID02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:314px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601px;top:38px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601px;top:73px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:600px;top:96px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:120px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:600px;top:148px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319px;top:57px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:143px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:208px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:253px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:762px;top:417px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:735px;top:404px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206px;top:285px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(13)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170px;top:379px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(14)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:712px;top:391px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812px;top:533px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:794px;top:432px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(17)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:762px;top:542px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(18)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:509px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(19)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:616px;top:515px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(20)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:667px;top:339px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(21)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:351px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(22)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:351px;top:507px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(23)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:522px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(24)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:624px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(25)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:537px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(26)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:482px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(27)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:542px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(28)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276px;top:633px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(29)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:584px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(30)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:690px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(31)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:668px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(32)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:645px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(33)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:237px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(34)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644px;top:558px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(36)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:492px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(38)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:232px;top:530px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(37)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:54px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(40)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:480px;top:88px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(41)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:215px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(42)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:103px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(43)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:735px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:751px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:783px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:799px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:831px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:847px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:863px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:895px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:911px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:927px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:943px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:975px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:991px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(13)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:1007px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(14)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:1023px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:1039px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:1071px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(17)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:735px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(18)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:767px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(19)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:799px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(20)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:831px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(21)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:863px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(22)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:895px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(23)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:927px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(24)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:959px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(25)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:991px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(26)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:1007px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(27)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:1023px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(28)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:1055px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(29)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:1071px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(30)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:735px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(31)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:751px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(32)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:767px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(33)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:783px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(34)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:799px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(35)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:815px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(36)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:847px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(37)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:879px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(38)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:911px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(39)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:943px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(40)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:975px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(41)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:991px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(42)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:1023px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(43)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:735px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SCATOLA TRASMISSIONE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:751px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BULLONE FLANGIATO 6 mm<br>12 N·m (1,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:783px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>COPERCHIO ELEMENTO FILTRANTE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:799px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>O-RING<br></b>Sostituire.<br></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:831px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MOLLA DI TARATURA ELEMENTO FILTRANTE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:847px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FILTRO POMPA OLIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:863px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BULLONE FLANGIATO 6 mm<br>12 N·m (1,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:895px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ELETTROVALVOLA BLOCCO RETROMARCIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:911px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PERNO DI ARRESTO SELEZIONE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:927px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MOLLA BLOCCO SELEZIONE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:943px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>VITE  DI FERMO<br>22 N·m (2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:975px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MOLLA (3), 27,4 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:1023px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SFERA DI ACCIAIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:1039px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BULLONE FLANGIATO 6 mm<br>12 N·m (1,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:1071px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>COLLARE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:735px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SENSORE VELOCITÀ DI ROTAZIONE<br>ALBERO DI USCITA (CONTRALBERO)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:767px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>O-RING<br></b>Sostituire.<br></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:799px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INTERRUTTORE LUCI DI RETROMARCIA<br>29 N·m (3,0 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:831px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RONDELLA, 6 mm<br></b>Sostituire.<br></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:863px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BULLONE CONTROLLO OLIO,<br>12 N·m (1,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:895px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RONDELLA 20 mm<br></b>Sostituire.<br></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:927px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TAPPO DI RIEMPIMENTO<br>44 N·m (4,5 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:959px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BULLONE SPECIALE, 8 mm<br>29 N·m (3,0 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:991px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RONDELLA ELASTICA 8 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:1007px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BRACCETTO CAMBIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:1023px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PARAPOLVERE<br></b>Sostituire.<br></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:1055px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>LEVA CAMBIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:1071px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SPESSORE, 82 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:735px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PISTA ESTERNA CUSCINETTO, 45 x 81 x 18 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:751px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DISTANZIALE, 46 x 81 x 1 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:767px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SPESSORE, 81 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:783px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SUPPORTO B TRASMISSIONE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:815px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BULLONE FLANGIATO, 10 x 42 mm<br>44 N·m (4,5 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:847px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BULLONE FLANGIATO, 10 x 20 mm<br>44 N·m (4,5 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:879px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BULLONE FLANGIATO, 10 x 90 mm<br>44 N·m (4,5 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:911px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BULLONE FLANGIATO 8 mm<br> 27 N·m (2,8 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:943px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BULLONE FLANGIATO 6 mm<br>12 N·m (1,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:975px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TAPPO SCATOLA CAMBIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:991px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>O-RING<br></b>Sostituire.<br></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:1023px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PARAOLIO 40 x 56 x 9 mm<br></b>Sostituire.<br></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:991px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MOLLA (2), 22,0 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:1007px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MOLLA (1), 26,1 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:799px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>STAFFA CABLAGGIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:559px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:547px;top:533px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296px;top:426px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311px;top:295px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:292px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:164px;top:279px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224px;top:354px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201px;top:365px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:405px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:624px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(35)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:572px;top:546px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:164px;top:538px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(39)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182px;top:170px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(36)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}