with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:719px;\" coordsize=\"950,719\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:719px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7EA0D14300014711LAID02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:719px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96px;top:28px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>: Grasso per gomma<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:61px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>: Grasso al silicone<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:15px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>BULLONE FORATO,<br>34 N·m (3,5 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624px;top:120px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>VITE DI SPURGO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:172px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>CORPO PINZA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:374px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>CUFFIA PISTONE<br></b>Sostituire.<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:59px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>RONDELLE<br>DI TENUTA<br></b>Sostituire.<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:321px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>GUARNIZIONE PISTONE<br></b>Sostituire.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798px;top:260px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>GRUPPO PISTONE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:243px;top:149px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>TUBO FLESSIBILE FRENI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:658px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>CUFFIA PERNO<br></b>Sostituire.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:611px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>10 x 1,25 mm<br>55 N·m<br>(5,6 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702px;top:488px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>PASTIGLIE FRENI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:355px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>STAFFA PINZA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96px;top:484px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>PERNI PINZA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90px;top:606px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>PERNO PINZA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:428px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>FERMI<br>PASTIGLIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514px;top:638px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>SPESSORE ADESIVO<br></b>Sostituire.<br></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:787px;top:614px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>SPESSORE ADESIVO<br></b>Sostituire.<br></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:239px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>35 N·m <br>(3,6 kgf·m)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}