with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:927px;\" coordsize=\"950,927\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:927px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E80A14666300000MFID01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:927px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:779px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ALBERO OSCILLANTE<br>SCARICO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:779px;top:89px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GRUPPO BILANCIERI<br>SCARICO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:11px;top:590px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SUPPORTO N.1<br>ALBERO A CAMME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58px;top:729px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ELASTICO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302px;top:763px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SUPPORTO<br>N.2<br>ALBERO A CAMME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:451px;top:763px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SUPPORTO<br>N.3<br>ALBERO A CAMME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601px;top:762px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SUPPORTO<br>N.4<br>ALBERO A CAMME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761px;top:780px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GRUPPO BILANCIERI<br>ASPIRAZIONE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:803px;top:595px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SUPPORTO N.5<br>ALBERO A CAMME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:897px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ALBERO OSCILLANTE ASPIRAZIONE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:51px;top:131px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ELASTICO<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}