with(document) {
write("<v:group id=\"group5\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:815px;\" coordsize=\"950,815\">");
write("<v:rect id=\"rect5\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:815px;\">");
write("<img id=\"img5\" name=\"PrtImgId\" src=\"../img/SMR7ETQA20300000000DBID05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:815px;border-color:#ffffff\">");
write("<p id=\"p5_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:110px;top:181px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:85px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p5_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:74px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p5_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:60px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p5_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:47px;top:253px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:752px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p5_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:745px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p5_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185px;top:718px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p5_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:734px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p5_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118px;top:687px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p5_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665px;top:594px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p5_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:619px;top:627px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p5_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:758px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p5_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:576px;top:650px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p5_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:758px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p5_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:630px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p5_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815px;top:596px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p5_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539px;top:54px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p5_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:59px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p5_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:67px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p5_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737px;top:96px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p5_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:27px;top:435px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CABLAGGIO<br>SECONDARIO DEVIOLUCI<br></b></nobr>");
write("</p>");
write("<p id=\"p5_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CABLAGGIO <br>PLANCIA<br></b></nobr>");
write("</p>");
write("<p id=\"p5_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:30px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CABLAGGIO<br>VANO<br>MOTORE<br></b></nobr>");
write("</p>");
write("<p id=\"p5_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:753px;top:369px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CABLAGGIO PIANALE<br></b></nobr>");
write("</p>");
write("<p id=\"p5_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:463px;top:778px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SCATOLA DI GIUNZIONE<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}