with(document) {
write("<v:group id=\"group6\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1039px;\" coordsize=\"950,1039\">");
write("<v:rect id=\"rect6\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1039px;\">");
write("<img id=\"img6\" name=\"PrtImgId\" src=\"../img/SMR7ETQA20300000000DBID06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1039px;border-color:#ffffff\">");
write("<p id=\"p6_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:449px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>INTERRUTTORE<br>POSIZIONE<br>PEDALE FRENO (14)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:156px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>MODULO DI COMANDO QUADRO<br>STRUMENTI (CONTAGIRI) (5)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533px;top:461px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>INTERRUTTORE B<br>POSIZIONE<br>PEDALE FRIZIONE (15)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624px;top:17px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SCATOLA FUSIBILI/RELÈ SOTTO<br>PLANCIA R (4)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174px;top:11px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>RELÈ 2<br>MOTORINO <br>DI AVVIAMENTO (2)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:17px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SCATOLA FUSIBILI/RELÈ<br>SOTTO PLANCIA Q (3)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:157px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONNETTORE 24P (6)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:474px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SENSORE APP (13)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:467px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>COMMUTATORE <br>DI ACCENSIONE<br>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:696px;top:305px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONNETTORE<br>TRASMISSIONE DATI (11)*<br></b></nobr>");
write("</p>");
write("<p id=\"p6_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:617px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SCATOLA FUSIBILI/RELÈ SOTTO PLANCIA G (19)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:626px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SCATOLA<br>FUSIBILI/RELÈ<br>SOTTO PLANCIA C (18)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:461px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SCATOLA FUSIBILI<br>/RELÈ SOTTO PLANCIA<br>D (17)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117px;top:781px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SCATOLA FUSIBILI/RELÈ SOTTO PLANCIA F (20)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:25px;top:17px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>RELÈ DI<br>INIBIZIONE<br>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:156px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONNETTORE 14P (7)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:311px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONNETTORE 12P (8)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339px;top:312px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONNETTORE 14P (9)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531px;top:299px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SENSORE 2 EGT<br>(con impianto DPF)<br>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:462px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>INTERRUTTORE A<br>POSIZIONE <br>PEDALE FRIZIONE<br>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722px;top:781px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SCATOLA<br>FUSIBILI/RELÈ<br>SOTTO PLANCIA K (21)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1px;top:979px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>NOTA:<br>· Connettore con terminali maschio (cornice doppia): visto dal lato terminale<br>·Connettore con terminali femmina (cornice singola): visto dal lato cablaggio<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}