with(document) {
write("<v:group id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:559px;\" coordsize=\"950,559\">");
write("<v:rect id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:559px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/SMR7E00J54400000000DAID03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:559px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:788px;top:229px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>GUARNIZIONE DI GOMMA C, 2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:582px;top:17px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DISPOSITIVO DI FISSAGGIO, 2<br>(Tipo autoadesivo, lato cristallo)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:372px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>LUNOTTO<br><a href=\"javascript:CtsProc('0','000000000000362','i000')\"></b>Sostituzione,</a><br></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:61px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DISPOSITIVO DI FISSAGGIO, 2<br>(Autoadesivo, lato carrozzeria)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:18px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>FERMAGLIO<br>(Autoadesivo, lato cristallo)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:72px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>GUARNIZIONE SUPERIORE<br>LUNOTTO<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:781px;top:324px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>GUARNIZIONE DI GOMMA B, 2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643px;top:448px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>GUARNIZIONE DI GOMMA A<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:623px;top:513px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DISPOSITIVO DI FISSAGGIO, 2<br>(Autoadesivo, lato cristallo)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:379px;top:513px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DISPOSITIVO DI FISSAGGIO, 2<br>(Autoadesivo, lato carrozzeria)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:768px;top:381px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>ADESIVO i-VTEC<br><a href=\"javascript:CtsProc('0','000000000002058','i000')\"></b>Sostituzione,<br></a><br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}