with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:554px;\" coordsize=\"950,554\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:554px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7ETAJ22100000000EAID90.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:554px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:866px;top:28px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>: Linea CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778px;top:155px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>MODULO DI COMANDO QUADRO STRUMENTI (CONTAGIRI)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:667px;top:268px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CIRCUITO DI <br>COMANDO <br>DISPLAY LCD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:896px;top:345px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:896px;top:184px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:896px;top:202px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:554px;top:498px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526px;top:498px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804px;top:498px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:498px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:498px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614px;top:498px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:430px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:699px;top:430px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:291px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CIRCUITO PRINCIPALE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:364px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:704px;top:402px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615px;top:402px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562px;top:364px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:866px;top:364px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:858px;top:387px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:364px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:460px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:407px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:797px;top:387px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:880px;top:262px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798px;top:262px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730px;top:262px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:210px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>5V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:252px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CIRCUITO<br>DI COMANDO<br>5 V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:616px;top:239px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>ON/OFF <br>5 V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:669px;top:242px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>DISPLAY<br>MULTIFUNZIONE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566px;top:250px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>SPIA<br>IMMOBILIZZATORE<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:210px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CIRCUITO DI REGOLAZIONE E<br>COMMUTAZIONE<br>ILLUMINAZIONE LANCETTE <br>(COLORE BIANCO)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:760px;top:210px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CIRCUITO DI REGOLAZIONE E<br>COMMUTAZIONE<br>ILLUMINAZIONE INDICATORI <br>(COLORE BIANCO)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838px;top:210px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CIRCUITO DI REGOLAZIONE E<br>COMMUTAZIONE<br>ILLUMINAZIONE DISPLAY LCD <br>(COLORE BIANCO)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:810px;top:418px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>TRASMETTITORE<br>INDICATORE<br>LIVELLO<br>CARBURANTE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:840px;top:446px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>GRUPPO<br>SERBATOIO<br>CARBURANTE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773px;top:317px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>PULSANTE DI<br>COMMUTAZIONE<br>km/h, mph<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:712px;top:317px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>REGOLATORE<br>LUMINOSITÀ<br>LUCI PLANCIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:680px;top:320px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>ILLUMI <br>(−)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:320px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>ILLUMI <br>(+)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:370px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RELÈ AVVISATORE ACUSTICO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665px;top:365px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>FUSIBILE N.14 (7,5A)<br>(SCATOLA FUSIBILI/RELÈ SOTTO PLANCIA) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:626px;top:467px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>INTERRUTTORE <br>INFORMAZIONI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:668px;top:462px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>INTERRUTTORE<br>DI SELEZIONE/<br>AZZERAMENTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:405px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>ARROTOLATORE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:502px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>ARROTOLATORE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823px;top:507px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>REGOLATORE<br>LUMINOSITÀ<br>LUCI PLANCIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566px;top:463px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>INTERRUTTORE<br>DI SELEZIONE/<br>AZZERAMENTO/<br>INFORMAZIONI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:110px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>Q9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:110px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>P10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:110px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>Q1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:110px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>P5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:64px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>D2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:64px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:46px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>E15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:28px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:480px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>TCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:480px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175px;top:496px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:262px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:20px;top:150px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>MODULO DI COMANDO QUADRO <br>STRUMENTI (CONTAGIRI)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175px;top:479px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:468px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175px;top:455px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:221px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:457px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:451px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CENTRALINA SRS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:451px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:434px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:428px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:428px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:291px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CIRCUITO PRINCIPALE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:449px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175px;top:449px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175px;top:425px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:257px;top:387px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:364px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:364px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:387px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:339px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>2,6 kΩ<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:123px;top:296px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:296px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:175px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:193px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:210px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:168px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>SEGNALE ACUSTICO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222px;top:119px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:257px;top:119px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:149px;top:119px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185px;top:119px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154px;top:134px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:134px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:125px;top:387px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133px;top:364px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:364px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:387px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:26px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>N.2 (IG) (50A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:157px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:157px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:237px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CONTAGIRI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:52px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:40px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:28px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237px;top:34px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:34px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120px;top:45px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>N.16 (15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:14px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>SCATOLA FUSIBILI/RELÈ VANO MOTORE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:38px;top:21px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BATTERIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:190px;top:14px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>COMMUTATORE DI ACCENSIONE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:26px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>N.1 (BAT) (100A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:87px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(7,5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:81px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>N.10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298px;top:82px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>SCATOLA<br>FUSIBILI/RELÈ<br>SOTTO PLANCIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206px;top:147px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>MODULO DI COMANDO<br>QUADRO STRUMENTI <br>(TACHIMETRO)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:148px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>MODULO DI COMANDO<br>QUADRO STRUMENTI <br>(TACHIMETRO)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157px;top:236px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CIRCUITO<br>DI AZIONAMENTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276px;top:257px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CIRCUITO<br>COMMUTATORE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:175px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>SEGNALATORE<br>FRENO DI<br>STAZIONAMENTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:192px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>SEGNALATORE<br>CINTURA DI<br>SICUREZZA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:210px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>SEGNALATORE CHIAVE<br>INSERITA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:318px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RICETRASMETTITORE<br>F−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:318px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RICETRASMETTITORE<br>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:425px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CENTRALINA<br>IMMOBILIZZATORE−<br>SISTEMA DI ACCESSO<br>CON TELECOMANDO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:425px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>MODULO<br>DI COMANDO<br>QUADRO STRUMENTI<br>(TACHIMETRO)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:258px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CIRCUITO STABILIZZATORE<br>10V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298px;top:232px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>SPIA<br>ABBAGLIANTI<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:434px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>MODULATORE−<br>CENTRALINA<br>VSA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:457px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CONNETTORE<br>TRASMISSIONE DATI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:221px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>SEGNALATORE<br>LUCI ACCESE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:455px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CENTRALINA<br>RISCALDAMENTO/<br>CENTRALINA<br>CLIMATIZZATORE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:215px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CIRCUITO<br>DI REGOLAZIONE E<br>COMMUTAZIONE<br>ILLUMINAZIONE <br>DISPLAY LCD <br>(COLORE AMBRA)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:232px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>SPIA<br>ANTIFURTO<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:257px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CIRCUITO LAMPEGGIO<br>SPIA ANTIFURTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:468px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CENTRALINA<br>EPS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:479px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>SENSORE<br>ILLUMINAZIONE<br>AUTOMATICA/PIOGGIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:234px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>INDICATORE<br>LIVELLO <br>CARBURANTE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:51px;top:240px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>INDICATORE<br>TEMPERATURA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:496px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CENTRALINA<br>VIVAVOCE<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}