with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:554px;\" coordsize=\"950,554\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:554px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7ETPJ32133100000EAID91.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:554px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765px;top:313px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731px;top:419px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731px;top:394px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:866px;top:257px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:926px;top:133px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:126px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>D2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:891px;top:21px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>: Linea CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:827px;top:158px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>R16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820px;top:268px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:844px;top:257px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687px;top:286px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:14px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>* : Con sensore illuminazione automatica/pioggia<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:827px;top:198px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>Q6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:844px;top:203px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:884px;top:183px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:844px;top:164px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604px;top:153px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(7,5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604px;top:147px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>N.1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544px;top:75px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:43px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732px;top:535px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G603: Versione con guida a sinistra<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732px;top:541px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G651: Versione con guida a destra<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:535px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G651: Versione con guida a destra<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:770px;top:285px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:777px;top:294px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:294px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720px;top:294px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:912px;top:464px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:910px;top:528px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804px;top:203px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>B-CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:867px;top:158px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:902px;top:144px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:902px;top:183px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:895px;top:221px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:920px;top:183px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:756px;top:319px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>AUTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:775px;top:325px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:785px;top:325px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:752px;top:310px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743px;top:310px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714px;top:326px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800px;top:169px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746px;top:126px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>SCATOLA FUSIBILI−RELÈ SOTTO PLANCIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720px;top:248px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>S1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:712px;top:257px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694px;top:464px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:464px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773px;top:492px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:492px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:655px;top:492px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:616px;top:492px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:576px;top:492px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:772px;top:385px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:733px;top:385px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694px;top:385px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654px;top:385px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798px;top:248px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>S5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:777px;top:248px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>S11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:248px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>S13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:695px;top:248px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>S12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:248px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>S16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790px;top:257px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:770px;top:257px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737px;top:257px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687px;top:257px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:257px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:771px;top:528px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G652<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:623px;top:305px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>E19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615px;top:325px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:305px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>F3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:576px;top:325px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:528px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615px;top:385px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:528px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:492px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614px;top:528px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G603<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:530px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G603: Versione con guida a sinistra<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:394px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:419px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:394px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:419px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:613px;top:394px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:613px;top:419px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653px;top:394px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653px;top:419px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:692px;top:394px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:692px;top:419px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:771px;top:394px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:771px;top:419px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:325px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:305px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:154px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>N.19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:160px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:547px;top:265px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>N.15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:547px;top:271px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(7,5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798px;top:294px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:695px;top:294px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:294px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:308px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658px;top:326px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>HI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:651px;top:342px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>COMMUTATORE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688px;top:330px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LAMPEGGIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:733px;top:358px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>DEVIOSGANCIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:419px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LUCE<br>DI POSIZIONE<br>ANTERIORE<br>SINISTRA<br>(5W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:419px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LUCE<br>DI POSIZIONE<br>ANTERIORE<br>DESTRA<br>(5W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:623px;top:419px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LUCE <br>DI POSIZIONE<br>POSTERIORE <br>SINISTRA <br>(5W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:663px;top:419px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LUCE <br>DI POSIZIONE<br>POSTERIORE <br>SINISTRA <br>(5W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:700px;top:420px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LUCE<br>DI POSIZIONE<br>POSTERIORE <br>LATO SINISTRO<br>(PORTELLONE)<br>(5W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:781px;top:419px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LUCI<br>TARGA<br>(5 Wx2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:880px;top:155px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>SENSORE<br>ILLUMINAZIONE<br>AUTOMATICA/<br>PIOGGIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:420px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LUCE<br>DI POSIZIONE<br>POSTERIORE<br>LATO DESTRO <br>(PORTELLONE)<br>(5W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:217px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CENTRALINA REGOLATORE<br>ASSETTO FARI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:155px;top:105px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>E15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:87px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:69px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>E17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:37px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:126px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:380px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>ABBAGLIANTI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:386px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(55W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:528px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:528px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:341px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:423px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:341px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:423px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:423px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:423px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:386px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(55W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:380px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>ABBAGLIANTI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:341px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:341px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324px;top:528px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:528px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:443px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:443px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:443px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:443px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:347px;top:408px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LO (35W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:338px;top:369px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CENTRALINA <br>HID<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:205px;top:368px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CENTRALINA <br>HID<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:408px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LO (35W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:352px;top:75px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:356px;top:43px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:43px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:49px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:36px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:23px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>COMMUTATORE DI ACCENSIONE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:85px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>N.2 (H/L) (60A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:190px;top:67px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>N.17 (7,5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90px;top:542px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G652: Versione con guida a destra<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:443px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:528px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:248px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>T34<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:155px;top:126px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:443px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:443px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:118px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:160px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(20A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:154px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>N.18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:219px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>SG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:305px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>E6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90px;top:537px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G602: Versione con guida a sinistra<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156px;top:528px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G651<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:166px;top:305px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>E33<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:305px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>F20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:219px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>PG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:443px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:528px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:181px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>+B BACK UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:169px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:154px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>N.21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:160px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(30A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147px;top:118px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187px;top:35px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>N.2 (IG) (50A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157px;top:78px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157px;top:72px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>N.16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:305px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>F22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:305px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>F4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:305px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:305px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:347px;top:325px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:325px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357px;top:279px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>N.16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357px;top:285px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:325px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:285px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:279px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>N.17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:38px;top:125px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>SCATOLA FUSIBILI−RELÈ SOTTO PLANCIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:77px;top:23px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>SCATOLA FUSIBILI/RELÈ VANO MOTORE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:325px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:285px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(10A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:279px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>N.12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:279px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>N.13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:285px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(10A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:35px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>N.1 (BAT) (100A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:53px;top:30px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BATTERIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:334px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>FARO<br>SINISTRO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:334px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>FARO<br>DESTRO<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}