with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:671px;\" coordsize=\"950,671\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:671px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E00D00060845111KBID01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:671px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:15px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>8 x 1,25 mm<br>22 N·m <br>(2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:226px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>8 x 1,25 mm<br>22 N·m <br>(2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715px;top:434px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>8 x 1,25 mm<br>22 N·m <br>(2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:188px;top:279px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DADO DI REGOLAZIONE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:13px;top:507px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>LEVA FRENO DI STAZIONAMENTO<br></b>Controllare che il funzionamento<br>sia regolare.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:490px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>CAVO FRENO DI STAZIONAMENTO<br></b>Controllare se presenta irrigidimenti,<br>inceppamenti o danni.<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457px;top:454px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>BILANCIERE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:536px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>1,4 N·m <br>(0,14 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367px;top:580px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>INTERRUTTORE FRENO DI STAZIONAMENTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:179px;top:591px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>(MULTIUSO)<br>Superficie di scorrimento<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1px;top:639px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b></b>La figura mostra la versione con guida a sinistra. La versione con guida a destra è simile.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}