with(document) {
write("<v:group id=\"group10\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:904px;\" coordsize=\"950,904\">");
write("<v:rect id=\"rect10\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:904px;\">");
write("<img id=\"img10\" name=\"PrtImgId\" src=\"../img/SMR8EN0J54230100000EAID10.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:904px;border-color:#ffffff\">");
write("<p id=\"p10_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:421px;top:442px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:448px;top:442px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p10_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:228px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p10_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:228px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:114px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:114px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p10_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:357px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Sensore ad ultrasuoni<br></b></nobr>");
write("</p>");
write("<p id=\"p10_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:828px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p10_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:849px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p10_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:828px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p10_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:114px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p10_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:78px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p10_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:43px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p10_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:264px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p10_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:300px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p10_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:442px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p10_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:407px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Relè superbloccaggio lato passeggero<br></b></nobr>");
write("</p>");
write("<p id=\"p10_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:43px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruttore principale alzacristalli elettrici<br></b></nobr>");
write("</p>");
write("<p id=\"p10_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:828px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Cablaggio tetto<br></b></nobr>");
write("</p>");
write("<p id=\"p10_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:827px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p10_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152px;top:848px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p10_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:849px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Cablaggio EPS<br></b></nobr>");
write("</p>");
write("<p id=\"p10_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:828px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Cablaggio portiera lato conducente<br></b></nobr>");
write("</p>");
write("<p id=\"p10_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566px;top:827px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p10_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:514px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:514px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p10_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:478px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p10_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:478px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Luce vano portaoggetti<br></b></nobr>");
write("</p>");
write("<p id=\"p10_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:442px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Sensore di coppia<br></b></nobr>");
write("</p>");
write("<p id=\"p10_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:478px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:442px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:410px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SCATOLA DI GIUNZIONE<br></b></nobr>");
write("</p>");
write("<p id=\"p10_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:342px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Luce specchietto di cortesia lato passeggero<br></b></nobr>");
write("</p>");
write("<p id=\"p10_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:328px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Luce specchietto di cortesia lato conducente<br></b></nobr>");
write("</p>");
write("<p id=\"p10_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:314px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Plafoniera<br></b></nobr>");
write("</p>");
write("<p id=\"p10_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:300px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Sensore illuminazione automatica/pioggia<br></b></nobr>");
write("</p>");
write("<p id=\"p10_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:264px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Motorino tendina parasole<br></b></nobr>");
write("</p>");
write("<p id=\"p10_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:264px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:300px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:228px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Centralina vivavoce<br></b></nobr>");
write("</p>");
write("<p id=\"p10_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:200px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Motorino alzacristalli elettrico lato conducente<br></b></nobr>");
write("</p>");
write("<p id=\"p10_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:185px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Attuatore serratura portiera lato conducente<br></b></nobr>");
write("</p>");
write("<p id=\"p10_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:171px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Indicatore di direzione laterale destro<br></b></nobr>");
write("</p>");
write("<p id=\"p10_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:157px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Sbrinatore specchietto elettrico destro<br></b></nobr>");
write("</p>");
write("<p id=\"p10_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:143px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Luce interruttore specchietti elettrici<br></b></nobr>");
write("</p>");
write("<p id=\"p10_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:128px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruttore specchietti elettrici<br></b></nobr>");
write("</p>");
write("<p id=\"p10_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:114px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruttore principale alzacristalli elettrici<br></b></nobr>");
write("</p>");
write("<p id=\"p10_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:592px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Unità audio<br></b></nobr>");
write("</p>");
write("<p id=\"p10_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:114px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:78px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:43px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:78px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:78px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p10_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:664px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G504<br></b></nobr>");
write("</p>");
write("<p id=\"p10_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:592px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p10_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:592px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:78px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Attuatore superbloccaggio lato conducente<br></b></nobr>");
write("</p>");
write("<p id=\"p10_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:514px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Navigatore<br></b></nobr>");
write("</p>");
write("<p id=\"p10_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:442px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p10_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:442px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:392px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p10_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:392px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:392px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Relè superbloccaggio lato conducente<br></b></nobr>");
write("</p>");
write("<p id=\"p10_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:300px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p10_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:300px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:264px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:264px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p10_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:114px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p10_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:114px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:521px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p10_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:43px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:43px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p10_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152px;top:827px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p10_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:828px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Cablaggio plancia<br></b></nobr>");
write("</p>");
write("<p id=\"p10_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:828px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}