with(document) {
write("<v:group id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/SMR8EL0J54260462001EAID03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:306px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:542px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Relè presa di corrente per accessori anteriore<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:245px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:192px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:599px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:557px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Relè presa di corrente posteriore accessori<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:542px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:499px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Navigatore<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:485px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Joystick<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:555px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N. 34 (non utilizzato)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:428px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:457px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:445px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Presa scatola fusibili/relè)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:335px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:227px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N.23 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:771px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:870px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N.22 (non utilizzato)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:128px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:86px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:386px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:239px;top:441px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N. 35 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:242px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:242px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:214px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:214px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Elettrovalvola motorino di avviamento <br>(tramite relè esclusione motorino di avviamento 2)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:471px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:471px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Unità audio<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:514px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Display navigatore<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:528px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Centralina vivavoce<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:335px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Relè di inibizione<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:529px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:842px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:807px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:791px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N.29 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:755px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N.28 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:720px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N. 27 (non utilizzato)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:699px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:243px;top:684px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N.7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:614px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Riscaldatore sedile lato passeggero<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:571px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:600px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Riscaldatore sedile lato conducente<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:243px;top:584px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N.5 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:842px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Centralina lavafari<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:827px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N. 31 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:628px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Relè fendinebbia<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:628px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:45px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SCATOLA FUSIBILI−RELÈ SOTTO PLANCIA<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:243px;top:613px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N. 6 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:475px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>FUSIBILE <br>N.4 (OP) (80 A) <br>(SCATOLA FUSIBILI/RELÈ <br>VANO MOTORE)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:701px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Luce di posizione anteriore destra <br>(attraverso il relè luci di marcia diurna) (Modello KS)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:730px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Luce di posizione anteriore sinistra <br>(attraverso il relè luci di marcia diurna) (Modello KS)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:644px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Fendinebbia sinistro<br>(attraverso il relè fendinebbia)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:670px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Fendinebbia destro<br>(attraverso il relè fendinebbia)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:171px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>RELÈ ESCLUSIONE<br>MOTORINO DI AVVIAMENTO 1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:358px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>RELÈ<br>ESCLUSIONE ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:48px;top:33px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>FUSIBILE <br>N.2 (IG) (50 A) <br>(SCATOLA FUSIBILI/RELÈ <br>VANO MOTORE)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:773px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Presa di corrente per accessori posteriore<br>(Attraverso il relè presa di corrente per accessori posteriore)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:808px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Presa di corrente per accessori anteriore <br>(Attraverso il relè presa di corrente per accessori anteriore)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:858px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Motorino lavafari<br>(attraverso la centralina lavafari)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}