with(document) {
write("<v:group id=\"group6\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:591px;\" coordsize=\"950,591\">");
write("<v:rect id=\"rect6\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:591px;\">");
write("<img id=\"img6\" name=\"PrtImgId\" src=\"../img/SMR9ER3E34137300000CAID06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:591px;border-color:#ffffff\">");
write("<p id=\"p6_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:81px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>100 ‰<br></b></nobr>");
write("</p>");
write("<p id=\"p6_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:271px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p6_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:478px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>0<br></b></nobr>");
write("</p>");
write("<p id=\"p6_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1px;top:275px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Apertura<br>valvola a farfalla<br></b></nobr>");
write("</p>");
write("<p id=\"p6_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737px;top:521px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>: Modalità normale<br></b></nobr>");
write("</p>");
write("<p id=\"p6_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737px;top:553px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>: Modalità sportiva<br></b></nobr>");
write("</p>");
write("<p id=\"p6_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:63px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>2a<br></b></nobr>");
write("</p>");
write("<p id=\"p6_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:63px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>3a<br></b></nobr>");
write("</p>");
write("<p id=\"p6_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:543px;top:63px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>4a<br></b></nobr>");
write("</p>");
write("<p id=\"p6_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:64px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>5a<br></b></nobr>");
write("</p>");
write("<p id=\"p6_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837px;top:64px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>6a<br></b></nobr>");
write("</p>");
write("<p id=\"p6_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457px;top:481px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>62 mph (100 km/h)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:829px;top:482px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Velocità vettura<br></b></nobr>");
write("</p>");
write("<p id=\"p6_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:63px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>2a<br></b></nobr>");
write("</p>");
write("<p id=\"p6_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:63px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>3a<br></b></nobr>");
write("</p>");
write("<p id=\"p6_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:64px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>4a<br></b></nobr>");
write("</p>");
write("<p id=\"p6_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:768px;top:64px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>5a<br></b></nobr>");
write("</p>");
write("<p id=\"p6_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:63px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>1a<br></b></nobr>");
write("</p>");
write("<p id=\"p6_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:17px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>MODALITÀ AUTOMATICA: Schema di passaggio alla marcia inferiore<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}