with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:417px;\" coordsize=\"475,417\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:417px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9EQPK80100081930FAID01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:417px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:49px;top:17px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>CONNETTORE 46P MODULATORE-CENTRALINA SISTEMA VSA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:114px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>CAN-L (RED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:33px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b></b>Lato cablaggio dei terminali femmina<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:290px;top:115px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>CAN-H (WHT)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:55px;top:370px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>CONNETTORE 12P MODULO DI COMANDO CAMBIO MARCIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:386px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b></b>Lato cablaggio dei terminali femmina<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:232px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>CAN-H (WHT)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:232px;top:337px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>CAN-L (RED)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}