with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SMR9EQ6E34150300000KBID02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687px;top:148px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>POMELLO LEVA CAMBIO<br>8 N·m (0,8 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654px;top:360px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SCATOLA LEVA CAMBIO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:976px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Durante il montaggio, i contrassegni per<br>l'identificazione devono essere<br>nei punti indicati.<br></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:574px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>STAFFA SCATOLA LEVA CAMBIO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:53px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 x 1,25 mm<br>22 N·m<br>(2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:49px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>COPERTURA LEVA CAMBIO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:202px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 x 1,25 mm<br>22 N·m<br>(2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:748px;top:698px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 x 1,0 mm<br>9,8 N·m<br>(1,0 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:432px;top:1059px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>STAFFA CAVO CAMBIO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:178px;top:839px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(SILICONE)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:1024px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(SILICONE)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:593px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CAVI DI CAMBIO MARCIA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:243px;top:721px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FERMAGLI CAVO<br></b>Sostituire.<br></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:946px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SPINA DI BLOCCAGGIO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:826px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SPINA DI <br>BLOCCAGGIO<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}