with(document) {
write("<v:group id=\"group4\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:882px;\" coordsize=\"950,882\">");
write("<v:rect id=\"rect4\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:882px;\">");
write("<img id=\"img4\" name=\"PrtImgId\" src=\"../img/SMR9ERPJ54260462100EAID04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:882px;border-color:#ffffff\">");
write("<p id=\"p4_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:243px;top:35px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SCATOLA FUSIBILI/RELÈ VANO MOTORE<br></b></nobr>");
write("</p>");
write("<p id=\"p4_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:154px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:138px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N. 23 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:174px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:126px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p4_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201px;top:91px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p4_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:154px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MODULO ECM (FHTR MON)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:204px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:204px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MODULO ECM (F/HTR RLY)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:154px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372px;top:138px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N.25 (7,5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659px;top:204px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:254px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:254px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Riscaldatore carburante<br></b></nobr>");
write("</p>");
write("<p id=\"p4_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:404px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:354px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Riscaldatore PTC.<br></b></nobr>");
write("</p>");
write("<p id=\"p4_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550px;top:354px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:338px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N. 26 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201px;top:291px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p4_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:326px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p4_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:375px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:467px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N. 27 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:596px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N. 28 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:483px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Riscaldatore PTC.<br></b></nobr>");
write("</p>");
write("<p id=\"p4_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:482px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:533px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:661px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:611px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:611px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Riscaldatore PTC.<br></b></nobr>");
write("</p>");
write("<p id=\"p4_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:731px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N.13 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:797px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:747px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:747px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Motorino lavafari<br></b></nobr>");
write("</p>");
write("<p id=\"p4_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763px;top:798px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p4_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:50px;top:85px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>FUSIBILE N.8 (15 A) <br>(SCATOLA FUSIBILI/<br>RELÈ VANO MOTORE)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:110px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>RELÈ RISCALDATORE<br>CARBURANTE<br></b></nobr>");
write("</p>");
write("<p id=\"p4_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:310px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>RELÈ RISCALDATORE <br>PTC A<br></b></nobr>");
write("</p>");
write("<p id=\"p4_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:50px;top:295px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>SCATOLA RELÈ/<br>FUSIBILI VANO MOTORE <br></b></nobr>");
write("</p>");
write("<p id=\"p4_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:439px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>RELÈ RISCALDATORE <br>PTC B<br></b></nobr>");
write("</p>");
write("<p id=\"p4_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:567px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>RELÈ C RISCALDATORE<br>PTC<br></b></nobr>");
write("</p>");
write("<p id=\"p4_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:703px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>RELÈ<br>LAVAFARI <br></b></nobr>");
write("</p>");
write("<p id=\"p4_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:405px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Centralina riscaldamento/<br>centralina climatizzatore <br></b></nobr>");
write("</p>");
write("<p id=\"p4_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:533px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Centralina riscaldamento/<br>centralina climatizzatore <br></b></nobr>");
write("</p>");
write("<p id=\"p4_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:662px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Centralina riscaldamento/<br>centralina climatizzatore <br></b></nobr>");
write("</p>");
write("<p id=\"p4_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:796px;top:798px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>SCATOLA FUSIBILI/<br>RELÈ SOTTO PLANCIA <br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}