with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:554px;\" coordsize=\"950,554\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:554px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SMR9ERPJ22100000000EAID91.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:554px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:898px;top:263px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:328px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CIRCUITO AZIONAMENTO INDICATORE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:898px;top:251px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731px;top:348px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CIRCUITO PRINCIPALE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:650px;top:417px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:407px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804px;top:241px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MODULO DI COMANDO QUADRO STRUMENTI (CONTAGIRI)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:430px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>K6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:450px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>E13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:650px;top:463px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:640px;top:493px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERRUTTORE DISATTIVAZIONE VSA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:682px;top:301px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SPIA<br>ATTIVAZIONE<br>VSA<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:728px;top:301px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SPIA<br>VSA<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:813px;top:301px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SPIA<br>SISTEMA SRS<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:771px;top:301px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SPIA<br>ABS<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642px;top:301px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SPIA<br>RISERVA<br>CARBURANTE<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:596px;top:301px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SPIA<br>EPS<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:859px;top:301px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SPIA<br>CANDELETTE<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:668px;top:437px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SCATOLA DI<br>DERIVAZIONE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:149px;top:418px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:126px;top:418px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:418px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:418px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:418px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:419px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:328px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CIRCUITO AZIONAMENTO INDICATORE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:533px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G502<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:155px;top:407px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:407px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:407px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:407px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:272px;top:407px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:407px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:534px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372px;top:407px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:328px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CIRCUITO AZIONAMENTO INDICATORE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187px;top:348px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CIRCUITO PRINCIPALE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:317px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:166px;top:459px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:166px;top:463px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170px;top:463px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UNITÀ AUDIO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:166px;top:468px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:418px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:471px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:272px;top:464px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:272px;top:444px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:437px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:434px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:459px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:459px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:472px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:472px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:472px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UNITÀ AUDIO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278px;top:454px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DIODO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:166px;top:482px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:166px;top:491px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170px;top:459px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUCI ABITACOLO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65px;top:263px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65px;top:277px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65px;top:391px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:49px;top:241px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MODULO DI COMANDO QUADRO STRUMENTI (CONTAGIRI)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:330px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SPIE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:166px;top:500px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:500px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUCE VANO GAMBE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:166px;top:504px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CIRCUITO DI<br>COMMUTAZIONE SPIE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117px;top:462px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERRUTTORE <br>SET/RESUME, <br>ACCEL/CANCEL <br>REGOLATORE <br>DI VELOCITÀ<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:136px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SPIA<br>REGOLATORE <br>DI VELOCITÀ<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:311px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CIRCUITO<br>DI PROTEZIONE <br>AUTOMATICA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:244px;top:269px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CIRCUITO<br>DI ACCENSIONE<br>FORZATA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:55px;top:460px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERRUTTORE<br>PRINCIPALE<br>CONTROLLO<br>VELOCITÀ DI CROCIERA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293px;top:289px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CIRCUITO<br>DI SPEGNIMENTO<br>FORZATO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375px;top:301px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SPIA<br>GUASTI<br>(MIL)<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170px;top:468px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUCE<br>INTERRUTTORE<br>LIVELLAMENTO FARI<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:459px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DISPLAY<br>SECONDARIO<br>IMPIANTO HVAC<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170px;top:482px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUCE INTERRUTTORE<br>RISCALDATORE SEDILE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170px;top:491px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUCE INTERRUTTORE<br>TENDINA PARASOLE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:317px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SPIA <br>PRINCIPALE<br>REGOLATORE <br>DI VELOCITÀ<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:314px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SPIA <br>ESCLUSIONE<br>AIRBAG<br>LATERALE<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170px;top:504px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUCE INTERRUTTORE<br>LAVAFARI<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:498px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:498px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:503px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:503px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:498px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUCE INTERRUTTORE LUCI DI EMERGENZA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:503px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUCE INTERRUTTORE DI <br>DISATTIVAZIONE SISTEMA VSA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:526px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:526px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:512px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:512px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:521px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:521px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:521px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUCE INTERRUTTORE INFORMAZIONI<br></b></nobr>");
write("</p>");
write("<p id=\"p2_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:535px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:535px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:535px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERRUTTORE TELECOMANDO STEREO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:544px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:544px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:544px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRUPPO TASTI VIVAVOCE/COMANDO VOCALE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:540px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:540px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:540px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRUPPO TASTI COMANDO VOCALE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:526px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERRUTTORE PRINCIPALE/SET/RESUME/CANCEL<br>REGOLATORE DI VELOCITÀ<br></b></nobr>");
write("</p>");
write("<p id=\"p2_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:512px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CENTRALINA RISCALDAMENTO/<br>CENTRALINA CLIMATIZZATORE<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}