with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\" coordsize=\"950,1071\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1071px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9EQPF18100000000CDID01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:371px;top:1041px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Lato terminale dei terminali femmina<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:911px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNETTORE TRASMISSIONE DATI (16P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:386px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Lato cablaggio dei terminali femmina<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:588px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Lato terminale dei terminali maschio<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNETTORE A (2P)<br>CENTRALINA EPS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:708px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNETTORE B (2P)<br>CENTRALINA EPS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNETTORE (36P) MODULO DI COMANDO QUADRO STRUMENTI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:692px;top:448px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNETTORE 6P SENSORE ANGOLO<br>DI ROTAZIONE MOTORINO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:448px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNETTORE 2P<br>MOTORINO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185px;top:448px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNETTORE 1P<br>MOTORINO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604px;top:652px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNETTORE A (49P) MODULO ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:677px;font-weight:normal;font-size:8.00pt;\">");
write("<nobr><b>(Modello con motore L13Z1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:159px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Lato cablaggio dei terminali femmina<br></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:222px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNETTORE D (28P) CENTRALINA<br>SERVOSTERZO ELETTRICO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117px;top:222px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNETTORE C (2P)<br>CENTRALINA SERVOSTERZO ELETTRICO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:221px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNETTORE 3P<br>SENSORE DI COPPIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:651px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNETTORE A (44P) MODULO ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:166px;top:678px;font-weight:normal;font-size:8.00pt;\">");
write("<nobr><b>(Eccetto modello con motore L13Z1)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}