with(document) {
write("<v:group id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/SMR9EQ0A14600000000DAID03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:598px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MOLLA VALVOLA DI ASPIRAZIONE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:680px;top:901px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PARAOLIO VALVOLA DI ASPIRAZIONE<br><a href=\"javascript:CtsProc('0','000000000002988','i000')\"></b>Rimozione,</a><br><a href=\"javascript:CtsProc('0','000000000002989','i000')\">Installazione,</a><br></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:610px;top:995px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GUIDA VALVOLA DI ASPIRAZIONE<br><a href=\"javascript:CtsProc('0','000000000002993','i000')\"></b>Sostituzione,</a><br></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:1061px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>VALVOLA DI SCARICO<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:102px;top:1032px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>VALVOLA DI ASPIRAZIONE<br><a href=\"javascript:CtsProc('0','000000000002988','i000')\"></b>Rimozione,</a><br><a href=\"javascript:CtsProc('0','000000000002989','i000')\">Installazione,</a><br></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1px;top:580px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>VALVOLA DI SCARICO<br>GUARNIZIONE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3px;top:517px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>VALVOLA DI SCARICO<br>MOLLA<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:695px;top:550px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FERMO MOLLA<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:509px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>COPPIGLIE VALVOLE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:639px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MOLLA VALVOLA<br>SEDILE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:697px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>VALVOLA DI SCARICO<br>GUIDA<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:380px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ALBERO A CAMME<br><a href=\"javascript:CtsProc('0','000000000002971','i000')\"></b>Rimozione,</a><br><a href=\"javascript:CtsProc('0','000000000002973','i000')\">Controllo,</a><br><a href=\"javascript:CtsProc('0','000000000002972','i000')\">Installazione,</a><br></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:324px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PIASTRA IMPULSI CMP<br><a href=\"javascript:CtsProc('0','000000000002977','i000')\"></b>Sostituzione,</a><br></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:207px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>O-RING<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GRUPPO BILANCIERI<br><a href=\"javascript:CtsProc('0','000000000002978','i000')\"></b>Verifica bilanciere sistema VTEC,</a><br><a href=\"javascript:CtsProc('0','000000000002979','i000')\">Rimozione,</a><br><a href=\"javascript:CtsProc('0','000000000002980','i000')\">Installazione,</a><br>Smontaggio/rimontaggio bilanciere e albero<br><a href=\"javascript:CtsProc('0','000000000002982','i000')\"> Rimontaggio,</a><br><a href=\"javascript:CtsProc('0','000000000002981','i000')\">Controllo bilanciere e albero,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:464px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FERMO MOLLA<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:57px;top:311px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>COPPIGLIE VALVOLE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:961px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SEDE MOLLA VALVOLA<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540px;top:509px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>O-RING<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:559px;top:461px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SENSORE POSIZIONE<br>ALBERO A CAMME (CMP)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:796px;top:207px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>COPERCHIO REGGISPINTA<br>ALBERO A CAMME<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:644px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FILTRO ELETTROVALVOLA<br>DI COMANDO OLIO BILANCIERI<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:857px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ELETTROVALVOLA<br>DI COMANDO OLIO BILANCIERI<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}