with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:995px;\" coordsize=\"950,995\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:995px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9EQPJ36314300000CAID04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:995px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:272px;top:91px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MODULO DI COMANDO QUADRO STRUMENTI (CONTAGIRI)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:461px;top:127px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B-CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:127px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>CAN H<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:127px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>CAN L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:162px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>F−CAN (500 kbps)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484px;top:162px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B−CAN (33,33 kbps)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:217px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>CENTRALINA SRS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:148px;top:302px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:110px;top:388px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>CENTRALINA EPS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:217px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:720px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LINEA K<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469px;top:953px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>HDS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:619px;top:731px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>UNITÀ AUDIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Con cambio i-SHIFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:52px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Linea CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:52px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90px;top:471px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>MODULATORE−CENTRALINA<br>VSA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569px;top:291px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>CENTRALINA IMMOBILIZZATORE−<br>SISTEMA DI<br>ACCESSO CON TELECOMANDO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:572px;top:468px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>CENTRALINA RISCALDAMENTO/<br>CENTRALINA CLIMATIZZATORE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:436px;top:850px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>CONNETTORE<br>TRASMISSIONE DATI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:592px;top:555px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>SENSORE ILLUMINAZIONE<br>AUTOMATICA/PIOGGIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587px;top:638px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>CENTRALINA<br>VIVAVOCE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:384px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>CENTRALINA SENSORI<br>DI PARCHEGGIO e RETROMARCIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:556px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>MODULO<br>DI COMANDO CAMBIO (TCM)*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:720px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>SENSORE VELOCITÀ <br>DI IMBARDATA/<br>ACCELERAZIONE LATERALE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:113px;top:642px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>MODULO DI COMANDO<br>LEVA CAMBIO*<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}