with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1023px;\" coordsize=\"950,1023\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1023px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SMR9EQ2A20300000000DBID02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1023px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:54px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>BOBINA<br>DI ACCENSIONE<br>N. 1 (1)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135px;top:379px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONNETTORE 23P<br>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594px;top:218px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CORPO FARFALLATO<br>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:218px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONNETTORE 3P<br>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:378px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>MODULO ECM C (○) (13)*<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418px;top:378px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>MODULO ECM B (△) (12)*<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237px;top:54px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>BOBINA<br>DI ACCENSIONE<br>N. 2 (2)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:416px;top:54px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>BOBINA<br>DI ACCENSIONE<br>N. 3 (3)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586px;top:54px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>BOBINA<br>DI ACCENSIONE<br>N. 4 (4)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769px;top:54px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SENSORE A/F<br>(SENSORE 1)<br>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:239px;top:218px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SENSORE MAP<br>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:218px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>VALVOLA DI SPURGO<br>ELEMENTO FILTRANTE EVAP<br>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:781px;top:218px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SENSORE MAF/<br>SENSORE IAT<br>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:107px;top:582px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONNETTORE 24P SCATOLA DI DERIVAZIONE<br> (14)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:581px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>INTERRUTTORE<br>LUCI DI RETROMARCIA <br>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:582px;top:581px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ELETTROVALVOLA <br>BLOCCO RETROMARCIA <br>(M/T) (16)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:581px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SENSORE 1 ECT<br>(17)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:743px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ELETTROVALVOLA<br>DI COMANDO OLIO<br>BILANCIERI (18)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:744px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SENSORE VELOCITÀ<br>DI ROTAZIONE<br>ALBERO DI USCITA<br>(CONTRALBERO) (19)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:743px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SENSORE CMP<br>(20)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:873px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>NOTA:<br>· Connettore con terminali maschio (cornice doppia): visto dal lato terminale<br>·Connettore con terminali femmina (cornice singola): visto dal lato cablaggio<br>*: Connettore con terminali femmina (cornice singola): visto dal lato terminali<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}