with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:927px;\" coordsize=\"950,927\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:927px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E20A14666300000MFSD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:927px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:61px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SOPORTE Nº 1<br>DEL EJE DE BALANCINES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:61px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SOPORTE Nº 2<br>DEL EJE DE BALANCINES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:390px;top:61px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SOPORTE Nº 3<br>DEL EJE DE BALANCINES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540px;top:61px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SOPORTE Nº 4<br>DEL EJE DE BALANCINES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:801px;top:39px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>EJE DE BALANCINES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:793px;top:180px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SOPORTE Nº 5<br>DEL EJE DE BALANCINES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:791px;top:92px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 x 1,0 mm<br>9,8 N·m <br>(1,0 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:604px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BALANCÍN<br>PRIMARIO DE ADMISIÓN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:827px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BALANCÍN DE ESCAPE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170px;top:869px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BALANCÍN <br>SECUNDARIO B <br>DE ADMISIÓN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306px;top:868px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BALANCÍN <br>SECUNDARIO A <br>DE ADMISIÓN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:899px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BALANCÍN DE ESCAPE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:493px;top:867px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:553px;top:867px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601px;top:867px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644px;top:867px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ARANDELA B<br>(0,2 mm.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732px;top:822px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ARANDELA A<br>(0,4 mm.)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}