with(document) {
write("<v:group id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/SMR7ETP000000000000EBS301.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:716px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293px;top:716px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:546px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(Con Control de climatizador)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:576px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Nº 15 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:575px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:303px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:302px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CALENTADOR DEL COMBUSTIBLE (3-A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:302px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:266px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Nº 25 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:203px;top:265px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:265px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:266px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Nº 23 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:249px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:276px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:250px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:262px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM (3-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:276px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:337px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:337px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CONDENSADOR DE RUIDOS (7-D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:330px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INTERRUPTOR DE LUNETA TRASERA TÉRMICA (7-D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:330px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:804px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>34<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:764px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:666px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:520px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:489px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:409px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:365px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:334px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:71px;top:824px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:686px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:509px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:398px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:323px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:0px;top:289px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:409px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MOTOR DEL VENTILADOR (9-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:471px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:666px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM (FAN L) (3-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:489px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM (ACC) (3-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:520px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>EMBRAGUE DEL COMPRESOR DEL A/C (12-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:364px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNIDAD DE CONTROL DEL CLIMATIZADOR (9-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:763px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECM (FAN H) (3-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:803px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MOTOR DEL VENTILADOR DEL RADIADOR (12-A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:835px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:409px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:687px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Nº 18 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:666px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR.<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:399px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Nº 19 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:440px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:333px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:324px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Nº 12 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:697px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:489px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:520px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR.<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:31px;top:510px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Nº 7 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:364px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY.<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:724px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:705px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MOTOR DEL VENTILADOR DEL CONDENSADOR DEL A/C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:763px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY.<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:803px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:24px;top:825px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Nº 4 (OP) (80 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:834px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:176px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*1 : CAJA DE FUSIBLES/RELÉS DEBAJO DEL CAPÓ<br></b></nobr>");
write("</p>");
write("<p id=\"p3_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:183px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*2 : CAJA DE FUSIBLES/RELÉS DEBAJO DEL SALPICADERO<br></b></nobr>");
write("</p>");
write("<p id=\"p3_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:102px;top:733px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>RELÉ <br>DE CONTROL <br>DEL VENTILADOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:464px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>RELÉ DEL EMBRAGUE<br> DEL COMPRESOR DEL A/C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:63px;top:557px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RELÉ <br>DEL VENTILADOR DEL RADIADOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:89px;top:636px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>RELÉ DEL VENTILADOR <br>DEL CONDENSADOR <br>DEL A/C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:381px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RELÉ DEL MOTOR <br>DEL VENTILADOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:306px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RELÉ DE LA LUNETA <br>TRASERA TÉRMICA<br></b></nobr>");
write("</p>");
write("<p id=\"p3_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-35px;top:291px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FUSIBLE Nº 36<br>(10 A)<br>(2-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:830px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CAJA DE FUSIBLES/RELÉS<br> SITUADA DEBAJO DEL SALPICADERO <br>(OP PRINCIPAL) (2-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:226px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RELÉ <br>DEL CALENTADOR DEL COMBUSTIBLE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-40px;top:184px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RELÉ PRINCIPAL 2<br>DE LA PGM-FI<br>(1-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-40px;top:552px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RELÉ PRINCIPAL 2<br>DE LA PGM-FI<br>(1-C)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}