with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1039px;\" coordsize=\"950,1039\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1039px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7EA0R21100000000YCSD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1039px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:110px;top:27px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BURLETES <br>EXTERIORES DE LUNAS DE PUERTAS<br>Negro (NH-70 Brillo 20)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:26px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CINTA DEL CANAL <br>EXTERIOR DEL TECHO DE PUERTAS Negro (NH-70 Brillo 20)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614px;top:89px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TAPA CENTRAL DE LA REJILLA DE CAPÓ<br>Negra (NH-696 Brillo 5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:749px;top:142px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TAPA DE LA REJILLA DEL CAPÓ<br>Negro (NH-696 Brillo 5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:770px;top:435px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CARA INFERIOR DEL <br>PARACHOQUES DELANTERO<br>Color de la carrocería<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603px;top:486px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TAPA LUCES ANTINIEBLA PARACHOQUES DELANTERO <br>Color de la carrocería<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:489px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CARA SUPERIOR DEL PARACHOQUES DELANTERO<br>Color de la carrocería<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:422px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GUARNECIDO DE ESQUINA DEL PILAR DELANTERO<br>Negro (NH-70 Brillo 20)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:606px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GUARNECIDO DE MARCO DE PUERTA<br>Negro (NH-70 Brillo 20)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:273px;top:548px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MOLDURAS DE TECHO<br>Negro (NH-70 Brillo 10)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729px;top:660px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TAPA DE LLENADO DE COMBUSTIBLE<br>Recubrimiento satinado<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:792px;top:736px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GUARNECIDO INFERIOR DEL <br>PORTÓN TRASERO<br>Color de la carrocería<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:678px;top:937px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CARA INFERIOR DEL PARACHOQUES TRASERO<br>Color de la carrocería<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:680px;top:996px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CARA SUPERIOR DEL PARACHOQUES TRASERO<br>Color de la carrocería<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:18px;top:806px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PROTECTOR DEL PASO DE RUEDA DELANTERO<br>Color de la carrocería<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:149px;top:901px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PANEL DEL LARGUERO LATERAL<br>Color de la carrocería<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:11px;top:324px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CARCASA DEL ESPEJO RETROVISOR DE PUERTA<br>Color de la carrocería<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:15px;top:273px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MANECILLA EXTERIOR DE PUERTA<br>Color de la carrocería<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:996px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PROTECTOR DEL PASO DE RUEDA TRASERO<br>Color de la carrocería<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:372px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BASE DE ESPEJO RETROVISOR DE PUERTA<br>Negro (NH-70 Brillo 5)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}