with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1039px;\" coordsize=\"950,1039\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1039px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7ET6E34116317031LASD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1039px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638px;top:402px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MANGUITO DEL DEPÓSITO<br></b>Compruebe la existencia de daños, <br>fugas, interferencias <br>y deformaciones.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:10px;top:613px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CLIP DE SUJECIÓN<br></b>Sustituir.<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:863px;top:110px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DEPÓSITO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:89px;top:992px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(Lóbulo de conjuntos de freno)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:729px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>VARILLA DE EMPUJE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540px;top:853px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ANILLO ELÁSTICO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:911px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>18 N·m<br>(1,8 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540px;top:968px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PASADOR DE BLOQUEO<br></b>Sustituir.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654px;top:822px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OBTURADOR<br></b>Compruebe si está doblado<br>o dañado.<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:740px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 x 1,25 mm<br>22 N·m<br>(2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:476px;top:496px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CUERPO DEL CILINDRO MAESTRO<br></b>Compruebe la pared del cilindro<br>por si presenta arañazos o desgaste.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:571px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>JUNTA TÓRICA<br></b>Sustituir.<br></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:373px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONECTOR<br>DEL EMBRAGUE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:8px;top:463px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONECTOR DEL ENLACE DE DATOS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:142px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Los cierres del clip deben estar<br>en el lado marcado con una flecha.<br></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:223px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1−3 mm <br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Los cierres del clip deben estar<br>en el lado marcado con una flecha.<br></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278px;top:174px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1−3 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:581px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONJUNTO DEL PISTÓN<br></b>Compruebe si está rayado o desgastado.<br></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:387px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>JUNTA TÓRICA<br></b>Sustituir.<br></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:23px;top:655px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TOPE<br>DEL CLIP <br>DE SUJECIÓN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275px;top:977px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PASADOR DEL PEDAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:1003px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HORQUILLA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119px;top:699px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PASADOR ELÁSTICO<br></b>Sustituir.<br></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:31px;top:730px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>4 x 0,7 mm<br>1,5 N·m<br>(0,15 kgf·m)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}