with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E40E34150100000LCSD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:55px;top:255px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:209px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:113px;top:227px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:425px;top:263px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:267px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392px;top:101px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367px;top:86px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:57px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:256px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}