with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7ETP000000000000EBS101.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:731px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:740px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:546px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNIDAD DE CONTROL <br>DEL CLIMATIZADOR (9-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:396px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:537px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Nº 27 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:535px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488px;top:547px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>157<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488px;top:573px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>160<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:546px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CALEFACTOR PCT B (9-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:612px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Nº 28 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:611px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:648px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNIDAD DE CONTROL <br>DEL CLIMATIZADOR (9-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:648px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488px;top:622px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>156<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488px;top:649px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>161<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CALEFACTOR PCT C (9-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185px;top:431px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:484px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:458px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:471px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CALEFACTOR PCT A (9-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:293px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MÓDULO DE CONTROLDE LAS BUJÍAS DE <br>PRECALENTAMIENTO (3-A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:268px;top:284px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Nº 5 (70 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:283px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:396px;top:293px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:489px;top:294px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156px;top:751px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:489px;top:791px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:731px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488px;top:498px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>159<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488px;top:471px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>158<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:460px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:398px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:367px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:409px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:412px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:412px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>UNIDAD DE CONTROL DEL MODULADOR VSA (11-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:405px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>UNIDAD DE CONTROL DEL MODULADOR ABS (11-A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:405px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:374px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:374px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>UNIDAD DE CONTROL DEL MODULADOR VSA (11-A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:381px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>UNIDAD DE CONTROL DEL MODULADOR ABS (11-A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:381px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:378px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:327px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:305px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:348px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:348px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INTERRUPTOR DE POSICIÓN DEL <br>PEDAL DE FRENO (7-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:341px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:341px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RELÉ DE LA BOCINA (12-A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:334px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MICU (10-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:334px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:316px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MICU (10-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:250px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:324px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:276px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:233px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BATERÍA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:396px;top:409px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:378px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:368px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Nº 3 (ABS MTR) (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:396px;top:338px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:328px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Nº 21 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:249px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:249px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MOTOR DEL ESTÁRTER (10-A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:306px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Nº 22 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:316px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:316px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:399px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Nº 3 (ABS FSR) (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:353px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MAZO C DE FUSIBLES−MÚLTIPLES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:461px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Nº 26 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:497px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:497px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNIDAD DE CONTROL <br>DEL CLIMATIZADOR (9-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:338px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:396px;top:471px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:790px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNIDAD DE CONTROL EPS (11-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:777px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:725px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Nº 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:732px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(BAT)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:740px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(70 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:732px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(EPS)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:725px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Nº 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:396px;top:790px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:694px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MAZO A DE FUSIBLES−MÚLTIPLES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42px;top:36px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:23px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>Caja de fusibles y relés situada debajo del capó<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:443px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RELÉ <br>DEL CALEFACTOR A DE PTC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:731px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ALTERNADOR<br>(10-A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:433px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FUSIBLE Nº 36<br>(10 A)<br>(2-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:594px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RELÉ <br>DEL CALEFACTOR C DE PTC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:519px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RELÉ <br>DEL CALEFACTOR B DE PTC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638px;top:184px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RELÉ PRINCIPAL 2<br>DE LA PGM-FI<br>(1-C)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}