with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:495px;\" coordsize=\"950,495\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:495px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E00D52100065301KBSD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:495px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:33px;top:17px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Delanteras<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:489px;top:17px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Traseras<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182px;top:64px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Lado derecho<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:85px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>6 x 1,0 mm<br>9,8 N·m <br>(1,0 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:246px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:91px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:38px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:45px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:183px;top:37px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:426px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>6 x 1,0 mm<br>9,8 N·m <br>(1,0 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:426px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:305px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}