with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:895px;\" coordsize=\"950,895\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:895px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E00J46643400000DASD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:895px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INTERRUPTOR DE LA LLAVE DE CONTACTO<br><a href=\"javascript:CtsProc('0','000000000000247','i000')\"></b>Comprobación,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643px;top:96px;font-weight:normal;font-size:6.27pt;\">");
write("<nobr><b>ACTUADOR DE LA CERRADURA DE LA PUERTA DEL ACOMPAÑANTE/<br>DE LA PUERTA DEL CONDUCTOR<br><a href=\"javascript:CtsProc('0','000000000000306','i000')\"></b>Comprobación del actuador,</a><br><a href=\"javascript:CtsProc('0','000000000000307','i000')\">Comprobación del interruptor del pomo,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:202px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INTERRUPTOR DE LA PUERTA DEL ACOMPAÑANTE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:704px;top:730px;font-weight:normal;font-size:6.27pt;\">");
write("<nobr><b>APERTURA DEL PORTÓN TRASERO<br>ACTUADOR<br><a href=\"javascript:CtsProc('0','000000000000313','i000')\"></b>Comprobación,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702px;top:767px;font-weight:normal;font-size:6.27pt;\">");
write("<nobr><b>INTERRUPTOR DEL CIERRE DEL PORTÓN TRASERO<br><a href=\"javascript:CtsProc('0','000000000000244','i000')\"></b>Comprobación,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665px;top:824px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INTERRUPTOR DE LA PUERTA DEL CONDUCTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:742px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ACTUADOR DE LA CERRADURA DE LA PUERTA DEL CONDUCTOR/<br>INTERRUPTOR DEL POMO/CILINDRO DE LA CERRADURA<br><a href=\"javascript:CtsProc('0','000000000000306','i000')\"></b>Comprobación del actuador,</a><br><a href=\"javascript:CtsProc('0','000000000000307','i000')\">Comprobación del interruptor del pomo,</a><br><a href=\"javascript:CtsProc('0','000000000000305','i000')\">Comprobación del interruptor del cilindro de la cerradura,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:136px;top:622px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PUERTA DEL CONDUCTOR<br>INTERRUPTOR DE BLOQUEO<br><a href=\"javascript:CtsProc('0','000000000000315','i000')\"></b>Comprobación,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:11px;top:407px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>MICU<br>(Incorporado en la caja de <br>fusibles/relés situada debajo del salpicadero)<br><a href=\"javascript:CtsProc('0','000000000000311','i000')\"></b>Comprobación de la entrada,</a><br><a href=\"javascript:CtsProc('0','000000000000340','i000')\">Sustitución,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:865px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Se indica el modelo LHD, el modelo RHD es similar.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812px;top:639px;font-weight:normal;font-size:8.28pt;\">");
write("<nobr><b>INTERRUPTOR DE LA <br>MANILLA EXTERIOR<br>DEL PORTÓN TRASERO<br><a href=\"javascript:CtsProc('0','000000000000312','i000')\"></b>Comprobación/Sustitución,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206px;top:678px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>LLAVE DE LA PUERTA DEL CONDUCTOR<br>INTERRUPTOR DEL CILINDRO<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}