with(document) {
write("<v:group id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/SMR7ETP000000000000EBS313.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:149px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:593px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408px;top:475px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISP<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:29px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:149px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISP<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:448px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:164px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISP<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:448px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5 V<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISP<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120px;top:448px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PROTECCIÓN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:98px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISP<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99px;top:448px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RST<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:75px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISP<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:448px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RELOJ<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:46px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISP<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:35px;top:448px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CONECTOR <br>DE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:18px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISP<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:448px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-7px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-8px;top:441px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISP<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-5px;top:455px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BL−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-7px;top:448px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LCD<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:379px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AC-SO<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:409px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:420px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:640px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>135<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:640px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>136<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303px;top:434px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ILL (+)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:149px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D8<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:29px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D9<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ILL−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:495px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119px;top:521px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:102px;top:547px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>52<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:130px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>: Protección<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:113px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*1 : CAJA DE FUSIBLES/RELÉS DEBAJO DEL CAPÓ<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:121px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*2 : CAJA DE FUSIBLES/RELÉS DEBAJO DEL SALPICADERO<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:418px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:786px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p3_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:100px;top:738px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>155<br></b></nobr>");
write("</p>");
write("<p id=\"p3_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306px;top:631px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>98<br></b></nobr>");
write("</p>");
write("<p id=\"p3_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306px;top:339px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>79<br></b></nobr>");
write("</p>");
write("<p id=\"p3_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324px;top:312px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p3_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:312px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No.14 (7,5 A)  <br>INTERRUPTOR<br> (2-D) <br></b></nobr>");
write("</p>");
write("<p id=\"p3_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:651px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REGULADOR <br>DE LA INTENSIDAD <br>DE LUZ <br>ILUMINACIÓN <br>DEL SALPICADERO<br>(5-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:758px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNIDAD DE <br>NAVEGACIÓN (14-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:521px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No.35 (7,5 A) <br>FUSIBLE <br>(2-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375px;top:656px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNIDAD DE CONTROL<br>DEL CLIMATIZADOR (9-D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:383px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:409px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:49px;top:307px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUDIO−HVAC SUBPANTALLA−RELOJ<br></b></nobr>");
write("</p>");
write("<p id=\"p3_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-7px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:347px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY.<br></b></nobr>");
write("</p>");
write("<p id=\"p3_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY.<br></b></nobr>");
write("</p>");
write("<p id=\"p3_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR.<br></b></nobr>");
write("</p>");
write("<p id=\"p3_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:689px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:98px;top:706px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:719px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:635px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DIAL DE INTERFAZ<br></b></nobr>");
write("</p>");
write("<p id=\"p3_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:98px;top:578px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR.<br></b></nobr>");
write("</p>");
write("<p id=\"p3_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302px;top:369px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY.<br></b></nobr>");
write("</p>");
write("<p id=\"p3_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276px;top:806px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(Con sistema de navegación)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:458px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNIDAD DE AUDIO<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}