with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:799px;\" coordsize=\"950,799\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:799px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7ED1J18500024101KBSD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:799px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ETIQUETA i-VTEC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730px;top:47px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RÓTULO CIVIC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:770px;top:281px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>LOGOTIPO TIPO&quot;S&quot;<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:348px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Unidad: mm.<br>Cinta adhesiva: Espesor 0,8 mm.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:524px;top:390px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RÓTULO CIVIC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:390px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ETIQUETA i-VTEC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302px;top:390px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CINTA DE APLICACIÓN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:144px;top:549px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MARCAS DE ALINEACIÓN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:533px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Borde de la ventana<br>trasera inferior<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:681px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Extremo del portón trasero<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604px;top:584px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Extremo del portón trasero<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:401px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>81 <br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:559px;top:494px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>16 <br>(0,6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764px;top:474px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>16 <br>(0,6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:715px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>18,4<br>(0,72)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:617px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>20,5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:144px;top:681px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>18,5<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}