with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:863px;\" coordsize=\"950,863\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:863px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E2PE34150400000LDSD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:863px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:324px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GUÍA DE SINCRONIZADO <br>DE 5ª/6ª<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:127px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GUÍA<br>DE SINCRONIZADO<br>DE 3ª/4ª<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:735px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ENGRANAJE DE 4ª<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:433px;top:674px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>COLLARÍN SEPARADOR <br>DE 4ª/5ª<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:410px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CUBO DE SINCRONIZADO DE 5ª<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:252px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MUELLE DE SINCRONIZADO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:490px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ANILLO DE SINCRONIZADO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:205px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CUBO<br>DE SINCRONIZADO DE 3ª/4ª<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:460px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MUELLE DE SINCRONIZADO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:256px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ANILLO DE SINCRONIZADO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731px;top:18px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>COJINETE DE BOLAS ANGULAR<br></b>Compruebe si hay desgaste y si<br>funciona.<br>Anote el sentido del <br>montaje.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:223px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>COLLAR SEPARADOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:287px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MUELLE DE SINCRONIZADO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:623px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>JAULA DE AGUJAS<br></b>Compruebe si hay desgaste y si <br>funciona.<br></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306px;top:425px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>JAULA DE AGUJAS<br></b>Comprobar <br>la existencia <br>de desgaste <br>y su funcionamiento.<br></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:592px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SENSOR DE VELOCIDAD DEL EJE PRINCIPAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:816px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MUELLE DE SINCRONIZADO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:375px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>3ª MARCHA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:784px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ANILLO DE SINCRONIZADO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:286px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ANILLO DE SINCRONIZADO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:539px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>5ª MARCHA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:119px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6ª MARCHA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:168px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>JAULA DE AGUJAS<br></b>Compruebe si hay desgaste y si <br>funciona.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}