with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7ES0J36200000000BBSD19.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156px;top:79px;font-weight:normal;font-size:10.88pt;\">");
write("<nobr><b>Índice de guiñada<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:77px;font-weight:normal;font-size:9.61pt;\">");
write("<nobr><b>Retorno<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:113px;font-weight:normal;font-size:9.61pt;\">");
write("<nobr><b>Sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:134px;font-weight:normal;font-size:9.61pt;\">");
write("<nobr><b>Offset<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:167px;font-weight:normal;font-size:9.61pt;\">");
write("<nobr><b>Factor CCW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:208px;font-weight:normal;font-size:9.61pt;\">");
write("<nobr><b>Factor CW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:112px;font-weight:normal;font-size:9.61pt;\">");
write("<nobr><b>x.xxxV<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:134px;font-weight:normal;font-size:9.61pt;\">");
write("<nobr><b>x.xxxV<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:166px;font-weight:normal;font-size:9.61pt;\">");
write("<nobr><b>0,0‰<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:206px;font-weight:normal;font-size:9.61pt;\">");
write("<nobr><b>0,0‰<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372px;top:218px;font-weight:normal;font-size:9.61pt;\">");
write("<nobr><b>Set<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360px;top:194px;font-weight:normal;font-size:6.24pt;\">");
write("<nobr><b>Puesta a punto<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}