with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1007px;\" coordsize=\"950,1007\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1007px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E80E34150100000LCSD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1007px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:532px;top:57px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(24)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:559px;top:88px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(26)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:532px;top:29px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(25)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615px;top:130px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:161px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:128px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:780px;top:225px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(30)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815px;top:241px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(32)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:840px;top:326px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:859px;top:389px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:626px;top:400px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:626px;top:441px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:437px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:579px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:372px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392px;top:384px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:421px;top:482px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:610px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:601px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(13)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:244px;top:371px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(27)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:527px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(20)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:121px;top:566px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(14)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:31px;top:518px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(13)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:398px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(17)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:188px;top:429px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:463px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:402px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:49px;top:383px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:376px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(17)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:363px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(18)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:326px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154px;top:318px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(17)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:308px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(18)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:260px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(21)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:272px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(22)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:309px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(18)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(23)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:396px;top:57px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(21)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:25px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(22)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:55px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:124px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(19)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:245px;top:145px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(29)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:197px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(28)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:377px;top:319px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:683px;top:297px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(31)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:674px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:690px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:722px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:754px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:786px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:802px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:834px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:850px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:866px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:882px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:898px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:914px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:930px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(13)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:962px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(14)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:674px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:706px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:738px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(17)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:754px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(18)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:770px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(19)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:786px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(20)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:802px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(21)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:834px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(22)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:866px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(23)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:898px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(24)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:930px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(25)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:674px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(26)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:706px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(27)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:722px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(28)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:738px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(29)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:770px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(30)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:674px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CARCASA DE LA CAJA DE CAMBIOS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:690px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ARANDELA DE 10 mm<br></b>Sustituir.<br></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:722px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TORNILLO DE BRIDA DE 10 mm<br>44 N·m (4,5 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:754px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TORNILLO DE BRIDA DE 8 mm<br>27 N·m (2,8 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:786px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SOPORTE A DE LA CAJA DE CAMBIOS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:802px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TORNILLO DE ENCLAVAMIENTO<br>39 N·m (4,0 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:834px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PLATO DE GUÍA DE ACEITE M<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:850px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SUPLEMENTO DE 72 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:866px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PLATO DE BAJADA DE ACEITE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:882px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SUPLEMENTO DE 80 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:898px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CLAVIJA DE 8 x 14 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:914px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONJUNTO DE LA PALANCA DE CAMBIOS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:930px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TORNILLO DE BRIDA DE 6 x 1,0 mm<br>12 N·m (1,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:962px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TORNILLO DE BRIDA DE 6 x 20 mm<br>12 N·m (1,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:674px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TORNILLO DE RETENCIÓN<br>22 N·m (2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:706px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ARANDELA DE 12 mm<br></b>Sustituir.<br></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:738px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MUELLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:754px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BOLA DE ACERO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:770px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SOPORTE B DE LA CAJA DE CAMBIOS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:802px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ARANDELA DE 20 mm<br></b>Sustituir.<br></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:834px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TAPÓN DE LLENADO<br>44 N·m (4,5 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:866px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RETÉN DE ACEITE DE 40 x 56 x 8 mm<br></b>Sustituir.<br></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:898px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ARANDELA DE 14 mm<br></b>Sustituir.<br></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:930px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TAPÓN DE DRENAJE<br>39 N·m (4,0 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644px;top:674px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TAPÓN DE CIERRE DE 32 mm<br>34 N·m (3,5 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644px;top:706px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>AOPORTE B DEL MAZO DE CABLES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644px;top:722px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SOPORTE DE LA CAJA DE CAMBIOS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644px;top:738px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TORNILLO DE BRIDA DE 10 mm<br>44 N·m (4,5 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644px;top:770px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SENSOR DE VELOCIDAD <br>DEL EJE SECUNDARIO (DE SALIDA)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:786px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SOPORTE DEL CLIP DEL TUBO DE EMBRAGUE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:802px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(31)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644px;top:802px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>JUNTA TÓRICA<br></b>Sustituir.<br></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:834px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(32)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644px;top:834px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TORNILLO DE BRIDA DE 6 mm<br>12 N·m (1,2 kgf·m)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}