with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:783px;\" coordsize=\"950,783\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:783px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E40A20326400000DASD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:783px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:196px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>MANGUITO DE RETORNO DEL <br>COMBUSTIBLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:179px;top:127px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>TUBOS DE ALTA PRESIÓN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:98px;top:636px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>SENSOR <br>DE PRESIÓN DE LA RAMPA DE INYECCIÓN <br>DE COMBUSTIBLE (FRP)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303px;top:702px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>TUBERÍA ALIMENTACIÓN DE COMBUSTIBLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:676px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>TUBERÍA DE RETORNO DEL COMBUSTIBLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:490px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>RACORES DE CONEXIÓN RÁPIDA<br><a href=\"javascript:CtsProc('0','000000000001143','i000')\"></b>Precauciones,</a><br><a href=\"javascript:CtsProc('0','000000000001144','i000')\">Desmontaje,</a><br><a href=\"javascript:CtsProc('0','000000000001145','i000')\">Montaje,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:802px;top:278px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>TAPÓN DE LLENADO <br>DE COMBUSTIBLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688px;top:88px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>TUBERÍA VAPOR DEL COMBUSTIBLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550px;top:578px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DEPÓSITO DE COMBUSTIBLE<br><a href=\"javascript:CtsProc('0','000000000001149','i000')\"></b>Drenaje,</a><br><a href=\"javascript:CtsProc('0','000000000001150','i000')\">Sustitución,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:751px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b></b>*: Esta ilustración muestra el modelo LHD.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:10px;top:692px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>RAMPA INYECCIÓN COMBUSTIBLE<br><a href=\"javascript:CtsProc('0','000000000001148','i000')\"></b>Sustitución,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586px;top:17px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>TRANSMISOR DEL AFORADOR DE COMBUSTIBLE<br><a href=\"javascript:CtsProc('0','000000000001137','i000')\"></b>Comprobación,</a><br><a href=\"javascript:CtsProc('0','000000000001138','i000')\">Sustitución,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:686px;top:435px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>TUBO DE LLENADO DE COMBUSTIBLE<br><a href=\"javascript:CtsProc('0','000000000001140','i000')\"></b>Desmontaje/Montaje,</a><br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}