with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:943px;\" coordsize=\"950,943\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:943px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E40A20336335001KDSD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:943px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108px;top:16px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 x 1,0 mm<br>12 N·m <br>(1,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:16px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ELECTRO<br>VÁLVULA <br>DE CONTROL DE LA CORREDERA <br>DEL COLECTOR DE ADMISIÓN (IMRC)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498px;top:317px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>JUNTA<br></b>Sustituir.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:608px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>VÁLVULA IMRC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:421px;top:678px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 x 1,25 mm<br>22 N·m <br>(2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744px;top:264px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONDUCTO<br>DE ADMISIÓN DEL AIRE<br>(sin DPF)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:596px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SOPORTE DEL<br>COLECTOR DE ADMISIÓN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:651px;top:898px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 x 1,25 mm<br>22 N·m (2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:151px;top:648px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 x 1,25 mm<br>22 N·m <br>(2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:31px;top:511px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>COLECTOR DE ADMISIÓN<br></b>Sustituya si está agrietada o si<br>está dañada la superficie<br>de acoplamiento.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:600px;top:593px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>JUNTA<br></b>Sustituir.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:430px;top:41px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>JUNTA<br></b>Sustituir.<br></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:18px;top:436px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 x 1,25 mm<br>22 N·m <br>(2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:860px;top:324px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 x 1,25 mm<br>22 N·m <br>(2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:470px;top:852px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>VÁLVULA<br>ISV<br>(con DPF)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}