with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:588px;\" coordsize=\"950,588\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:588px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR8EVXH46400000000CASD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:588px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:223px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>VB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:251px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>VA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:450px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>DLC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:450px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>MES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:450px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>SCS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:333px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>CIRCUITO DE ACTIVACIÓN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:394px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:55px;top:330px;font-weight:normal;font-size:4.50pt;\">");
write("<nobr><b>SENSOR DE <br>IMPACTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:198px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>UNIDAD SRS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:333px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>CIRCUITO DE DIAGNÓSTICO y del MICROPROCESADOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:450px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>CAN+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:450px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>CELAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:377px;top:542px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>MÓDULO DE CONTROL DE LOS INDICADORES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:139px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>INTERRUPTOR <br>DE OCUPACIÓN <br>DEL ASIENTO <br>DEL <br>ACOMPAÑANTE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:474px;top:91px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>SENSOR <br>DE IMPACTO<br>LATERAL <br>DERECHO (SEGUNDO) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:89px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>SENSOR <br>DE IMPACTO<br>LATERAL<br> IZQUIERDO (SEGUNDO) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:848px;top:503px;font-weight:normal;font-size:4.50pt;\">");
write("<nobr><b>TENSOR <br>DE LA HEBILLA DEL<br> CINTURÓN <br>DE SEGURIDAD <br>DEL LADO <br>DERECHO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804px;top:147px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>CARRETE DEL<br> CABLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:15px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>PRIMER <br>DISPOSITIVO <br>DE INFLADO <br>DEL AIRBAG <br>DEL CONDUCTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837px;top:22px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>DISPOSITIVO<br>DE INFLADO <br>DEL AIRBAG <br>DEL ACOMPAÑANTE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:463px;top:493px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>LUZ TESTIGO <br>DEL SRS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372px;top:486px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>LUZ TESTIGO DE<br>CORTE DEL <br>AIRBAG LATERAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:791px;top:503px;font-weight:normal;font-size:4.50pt;\">");
write("<nobr><b>TENSOR <br>DE LA HEBILLA <br>DEL CINTURÓN <br>DE SEGURIDAD <br>DEL LADO <br>IZQUIERDO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730px;top:503px;font-weight:normal;font-size:4.50pt;\">");
write("<nobr><b>TENSOR DEL <br>CINTURÓN <br>DE SEGURIDAD <br>DEL LADO <br>DERECHO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:503px;font-weight:normal;font-size:4.50pt;\">");
write("<nobr><b>TENSOR DEL <br>CINTURÓN <br>DE SEGURIDAD <br>DEL LADO <br>IZQUIERDO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:616px;top:503px;font-weight:normal;font-size:4.50pt;\">");
write("<nobr><b>DISPOSITIVO <br>DE INFLADO <br>DEL AIRBAG <br>DE CORTINA <br>LATERAL <br>DERECHO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:559px;top:503px;font-weight:normal;font-size:4.50pt;\">");
write("<nobr><b>DISPOSITIVO <br>DE INFLADO <br>DEL AIRBAG <br>DE CORTINA <br>LATERAL <br>IZQUIERDO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:391px;font-weight:normal;font-size:4.50pt;\">");
write("<nobr><b>CIRCUITO <br>DE ENLACE <br>DE DATOS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:392px;font-weight:normal;font-size:4.50pt;\">");
write("<nobr><b>CIRCUITO <br>DE LA <br>MEMORIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:346px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>SENSOR <br>DE IMPACTO <br>LATERAL <br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:300px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>SENSOR DE <br>IMPACTO <br>DELANTERO <br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160px;top:238px;font-weight:normal;font-size:4.50pt;\">");
write("<nobr><b>CIRCUITO<br> DE ALIMENTACIÓN<br> DE CORRIENTE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278px;top:149px;font-weight:normal;font-size:4.50pt;\">");
write("<nobr><b>SENSOR <br>DE IMPACTO <br>DELANTERO <br>IZQUIERDO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:147px;font-weight:normal;font-size:4.50pt;\">");
write("<nobr><b>SENSOR <br>DE IMPACTO <br>DELANTERO <br>DERECHO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:152px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>SENSOR <br>DE IMPACTO LATERAL <br>IZQUIERDO <br>(PRIMERO) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:478px;top:153px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>SENSOR <br>DE IMPACTO LATERAL <br>DERECHO <br>(PRIMERO) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:13px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>DISPOSITIVO <br>DE INFLADO <br>DEL AIRBAG<br>LATERAL <br>IZQUIERDO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:619px;top:13px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>DISPOSITIVO <br>DE INFLADO <br>DEL AIRBAG <br>LATERAL <br>DERECHO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:147px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>CAJA −DE FUSIBLES/RELÉS<br>SITUADA <br>DEBAJO DEL SALPICADERO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:748px;top:14px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>SEGUNDO<br>DISPOSITIVO <br>DE INFLADO <br>DEL AIRBAG <br>DEL CONDUCTOR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}