with(document) {
write("<v:group id=\"group6\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect6\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img6\" name=\"PrtImgId\" src=\"../img/SMR8EL0J54230100000EASD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p6_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:343px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruptor de entrada del lado del conductor<br></b></nobr>");
write("</p>");
write("<p id=\"p6_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:357px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruptor de entrada del lado del acompañante<br></b></nobr>");
write("</p>");
write("<p id=\"p6_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:307px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruptor del calefactor del asiento del acompañante<br></b></nobr>");
write("</p>");
write("<p id=\"p6_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:257px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruptor de la hebilla del cinturón de seguridad del acompañante<br></b></nobr>");
write("</p>");
write("<p id=\"p6_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:50px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Calefactor del asiento del acompañante<br></b></nobr>");
write("</p>");
write("<p id=\"p6_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:243px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruptor de la hebilla del cinturón de seguridad del conductor<br></b></nobr>");
write("</p>");
write("<p id=\"p6_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:243px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:243px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p6_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:293px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p6_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:293px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:479px;top:403px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Enchufe de la caja de fusibles/relés)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:479px;top:439px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Enchufe de la caja de fusibles/relés)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:414px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p6_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:414px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p6_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:414px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:207px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Sensor de aceleración lateral-ángulo de guiñada<br></b></nobr>");
write("</p>");
write("<p id=\"p6_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:207px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p6_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:207px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:486px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G602<br></b></nobr>");
write("</p>");
write("<p id=\"p6_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:343px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:343px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p6_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:293px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interuptor del calefactor del asiento del conductor<br></b></nobr>");
write("</p>");
write("<p id=\"p6_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:86px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p6_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:86px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:86px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Toma de corriente delantera para los accesorios<br></b></nobr>");
write("</p>");
write("<p id=\"p6_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:450px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Conector de comprobación del servicio MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p6_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:150px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p6_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:36px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:36px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p6_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:36px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Calefactor del asiento del conductor<br></b></nobr>");
write("</p>");
write("<p id=\"p6_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:136px;top:670px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p6_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:672px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Mazo de cables del piso<br></b></nobr>");
write("</p>");
write("<p id=\"p6_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119px;top:672px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p6_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:370px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>CAJA DE −FUSIBLES/RELÉS<br>SITUADA DEBAJO DEL SALPICADERO<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}