with(document) {
write("<v:group id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:904px;\" coordsize=\"950,904\">");
write("<v:rect id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:904px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/SMR9ERPJ54260462001EASD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:904px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:506px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nº 6 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:53px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>CAJA DE FUSIBLES/RELÉS DEBAJO DEL SALPICADERO<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:521px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:521px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>Relé de las luces antiniebla delanteras<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306px;top:749px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nº 31 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:764px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>Relé de la toma de corriente delantera para los accesorios<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:477px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nº 5 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:493px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>Calefactor del asiento del conductor<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:463px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:507px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>Calefactor del asiento del pasajero delantero<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:577px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nº 7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506px;top:593px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296px;top:620px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nº 27 (No se utiliza)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306px;top:663px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nº 28 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306px;top:706px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nº 29 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506px;top:721px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506px;top:764px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:422px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:214px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Relé inhibidor<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:157px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Relé 2 de corte del motor de arranque<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:157px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498px;top:186px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:186px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:334px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nº 35 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133px;top:320px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:279px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:87px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:128px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296px;top:784px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nº 22 (No se utiliza)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:678px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:383px;top:170px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nº 23 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506px;top:214px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRY.<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:128px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:462px;top:339px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Enchufe de la caja de fusibles/relés)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:350px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498px;top:493px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:87px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:593px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>Relé de las luces de conducción diurna (modelo KS)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:678px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>Relé de la toma de corriente trasera para los accesorios<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:721px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>Relé del encendedor de cigarrillos<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672px;top:168px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>Solenoide del motor de arranque <br>(A través del relé de corte del motor de arranque)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:186px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:71px;top:365px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>FUSIBLE Nº 4 (80 A) <br>(OP)<br>(CAJA DE FUSIBLES/RELÉS<br>SITUADA DEBAJO DEL CAPÓ)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:642px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>Luz de posición delantera izquierda <br>(A través del relé de la luces de conducción diurna) <br>(modelo KS)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:536px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>Luz antiniebla delantera izquierda <br>(A través del relé de las luces antiniebla delanteras)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:564px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>Luz antiniebla delantera derecha <br>(A través del relé de las luces antiniebla delanteras)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:245px;top:112px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>RELÉ <br>DE CORTE 1 DEL MOTOR DE ARRANQUE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:125px;top:238px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>INTERRUPTOR <br>DE ENCENDIDO <br>(ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:107px;top:23px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>FUSIBLE <br>Nº 2 (IG) (50 A) <br>(CAJA DE FUSIBLES/RELÉS <br>SITUADA DEBAJO <br>DEL CAPÓ)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:11px;top:42px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>INTERRUPTOR <br>DE ARRANQUE <br>DEL MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:606px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>Luz de posición delantera derecha <br>(A través del relés de la luces de conducción diurna) <br>(modelo KS) <br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:693px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>Toma de corriente trasera para los accesorios<br>(a través del relé de la toma de corriente trasera para los accesorios)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:736px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>Encendedor de cigarrillos<br>(A través del relé del encendedor de cigarrillos)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:783px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>Toma de corriente delanterfa para los accesorios<br>(a través del relé de la toma de corriente delantera para los accesorios)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:405px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nº 34 (No se utiliza)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507px;top:385px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:668px;top:386px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:701px;top:385px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RELÉ DE CORTE ACC<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}