with(document) {
write("<v:group id=\"group6\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect6\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img6\" name=\"PrtImgId\" src=\"../img/SMR9ER2A20300000000DBSD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p6_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:395px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONECTOR 23P (11)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677px;top:41px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONECTOR 12P (3)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:448px;top:412px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>INTERRUPTOR <br>DE INERCIA (12)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:401px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONECTOR R <br>DE LA CAJA DE FUSIBLES/RELÉS SITUADA DEBAJO <br>DEL SALPICADERO (13)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:148px;top:41px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONECTOR 28P (1)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:449px;top:40px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>INTERRUPTOR DE ENCENDIDO (2)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:110px;top:857px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONECTOR G (17) DE LA CAJA DE FUSIBLES/RELÉS SITUADA DEBAJO DEL SALPICADERO<br></b></nobr>");
write("</p>");
write("<p id=\"p6_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:795px;top:839px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONECTOR C (19) DE LA CAJA <br>DE FUSIBLES/RELÉS<br> SITUADA DEBAJO <br>DEL SALPICADERO <br></b></nobr>");
write("</p>");
write("<p id=\"p6_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:540px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONECTOR E (15) DE LA CAJA DE FUSIBLES/RELÉS SITUADA DEBAJO DEL SALPICADERO<br></b></nobr>");
write("</p>");
write("<p id=\"p6_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:690px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONECTOR F (16) DE LA CAJA DE FUSIBLES/RELÉS SITUADA DEBAJO DEL SALPICADERO<br></b></nobr>");
write("</p>");
write("<p id=\"p6_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638px;top:840px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONECTOR D<br>DE LA CAJA DE <br>FUSIBLES/RELÉS<br>SITUADA DEBAJO DEL <br>SALPICADERO (18)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65px;top:556px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONECTOR Q DE LA CAJA DE <br>FUSIBLES/RELÉS SITUADA DEBAJO DEL SALPICADERO<br> (14)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643px;top:144px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>MÓDULO DE CONTROL DE LOS INDICADORES <br>(TACH) (6)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284px;top:254px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SENSOR APP (8)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:110px;top:253px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONECTOR <br>DE LA CAJA DE CONEXIONES<br>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:143px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONECTOR 12P (4)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:143px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CONECTOR 20P (5)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:254px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>RELÉ DE CORTE (10)<br>DEL MOTOR <br>DE ARRANQUE 2 <br>(M/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:259px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>RELÉ<br>DEL INHIBIDOR (9) <br>(M/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:819px;top:254px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>RELÉ DE CORTE 2<br>DEL MOTOR DE <br>ARRANQUE <br>(con i-SHIFT)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717px;top:258px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>RELÉ DEL <br>INHIBIDOR (9) <br>(con i-SHIFT)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:1011px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>NOTA:<br>· Conector con terminales macho (subrayado doble): visto desde el lado del terminal<br>· Conector con terminales hembra (subrayado simple): visto desde el lado del cable.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}