with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:831px;\" coordsize=\"950,831\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:831px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9EQPD52100000000CASD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:831px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:421px;top:556px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>UNIDAD DE CONTROL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:669px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>MODULADOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:607px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>UNIDAD DE CONTROL <br> DEL MODULADOR VSA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499px;top:609px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Señal<br>de presión del freno<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:607px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>· Control de electroválvula<br>· Control del motor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:784px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Comunicación vía F-CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:126px;top:77px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>INTERRUPTOR <br>DE DESCONEXIÓN <br>DE VSA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:211px;top:78px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>INTERRUPTOR <br>DEL FRENO DE <br>ESTACIONAMIENTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:73px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>INTERRUPTOR <br>DEL NIVEL <br>DEL LÍQUIDO <br>DE FRENOS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715px;top:324px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RUEDA <br>TRASERA IZQUIERDA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:449px;top:260px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>· Solicitud de control del par del motor<br>· Señal de modo de control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:695px;top:224px;font-weight:normal;font-size:5.73pt;\">");
write("<nobr><b>· Activación/desactivación del control de VSA<br>· Señal del ángulo de apertura del acelerador<br>· Señal de las revoluciones del motor<br>· Señal del interruptor de posición<br>   del pedal de freno<br>· Señal de comprobación de servicio<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:356px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Señal de impulsos<br>de giro de la rueda<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:190px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:67px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>INTERRUPTOR <br>DE<br>POSICIÓN DEL<br>PEDAL DE<br>FRENO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:189px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>MÓDULO DE CONTROL DE LOS INDICADORES (TAC)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320px;top:373px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SENSOR <br>DEL ÁNGULO <br>DE LA DIRECCIÓN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246px;top:224px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>· Señal del interruptor de desconexión de VSA<br>· Señal del interruptor del freno de estacionamiento<br>· Señal del interruptor del nivel del líquido de frenos<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:286px;top:330px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>· Señal del índice de guiñada<br>· Señal de aceleración lateral/longitudinal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:420px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Señal de ángulo de la dirección<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60px;top:247px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Señal de activación <br>de las luces testigo<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270px;top:273px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>SENSOR DE <br>ACELERACIÓN <br>LATERAL/LONGITUDINAL-<br>ÍNDICE DE<br>GUIÑADA<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}