with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:415px;\" coordsize=\"950,415\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:415px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9EQDE34137300000CASD15.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:415px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:792px;top:240px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Parpadeo<br>del indicador<br>de posición<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:13px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Pedal<br>de freno<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495px;top:13px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>IG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633px;top:13px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Motor de arranque<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:30px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495px;top:30px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:46px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:249px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Pedal<br>de freno<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495px;top:249px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>IG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:243px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Motor de arranque<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:266px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495px;top:266px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:282px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117px;top:10px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Palanca de cambios<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187px;top:30px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}