with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:415px;\" coordsize=\"950,415\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:415px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SMR9ERPJ36200000000CASD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:415px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:21px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Vista aumentada del sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:72px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>ELEMENTOS PIEZOELÉCTRICOS<br> DE DETECCIÓN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:132px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>OSCILADORES<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:136px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>PASADOR DE APOYO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:7px;top:234px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>ELEMENTO PIEZOELÉCTRICO<br> DE EXCITACIÓN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:379px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>BLOQUE METÁLICO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:356px;top:361px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>ELEMENTO PIEZOELÉCTRICO<br> DE CONTROL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:433px;top:287px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Curva<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:338px;top:198px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Oscilación<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:549px;top:228px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Fuerza de Coriolis<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:626px;top:143px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Gire a <br>la derecha<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:759px;top:176px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Fuerza de Coriolis<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:872px;top:198px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Oscilación<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:22px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Vista superior del sensor<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}