with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9EQP000000000000EBS108.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:23px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>Módulo de control de los indicadores (tac)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:497px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:661px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:661px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:630px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:696px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:696px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>UNIDAD DE SONIDO (18−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:623px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:528px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:697px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:697px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:661px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DEL INTERRUPTOR DE LAS LUCES DE EMERGENCIA  (10−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:690px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DEL INTERRUPTOR DE DESCONEXIÓN DE VSA (16−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:634px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:634px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:668px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:668px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:620px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:620px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583px;top:582px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:570px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:539px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:528px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:528px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:567px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:567px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:581px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:581px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:581px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNIDAD DE SONIDO (18−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:555px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DIODO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:658px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:630px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ AMBIENTAL (10-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:258px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:458px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:224px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MÓDULO DE CONTROL DE LOS INDICADORES (TAC)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:637px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:637px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DE PISO DEL CONDUCTOR (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:651px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:690px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:690px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:658px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DEL INTERRUPTOR DEL CALEFACTOR <br>DEL ASIENTO DEL CONDUCTOR (13−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:623px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DEL INTERRUPTOR DE NIVELACIÓN DE LOS FAROS (9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:689px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:689px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DEL INTERRUPTOR DEL TECHO CORERDIZO (14-D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:556px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>102<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586px;top:609px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>85<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:609px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>88<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:651px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DEL INTERRUPTOR DEL LAVAFAROS (11−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:644px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:644px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DE PISO DEL ACOMPAÑANTE (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:673px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:673px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DEL INTERRUPTOR DEL CALEFACTOR DEL <br>ASIENTO DEL ACOMPAÑANTE (13−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506px;top:722px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506px;top:722px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:715px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>INTERRUPTOR DE CONTROL DE VOZ (19−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506px;top:715px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506px;top:715px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:697px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>INTERRUPTOR MANDO A DISTANCIA <br>DEL SISTEMA DE SONIDO (18−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:722px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>INTERRUPTOR DE CONTROL DE VOZ−HFT (19−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:335px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>CIRCUITO <br>DE SEGURIDAD <br>CONTRA FALLOS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:436px;top:268px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CIRCUITO <br>DE CONEXIÓN <br>OBLIGATORIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507px;top:269px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CIRCUITO <br>DE DESCONEXIÓN <br>OBLIGATORIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:313px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ <br>TESTIGO <br>DE FALLO DE <br>FUNCIONAMIENTO <br>(MIL) <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:634px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DEL INTERRUPTOR DE ESTABLECIMIENTO<br>/REANUDACIÓN/CANCELACIÓN <br>DEL CONTROL DE LA VELOCIDAD <br>DE CRUCERO (7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:567px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PANTALLA AUXILIAR <br>DE HVAC (14−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:669px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>UNIDAD DE CONTROL DEL CALEFACTOR/<br>UNIDAD DE CONTROL DEL CLIMATIZADOR (14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:620px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUCES DEL INTERRUPTOR <br>DE INFORMACIÓN/SELECCIÓN/RESTABLECIMIENTO (7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:683px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>INTERRUPTOR DEL S−MODE (16−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:683px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:683px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}