with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:769px;\" coordsize=\"950,769\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:769px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9EQPJ36314300000EASD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:769px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:232px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:209px;top:206px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>Q6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:603px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:594px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:655px;top:594px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:512px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:457px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659px;top:512px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702px;top:440px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:655px;top:440px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:165px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:378px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:209px;top:361px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:152px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:114px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>CAJA DE FUSIBLES/RELÉS DEBAJO DEL SALPICADERO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99px;top:165px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>K−LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118px;top:206px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>Q8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:100px;top:232px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:306px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:306px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575px;top:306px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392px;top:361px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:378px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587px;top:361px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569px;top:378px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:378px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:741px;top:361px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730px;top:306px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718px;top:457px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:320px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:651px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>UNIDAD SRS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:651px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:660px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:679px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:706px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:782px;top:561px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>UART<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798px;top:543px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:780px;top:489px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798px;top:457px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:782px;top:440px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>UART<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:466px;top:378px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484px;top:361px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:306px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:289px;top:306px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:361px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283px;top:378px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:724px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:724px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>UNIDAD DE CONTROL DE LA EPS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181px;top:393px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>UNIDAD <br>DE CONTROL-<br>DE ENTRADA <br>SIN LLAVE-<br>INMOVILIZADOR<br>(7P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:397px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>UNIDAD DE CONTROL <br>DEL CALEFACTOR/ <br>UNIDAD DE CONTROL <br>DEL CLIMATIZADOR <br>(32P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:399px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>UNIDAD <br>DE CONTROL <br>DEL TELÉFONO <br>MANOS LIBRES <br>(28P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698px;top:406px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>MÓDULO DE CONTROL <br>DE LOS INDICADORES (TAC) (36P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:655px;top:603px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>MÓDULO DE CONTROL<br> DE LA CAJA DE CAMBIOS<br>(TCM)*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:661px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>UNIDAD DE CONTROL−<br>MODULADOR DE VSA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:678px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>SENSOR <br>DE ACELERACIÓN<br>LATERAL-ÍNDICE DE GUIÑADA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:706px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>CONECTOR DE <br>ENLACE DE DATOS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764px;top:580px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>MÓDULO <br>DE CONTROL <br>DE LOS <br>INDICADORES <br>(VELOCÍM) (12P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:399px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>SENSOR <br>DE LLUVIA/<br>ALUMBRADO <br>AUTOMÁTICO <br>(5P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:396px;font-weight:normal;font-size:4.50pt;\">");
write("<nobr><b>UNIDAD DE <br>CONTROL (16P)<br>DE LOS <br>SENSORES <br>DE ESTACIONAMIENTO y <br>MARCHA ATRÁS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694px;top:32px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:31px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:32px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>Con sistema i−SHIFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:41px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>Con teléfono manos libres<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:41px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694px;top:41px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:77px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>Protección<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:77px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:66px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:66px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>Otra línea de comunicación<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:55px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>Línea CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:54px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:401px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:419px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:447px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:465px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:483px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:483px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>UNIDAD SRS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:492px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:492px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>UNIDAD DE AUDIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:632px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>MÓDULO DE CONTROL <br>DEL CAMBIO DE MARCHAS*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:401px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>CONECTOR DE <br>ENLACE DE DATOS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:419px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>UNIDAD DE CONTROL− <br>DE ENTRADA SIN LLAVE<br>INMOVILIZADOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:447px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>UNIDAD DE CONTROL− <br>MODULADOR DE VSA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:465px;font-weight:normal;font-size:5.53pt;\">");
write("<nobr><b>UNIDAD <br>DE CONTROL DE LA EPS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:632px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}