with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SMR9EQPJ54260462100EASD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:242px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:273px;top:1008px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353px;top:227px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nº 2 (IG) (50 A) :<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:270px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nº 2 (H/L) (60 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:243px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:286px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:285px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:202px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MAZO B DE FUSIBLES−MÚLTIPLES<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:312px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nº 6 (P/W) (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:328px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:329px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:372px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:371px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:414px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360px;top:398px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nº 16 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:355px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nº 17 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:427px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nº 9 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:31px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>CAJA DE FUSIBLES/RELÉS DEBAJO DEL CAPÓ<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:466px;top:493px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:535px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546px;top:578px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:535px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ECM (MRLY)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:628px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Sensor de CMP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:614px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Sensor de CKP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:671px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Inyector Nº 3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:685px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Inyector Nº 4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:657px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Inyector Nº 2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:642px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Inyector Nº 1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:963px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nº 8 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:935px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:935px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ECM (DBWRLY−)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:978px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ECM (VBDBW)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539px;top:978px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:414px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614px;top:614px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:579px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615px;top:971px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT/GRN*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624px;top:578px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546px;top:699px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:699px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ECM (IGP)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:128px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:185px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ECM (ELD)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:185px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:235px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182px;top:314px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:157px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ELD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:273px;top:86px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:142px;top:79px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546px;top:835px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:850px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Sensor de CMP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:835px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Sensor de CKP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:892px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Inyector Nº 3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:907px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Inyector Nº 4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:878px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Inyector Nº 2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:864px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Inyector Nº 1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614px;top:835px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:800px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:760px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:538px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:985px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT*<sup>4</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:617px;top:799px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:232px;font-weight:normal;font-size:6.18pt;\">");
write("<nobr><b>CAJA <br>DE FUSIBLES/RELÉS <br>SITUADA DEBAJO DEL SALPICADERO (IG MAIN)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:275px;font-weight:normal;font-size:6.18pt;\">");
write("<nobr><b>CAJA <br>DE FUSIBLES/RELÉS <br>SITUADA DEBAJO DEL SALPICADERO (OP MAIN)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:318px;font-weight:normal;font-size:6.18pt;\">");
write("<nobr><b>CAJA <br>DE FUSIBLES/RELÉS <br>SITUADA DEBAJO DEL SALPICADERO (P/W MAIN)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:361px;font-weight:normal;font-size:6.18pt;\">");
write("<nobr><b>CAJA <br>DE FUSIBLES/RELÉS <br>SITUADA DEBAJO DEL SALPICADERO (INTERIOR)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:404px;font-weight:normal;font-size:6.18pt;\">");
write("<nobr><b>CAJA DE <br>FUSIBLES/RELÉS <br>SITUADA DEBAJO DEL SALPICADERO (+B) <br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:489px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>RELÉ<br> PRINCIPAL 1 DE PGM-FI<br> (FI MAIN)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:436px;top:450px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>RELÉ DE <br>LA BOBINA <br>DE ENCENDIDO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:863px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>RELÉ <br>DEL SISTEMA <br>DE CONTROL ELECTRÓNICO <br>DEL ACELERADOR <br>(ETCS)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:34px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>FUSIBLE N.º 3 (10 A)<br>(CAJA DE FUSIBLES/RELÉS <br>SITUADA DEBAJO DEL SALPICADERO)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:782px;font-weight:normal;font-size:5.15pt;\">");
write("<nobr><b>CAJA DE <br>FUSIBLES/RELES <br>SITUADA DEBAJO <br>DEL SALPICADERO <br>(RELÉ PRINCIPAL <br>2 DE PGM-FI)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:752px;top:557px;font-weight:normal;font-size:5.15pt;\">");
write("<nobr><b>CAJA DE <br>FUSIBLES/RELES <br>SITUADA DEBAJO <br>DEL SALPICADERO <br>(RELÉ PRINCIPAL <br>2 DE PGM-FI)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:678px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Motor K20Z4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688px;top:49px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Motor R18A2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:678px;top:49px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658px;top:49px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658px;top:61px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:678px;top:61px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688px;top:61px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Motor R18A2 y L13Z1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688px;top:72px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Motor K20Z4 y L13Z1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:678px;top:72px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658px;top:72px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}