with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E00R31100000000YDGD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:34px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OBERER TRENNWAND-SEITENRAHMEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:232px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TRENNWAND-SEITENHALTESTREBE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:794px;top:58px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OBERER TRENNWAND-<br>SEITENRAHMEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:349px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 x 1,0 mm<br>18 N·m (1,8 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:502px;top:489px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OBERER TRENNWAND-<br>SEITENRAHMEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:462px;top:532px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>[X]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:692px;top:506px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>[Y]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:456px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>UNTERE RADKASTENVERLÄNGERUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:493px;top:1044px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>VORDERER SEITENRAHMEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:1042px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>UNTERER<br>TRENNWAND-QUERTRÄGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99px;top:851px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TRENNWAND-SEITENHALTESTREBE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:46px;top:714px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 x 1,0 mm<br>18 N·m<br>(1,8 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:23px;top:371px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OBERER TRENNWAND-MITTELRAHMEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:662px;top:284px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>[ANSICHT: Y]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:285px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>[ANSICHT: X]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529px;top:15px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>UNTERE RADKASTENVERLÄNGERUNG<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}