with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:687px;\" coordsize=\"950,687\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:687px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7EDAF18100000000DAGD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:687px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:163px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>BATTERIE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:35px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>INSTRUMENTENSTEUERMODUL (DREHZAHLMESSER)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:794px;top:232px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>SICHERUNGS-/<br>RELAISKASTEN <br>UNTER DEM <br>ARMATURENBRETT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:750px;top:413px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>EPS-STEUERGERÄT<br></b>EPS-Steuergerät<br><a href=\"javascript:CtsProc('0','000000000000054','i000')\"> Ausbau/Einbau,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:75px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>SICHERUNGS-/<br>RELAISKASTEN IM MOTORRAUM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:542px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>LENKGETRIEBE<br><a href=\"javascript:CtsProc('0','000000000002094','i000')\"></b>Lenkgetriebe Ausbau und Einbau,</a><br><a href=\"javascript:CtsProc('0','000000000000044','i000')\">Ausbau/Einbau des Zahnstangenendes,</a><br><a href=\"javascript:CtsProc('0','000000000000045','i000')\">Zahnstangenführung ausbauen/einbauen,</a><br><a href=\"javascript:CtsProc('0','000000000000050','i000')\">Kugelgelenkmanschette Austausch,</a><br><a href=\"javascript:CtsProc('0','000000000000041','i000')\">Getriebe-Montagedämpfer Austausch,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:785px;top:43px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DATENÜBERTRAGUNGS-<br>STECKER (DLC)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:525px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>MOTOR<br><a href=\"javascript:CtsProc('0','000000000000055','i000')\"></b>Motor Ausbau und Einbau,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1px;top:653px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b></b>Abgebildet ist ein LHD-Modell (mit Linkslenkung). Für das RHD-Modell (mit Rechtslenkung) gilt sinngemäß das Gleiche.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}