with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:449px;\" coordsize=\"475,449\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:449px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E00J34300044051FEGD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:449px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:183px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:369px;top:72px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162px;top:369px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>RED*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:245px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:369px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:388px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:225px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:183px;top:388px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:369px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:388px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:225px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Nicht belegt<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117px;top:388px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>LT BLU*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:369px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:298px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b></b>Kabelseite der<br>weiblichen <br>Steckanschlüsse<br></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:225px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Nicht belegt<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276px;top:245px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:421px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>*: Mit klappbarem elektrisch verstellbarem Außenspiegel<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}