with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E00R31100000000YDGD55.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790px;top:150px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HINTERE STOSSDÄMPFER-<br>VERSTEIFUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:421px;top:42px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(32)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:668px;top:140px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:565px;top:34px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>UNTERES DREIECKSFENSTERBLECH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:247px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:873px;top:317px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(14)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833px;top:576px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:755px;top:576px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:669px;top:435px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:515px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RADLAUF<br>VERLÄNGERUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:695px;top:627px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:728px;top:605px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>An zwei Stellen (B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:566px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:746px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677px;top:676px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OBERE HECKSÄULENRINNE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:783px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>UNTERE HECKSÄULENRINNE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:854px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(28)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:775px;top:843px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HECKABSCHLUSSBLECH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:1074px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:1054px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>AUSSENBLECH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:936px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:859px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HINTERER KOMBINATIONSADAPTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:767px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495px;top:630px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:272px;top:716px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(27)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306px;top:695px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>An zwei Stellen (A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:689px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INNERES TRENNSTÜCK <br>AN DER B-SÄULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:18px;top:637px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>UNTERE B-SÄULEN-<br>VERSTEIFUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60px;top:461px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:28px;top:351px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ÄUSSERES TRENNSTÜCK <br>AN DER B-SÄULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:199px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(30)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:463px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628px;top:1074px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HECKSÄULENVERLÄNGERUNG<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}