with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1085px;\" coordsize=\"950,1085\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1085px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E00J32300019185EAGD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1085px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:575px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SCHLUSSLEUCHTEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:586px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:586px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>KENNZEICHENLEUCHTEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:563px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:563px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>VORDERE BEGRENZUNGSLEUCHTEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:575px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:965px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:954px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>UMGEBUNGSLEUCHTE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:954px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:862px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>HANDSCHUHFACHBELEUCHTUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:862px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:851px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:851px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MITTLERE ANZEIGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:839px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>NAVIGATIONSEINHEIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:839px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:828px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:828px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>NAVIGATIONSDISPLAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:1056px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G652: RHD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:1044px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G602: LHD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:51px;top:1044px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:1044px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G651<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:835px;top:562px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778px;top:562px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:562px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:664px;top:562px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:931px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:919px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:919px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>AUDIOGERÄT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:896px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:816px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ASCHENBECHERBELEUCHTUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:874px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:816px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:479px;top:788px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:740px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:763px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:664px;top:447px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:835px;top:447px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778px;top:447px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:447px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:508px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820px;top:508px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:762px;top:508px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:508px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:630px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:593px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736px;top:593px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765px;top:630px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:632px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>AUS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:758px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162px;top:758px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:758px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:66px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:449px;top:219px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:1044px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:376px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:178px;top:619px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>F20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:619px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>E33<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:55px;top:758px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:144px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:272px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:260px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nr. 19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:447px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>T34<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:619px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>E6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:113px;top:376px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42px;top:290px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270px;top:53px;font-weight:normal;font-size:5.47pt;\">");
write("<nobr><b>Nr. 2 (SCHEINWERFER) <br>(60 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:619px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Q12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:658px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:35px;top:219px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SICHERUNGS-/RELAISKASTEN UNTER DEM ARMATURENBRETT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156px;top:33px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SICHERUNGS−/RELAISKASTEN IM MOTORRAUM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539px;top:479px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539px;top:467px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nr. 14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:467px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nr. 15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:479px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:55px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Nr.1 (BATT) (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:86px;top:47px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BATTERIE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764px;top:697px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>KOMBINATIONSLICHTSCHALTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:763px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BELEUCHTUNG DES <br>SCHEINWERFERHÖHENVERSTELLSCHALTERS (ohne HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:740px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WARNBLINKSCHALTER-<br>BELEUCHTUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:489px;top:789px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>HEIZUNGSSTEUERGERÄT / <br>KLIMAREGLEREINHEIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:873px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LENKRADSCHALTERBELEUCHTUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:896px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BELEUCHTUNG DES SITZHEIZUNGSSCHALTERS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:931px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BELEUCHTUNG DES SCHALTERS VSA OFF (VSA AUS)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:965px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BELEUCHTUNG DES SONNENSCHUTZSCHALTERS<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}