with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E40A20326428001MAGD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:12px;top:397px;font-weight:normal;font-size:7.82pt;\">");
write("<nobr><b>Zum KRAFTSTOFFRÜCKLAUFSCHLAUCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:436px;top:410px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>KONTERMUTTER DER TANKEINHEIT<br></b>Erneuern.<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:510px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:617px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>C:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:619px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Es sollte kein Abstand vorhanden sein.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:638px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Markierung<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:878px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>90 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:624px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Sicherstellen, <br>dass die Klemme <br>wie gezeigt <br>positioniert ist.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458px;top:799px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OBERSEITE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:626px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OBERSEITE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:613px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Sicherstellen, dass die Schelle <br>sich innerhalb des dargestellten <br>Hebelbereichs in Stellung befindet.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:623px;top:655px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>90 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:414px;top:663px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>90 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:739px;top:767px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>45 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:765px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Beim Anschluss der <br>Kraftstoffzuleitung <br>die Markierungen an <br>Leitung und Stutzen <br>aufeinander ausrichten.<br></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278px;top:992px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Es darf<br>kein Spiel vorhanden sein.<br></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:841px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OBERSEITE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:1017px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>30 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715px;top:1016px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>120 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:1067px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Sicherstellen, dass die Schelle sich innerhalb <br>des dargestellten Hebelbereichs in Stellung befindet.<br></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:377px;top:112px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:103px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:154px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:112px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:112px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117px;top:449px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Zur HANDPUMPE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:337px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:258px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375px;top:510px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>B:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:540px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>90 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:553px;top:576px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>90 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:793px;top:781px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OBERSEITE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:592px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>45 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:540px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>45 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:639px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OBERSEITE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:468px;top:689px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Es darf<br>kein Spiel vorhanden sein.<br></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:788px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Markierung<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:747px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>90 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740px;top:813px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Markierung<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:946px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Sicherstellen, dass die Schelle <br>sich innerhalb des dargestellten <br>Hebelbereichs in Stellung befindet.<br></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:780px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>F:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:731px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>D:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:657px;top:731px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>E:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:1005px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>G:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:414px;top:602px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OBERSEITE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:563px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OBERSEITE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:473px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Sicherstellen, dass die Klemme<br>wie gezeigt positioniert ist.<br></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:368px;top:586px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Markierung<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:463px;top:514px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Markierung<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778px;top:970px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Markierung<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}