with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:433px;\" coordsize=\"475,433\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:433px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E80A18316217201KBGD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:433px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:32px;top:367px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Kleinerer<br>Pleuel-<br>zapfen<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302px;top:19px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Größere Pleuelfußbohrung<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:107px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Kleineres Lager (Dicker)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:149px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:202px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:257px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:311px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:65px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>1 oder I<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:65px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>2 oder II<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:64px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>3 oder III<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:64px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>4 oder IIII<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:257px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Schwarz<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:204px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Braun<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:148px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Grün<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:314px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Braun<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:313px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Blau<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:367px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Kleineres <br>Lager<br>(dicker)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:13px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Kennzeichnung<br>Pleuelfuß-<br>bohrung<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:75px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Pleuelfuß-<br>zapfen-<br>code<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:205px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Gelb<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:150px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Rosa<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:257px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Grün<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:250px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Braun/<br>Schwarz<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:197px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Grün/<br>Braun<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:143px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Gelb/<br>Grün<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:305px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Schwarz/<br>Blau<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:249px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Grün/<br>Braun<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:305px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Braun/<br>Schwarz<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:197px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Gelb/<br>Grün<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:143px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Pink/<br>Gelb<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}