with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:475px;\" coordsize=\"950,475\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:475px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7ETM000000000000EBG904.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:475px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:293px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498px;top:282px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:293px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:282px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808px;top:83px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4 : Ohne Alarmanlage<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808px;top:79px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3 : Mit Alarmanlage<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:357px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654px;top:281px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:617px;top:281px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:466px;top:281px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:281px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:350px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:335px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200px;top:335px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SRS-EINHEIT (12-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200px;top:321px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ECM (3-D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:321px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:325px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:339px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:257px;top:366px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:257px;top:352px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:257px;top:341px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:338px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU (10-D) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:257px;top:338px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:257px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:307px;top:310px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303px;top:296px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311px;top:281px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:281px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:281px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200px;top:281px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:153px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:153px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311px;top:123px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>45<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:108px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:863px;top:87px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>: Kommunikationsleitung<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275px;top:108px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:123px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175px;top:153px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INSTRUMENTENSTEUERMODUL (DREHZAHLMESSER)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:145px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:145px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:269px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:181px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808px;top:72px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1 : SICHERUNGS−/RELAISKASTEN IM MOTORRAUM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808px;top:76px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2 : SICHERUNGS−/RELAISKASTEN HINTER DEM ARMATURENBRETT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182px;top:196px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:289px;top:236px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HAUPTSCHALTKREIS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:296px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:266px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2,6 kΩ<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:239px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:239px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181px;top:165px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181px;top:175px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181px;top:186px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181px;top:160px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WARNSUMMER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:296px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:296px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:208px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DREHZAHLMESSER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:310px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>89<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:310px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:267px;top:310px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>94<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531px;top:221px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LCD-<br>ANSTEUERUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:461px;top:363px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:444px;top:363px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:616px;top:363px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544px;top:236px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HAUPTSCHALTKREIS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:554px;top:316px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499px;top:316px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:296px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612px;top:296px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:663px;top:218px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612px;top:218px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:218px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495px;top:186px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5 V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:563px;top:348px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEUCHTE (LED x 2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:303px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>96<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:555px;top:303px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>79<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:635px;top:361px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>97<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:565px;top:292px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:280px;top:218px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:19px;font-weight:normal;font-size:8.82pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:920px;top:19px;font-weight:normal;font-size:8.82pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:12px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>Instrumentensteuermodul (Drehzahlmesser)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>STEUERGERÄT <br>VON WEGFAHRSPERRE UND <br>SCHLÜSSELLOSEM <br>TÜRÖFFNUNGSSYSTEM <br>(8-A)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:211px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5 V <br>STEUER <br>SCHALTKREIS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499px;top:204px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>EIN/AUS <br>5 V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531px;top:206px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MULTI-<br>INFORMATIONSANZEIGE<br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:468px;top:211px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WEGFAHRSPERREN-<br>ANZEIGELEUCHTE <br>(LED) <br> <br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:543px;top:190px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BELEUCHTUNGSSTEUERUNG <br>UND DIMMERSCHALTKREIS <br>FÜR ZEIGER (WEISS)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:591px;top:191px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BELEUCHTUNGSSTEUERUNG <br>UND DIMMERSCHALTKREIS <br>FÜR SKALENSCHEIBE (WEISS)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:191px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BELEUCHTUNGSSTEUERUNG <br>UND DIMMERSCHALTKREIS <br>FÜR LCD (WEISS)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:316px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>KRAFTSTOFFVORRATGEBER <br><br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:639px;top:322px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>KRAFTSTOFF <br>TANK <br>EINHEIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:596px;top:256px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UMSCHALTER <br>FÜR <br>KM/H- UND <br>MPH-ANZEIGE <br> <br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:246px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HELLIGKEITSREGLER <br>FÜR <br>ARMATURENBRETTBELEUCHTUNG<br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539px;top:254px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ILLUMI <br>(Beleuchtung) <br>(−)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:254px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ILLUMI <br>(Beleuchtung) <br>(+)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:282px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU <br>(HUPENRELAIS) <br>(10-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544px;top:290px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SICHERUNG <br>Nr. 14 (7,5 A)       <br>(2-D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:360px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INFO-<br>SCHALTER<br> <br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:532px;top:359px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WAHL-/<br>RÜCKSTELL-<br>SCHALTER <br> <br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:470px;top:331px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>KABELROLLE <br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:470px;top:387px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>KABELROLLE <br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628px;top:370px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HELLIGKEITSREGLER FÜR ARMATURENBRETTBELEUCHTUNG <br>(5-B)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:468px;top:347px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WAHL-/<br>RÜCKSTELL-/<br>INFORMATIONS-<br>SCHALTER <br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:390px;top:215px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>10 V-<br>STABILISIERUNGSSCHALTKREIS <br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:243px;top:203px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ANTRIEBSSTEUERKREIS <br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320px;top:216px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HELLIGKEITS-<br>REGELKREIS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:165px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FESTSTELL<br>BREMS-<br>WARNSUMMER  <br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:175px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SICHERHEITS<br>GURT<br>WARNSUMMER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:186px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SCHLÜSSEL<br>WARNSUMMER−<br>SCHALTKREIS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:253px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>F−CAN-<br>SENDER/EMPFÄNGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:254px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>B−CAN-<br>SENDER/EMPFÄNGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:196px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FERNLICHTANZEIGELEUCHTE <br>(LED)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185px;top:196px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LICHTWARNSUMMER <br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:191px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BELEUCHTUNGSREGLER <br>UND <br>DIMMERSCHALTKREIS <br>FÜR LCD (GELB)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:371px;top:198px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ALARMANLAGEN-<br>ANZEIGELEUCHTE <br>(LED) <br> <br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:216px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLINKSTROMKREIS DER <br>ALARMANLAGENANZEIGE <br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:213px;top:203px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>KRAFTSTOFFANZEIGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:203px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TEMPERATURANZEIGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:110px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SICHERUNG <br>Nr.16 (15 A) <br>(1-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:110px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SICHERUNG <br>Nr. 10 (7,5 A) <br>(2-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:307px;top:321px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INSTRUMENTENSTEUERMODUL <br>(GESCHWINDIGKEITSMESSER) <br>(6-A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:341px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>KLIMAREGLEREINHEIT <br>(9-D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:352px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SENSOR DER AUTOMATISCHEN <br>FAHRLICHTSTEUERUNG/<br>REGENSENSOR <br>(6-D)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:366px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HFT-STEUERGERÄT <br>(14-C)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200px;top:339px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DATENÜBERTRAGUNGS-<br>STECKER <br>(3-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200px;top:325px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>VSA-STEUERGERÄT <br>(11-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200px;top:350px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>EPS-STEUERGERÄT <br>(11-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200px;top:357px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GIERWINKEL-/<br>QUERBESCHLEUNIGUNGS-<br>SENSOR <br>(11-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:293px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HUPENRELAIS <br>(12-A)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}