with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:543px;\" coordsize=\"950,543\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:543px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E80A14680800000CAGD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:543px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:47px;font-weight:normal;font-size:6.09pt;\">");
write("<nobr><b>NOCKEN FÜR NIEDRIGE DREHZAHL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:49px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>NOCKEN FÜR HOHE DREHZAHL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:40px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>FERNL.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:511px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>MOTORDREHZAHL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789px;top:513px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>FERNL.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:511px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>ABBLENDL.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:486px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>ABBLENDL.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:244px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>MOTOR-<br>BELASTUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:211px;top:444px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:432px;top:185px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:348px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:347px;top:110px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DREHMOMENTKURVE<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}