with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:447px;\" coordsize=\"950,447\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:447px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SMR7ED4E34137316775CAGD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:447px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:49px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>KUPPLUNGSLEITUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:337px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>SAC<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:123px;top:382px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>AUSRÜCKLAGER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:22px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>BEHÄLTER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789px;top:79px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>SCHNECKENRADGETRIEBE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:844px;top:180px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>SCHNECKENRAD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798px;top:328px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>GESTÄNGEMECHANISMUS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:699px;top:368px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>KUPPLUNGSSTELLANTRIEB-HUBSENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:408px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DRUCKSTANGE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:376px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>HAUPTZYLINDER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:245px;top:17px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>NEHMERZYLINDER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:33px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>AUSRÜCKGABEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642px;top:48px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>KUPPLUNGSSTELLANTRIEBMOTOR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}