with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\" coordsize=\"950,1071\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1071px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E40A18475060661KDGD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222px;top:63px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ABDECKUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:561px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 x 1,25 mm<br>22 N·m <br>(2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:148px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DICHTUNG<br></b>Erneuern.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:635px;top:278px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>AUSPUFFKRÜMMER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:142px;top:211px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SELBSTSICHERNDE MUTTER<br>10 x 1,25 mm<br>44 N·m (4,5 kgf·m)<br></b>Erneuern.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:700px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DICHTUNG<br></b>Erneuern.<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:307px;top:512px;font-weight:normal;font-size:8.51pt;\">");
write("<nobr><b>UNTERLEGSCHEIBEN<br></b>Erneuern.<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:750px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DICHTSCHRAUBE<br>12 x 1,25 mm<br>28 N·m <br>(2,9 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:850px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TURBOLADER-BAUGRUPPE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:257px;top:931px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>10 x 1,25 mm<br>59 N·m <br>(6,0 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:361px;top:1013px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>10 x 1,25 mm<br>44 N·m <br>(4,5 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:647px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>LUFTLEITUNG A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643px;top:1011px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 x 1,0 mm<br>12 N·m <br>(1,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:753px;top:980px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>12 x 1,25 mm<br>44 N·m <br>(4,5 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:908px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>UNTERLEGSCHEIBEN<br></b>Erneuern.<br></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:749px;top:711px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DICHTUNGEN<br></b>Erneuern.<br></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798px;top:802px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ÖL-BYPASS-LEITUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:992px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TURBOLADERHALTERUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:423px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 x 1,0 mm<br>12 N·m <br>(1,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118px;top:291px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>10 x 1,25 mm<br>44 N·m <br>(4,5 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:664px;top:320px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DICHTUNG<br></b>Erneuern.<br></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495px;top:18px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 x 1,25 mm<br>22 N·m <br>(2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}