with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:975px;\" coordsize=\"950,975\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:975px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E40A14400049001KBGD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:975px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:244px;top:118px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OBERER KÜHLERSCHLAUCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:557px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>KÜHLERLÜFTERMOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:24px;top:387px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>KÜHLERLÜFTERVERKLEIDUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:103px;top:864px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A/C-KONDENSATORLÜFTER-/<br>VERKLEIDUNGSBAUGRUPPE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:433px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ECT-SENSOR 2 (KÜHLMITTELTEMPERATUR) <br><br>12 N·m (1,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:682px;top:82px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>O-RING<br></b>Erneuern.<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812px;top:282px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>KÜHLER-<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:771px;top:571px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>O-RING<br></b>Erneuern.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:452px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>UNTERER DÄMPFER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736px;top:627px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ABLASS-SCHRAUBE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615px;top:706px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>UNTERER KÜHLERSCHLAUCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:618px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 x 1,0 mm<br>7 N·m <br>(0,7 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:747px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6,0 N·m <br>(0,61 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:190px;top:159px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>KÜHLERLÜFTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:98px;top:264px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 x 1,0 mm<br>7 N·m <br>(0,7 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339px;top:77px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SCHNELLKUPPLUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:733px;top:166px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OBERE HALTERUNG UND DÄMPFER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687px;top:665px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SCHNELLKUPPLUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156px;top:208px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>3,9 N·m <br>(0,4 kgf·m)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}