with(document) {
write("<v:group id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/SMR7ET0000000000000EBG305.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:339px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:205px;top:582px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:848px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206px;top:702px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:582px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-59px;top:440px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ANZEIGE-ANSTEUERUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-39px;top:471px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HAUPTSCHALTKREIS<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:145px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*2 : SICHERUNGS−/RELAISKASTEN HINTER DEM ARMATURENBRETT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:138px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*1 : SICHERUNGS−/RELAISKASTEN IM MOTORRAUM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:562px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:562px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:152px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*3 : Mit Alarmanlage<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:159px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4 : Ohne Alarmanlage<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LADESYSTEMLEUCHTE <br>(LED) <br><br><br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:376px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ÖLDRUCK <br>WARN <br>ANZEIGE <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:209px;top:412px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SICHERHEITSGURT- <br>ANZEIGELEUCHTE <br> (LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:395px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>BREMSANLAGENLEUCHTE <br>(LED) <br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:384px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>SCHEINWERFER- <br>ANZEIGE <br>(LED) <br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:319px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DIMMERSCHALTKREIS FÜR LICHT-/<br>NEBELSCHEINWERFERANZEIGE <br>(5-A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:379px;top:368px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>NEBELSCHEINWERFERANZEIGELEUCHTE <br>(LED) <br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:409px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>NEBELSCHLUSSLEUCHTENANZEIGE <br>(LED) <br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:647px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BREMSFLÜSSIGKEITSSTAND-<br>SCHALTER (Geschlossen :<br>Schwimmer unten) <br>(Offen: <br>Schwimmer oben)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:647px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FESTSTELLBREMSSCHALTER <br>(Geschlossen:<br>Hebel gezogen)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-43px;top:378px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VSA-<br>ANZEIGE (LED) <br> <br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119px;top:411px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SRS-<br>ANZEIGELEUCHTE <br>(LED)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:378px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ABS-<br>ANZEIGELEUCHTE <br>(LED) <br> <br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-49px;top:665px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SCHALTER VSA AUS<br><br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-111px;top:767px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HELLIGKEITSREGLER FÜR ARMATURENBRETTBELEUCHTUNG <br>(5-B)<br><br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}