with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9EQP000000000000EBG110.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:693px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:804px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:857px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:693px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276px;top:857px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:804px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:804px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:613px;top:857px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G652<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:616px;top:804px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:804px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:693px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:693px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278px;top:626px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278px;top:693px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:540px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(Außer Modell KS)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:559px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:539px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(Modell KS)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:626px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:693px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:693px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:717px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:748px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:717px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:748px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:717px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:748px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457px;top:717px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457px;top:748px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:717px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:748px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443px;top:863px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[G603]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:445px;top:857px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G651<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615px;top:693px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:693px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:748px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:717px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:804px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:764px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:717px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:748px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:764px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:857px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G603<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:554px;top:863px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[G603]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:555px;top:857px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G651<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:587px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>142<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:587px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>73<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:267px;top:559px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SICHERUNG <br>Nr. 15 (7,5 A) <br>(3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:568px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>TAGFAHRLEUCHTENRELAIS <br>(15−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:760px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>BEGRENZUNGSLEUCHTE <br>VORN LINKS <br>(5 W) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:783px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>BEGRENZUNGSLEUCHTE <br>VORN RECHTS <br>(5 W) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:756px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LINKE <br>SCHLUSSLEUCHTE <br>(DECKELLEUCHTE) <br>(5 W) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:771px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>RECHTE <br>SCHLUSSLEUCHTE <br>(DECKELLEUCHTE) <br>(5 W) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:623px;top:758px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>KENNZEICHENLEUCHTE <br>(5 W x 2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:572px;top:755px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>RECHTE <br>(INNERE) <br>SCHLUSSLEUCHTE <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:713px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LINKE <br>(INNERE) <br>SCHLUSSLEUCHTE <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:24px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:23px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>Nebelleuchten, Innenraumbeleuchtung, Rückfahrscheinwerfer, Schlussleuchten, Kennzeichenleuchten, Blinker/Warnblinker, Bremsleuchten, Begrenzungsleuchten vorn, Warnblinkschalter, Heckscheibenheizung<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182px;top:251px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182px;top:282px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:616px;top:304px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:616px;top:238px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:147px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:156px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:347px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:405px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:322px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:211px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:255px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SCHLIESSEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:220px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ÖFFNEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:347px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:347px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:220px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ÖFFNEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:433px;top:255px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SCHLIESSEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417px;top:211px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417px;top:322px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:480px;top:458px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170px;top:458px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G651<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:347px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:478px;top:147px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:86px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:464px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[G603]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:183px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:183px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:239px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:362px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:331px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284px;top:331px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284px;top:362px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329px;top:458px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:405px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274px;top:405px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:272px;top:458px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357px;top:86px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:273px;top:307px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:307px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:86px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:147px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:183px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:478px;top:183px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:193px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:193px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:242px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:242px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:183px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:387px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:117px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>117<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:117px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>53<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:276px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:485px;top:117px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:117px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>72<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:409px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>88<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181px;top:294px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>NEBELSCHLUSSLEUCHTE<br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:89px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SICHERUNG <br>Nr. 17 (7,5 A)<br>(1−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:98px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MICU <br>(15−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284px;top:376px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>NEBELSCHEINWERFER <br>LINKS (55 W) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:335px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>NEBELSCHEINWERFER <br>RECHTS (55 W) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:89px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SICHERUNG <br>Nr. 6 (20 A) <br>(3−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:308px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MICU <br>(15−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:207px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>NEBELSCHEINWERFER-<br>RELAIS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:278px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>KOSMETIKSPIEGELLEUCHTE <br>FAHRERSEITE <br>(2 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:292px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>KOSMETIKSPIEGELLEUCHTE <br>BEIFAHRERSEITE <br>(2 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:596px;top:89px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SICHERUNG <br>Nr. 14 (7,5 A) <br>(3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:616px;top:314px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>UMGEBUNGSLEUCHTE <br>(LED)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:591px;top:432px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HELLIGKEITSREGLER FÜR <br>ARMATURENBRETTBELEUCHTUNG <br>(8−A)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}