with(document) {
write("<v:group id=\"group5\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:591px;\" coordsize=\"950,591\">");
write("<v:rect id=\"rect5\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:591px;\">");
write("<img id=\"img5\" name=\"PrtImgId\" src=\"../img/SMR9ER3E34137300000CAGD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:591px;border-color:#ffffff\">");
write("<p id=\"p5_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:81px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>100 ‰<br></b></nobr>");
write("</p>");
write("<p id=\"p5_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:271px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p5_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:478px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>0<br></b></nobr>");
write("</p>");
write("<p id=\"p5_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:12px;top:243px;font-weight:normal;font-size:7.55pt;\">");
write("<nobr><b>Drosselklappenöffnung<br></b></nobr>");
write("</p>");
write("<p id=\"p5_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737px;top:520px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>: Normalmodus<br></b></nobr>");
write("</p>");
write("<p id=\"p5_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737px;top:552px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>: S-Modus<br></b></nobr>");
write("</p>");
write("<p id=\"p5_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:64px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>2. GANG<br></b></nobr>");
write("</p>");
write("<p id=\"p5_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:64px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>3. GANG<br></b></nobr>");
write("</p>");
write("<p id=\"p5_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659px;top:65px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>4.<br></b></nobr>");
write("</p>");
write("<p id=\"p5_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:786px;top:64px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>5.<br></b></nobr>");
write("</p>");
write("<p id=\"p5_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:922px;top:65px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>6TH<br></b></nobr>");
write("</p>");
write("<p id=\"p5_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457px;top:481px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>62 mph (100 km/h)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:829px;top:482px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Geschwindigkeit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:64px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>2. GANG<br></b></nobr>");
write("</p>");
write("<p id=\"p5_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:65px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>3. GANG<br></b></nobr>");
write("</p>");
write("<p id=\"p5_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715px;top:65px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>4.<br></b></nobr>");
write("</p>");
write("<p id=\"p5_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:853px;top:65px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>5.<br></b></nobr>");
write("</p>");
write("<p id=\"p5_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:64px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>1.<br></b></nobr>");
write("</p>");
write("<p id=\"p5_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:17px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>AUTO MODUS: Hochschaltmuster<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}