with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:256px;\" coordsize=\"475,256\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:256px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9EQPJ36200000000BBGD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:256px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60px;top:38px;font-weight:normal;font-size:6.65pt;\">");
write("<nobr><b>System-Verbindungen<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:76px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>Radio<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201px;top:35px;font-weight:normal;font-size:8.33pt;\">");
write("<nobr><b>Hilfe<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274px;top:32px;font-weight:normal;font-size:6.65pt;\">");
write("<nobr><b>Diagnose <br>verlassen<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:35px;font-weight:normal;font-size:8.33pt;\">");
write("<nobr><b>Zurück<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:35px;font-weight:normal;font-size:8.33pt;\">");
write("<nobr><b>Zurück<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135px;top:114px;font-weight:normal;font-size:8.33pt;\">");
write("<nobr><b>Navi.ECU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:76px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>TMC-Ant.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:245px;top:76px;font-weight:normal;font-size:5.24pt;\">");
write("<nobr><b>KLIMAANLAGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:117px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>Display<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:158px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>Heckkamera<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60px;top:199px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>GPS-Ant.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:155px;top:148px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>Fehler<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156px;top:158px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>Archiv<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154px;top:181px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>Gierwinkel<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:192px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>Sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:154px;font-weight:normal;font-size:5.24pt;\">");
write("<nobr><b>Fahrzeugstatus<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:188px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>ECU-Info<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:290px;top:155px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>Taste<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293px;top:188px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>DVD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:117px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>Mik<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:199px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>HFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:146px;top:219px;font-weight:normal;font-size:5.78pt;\">");
write("<nobr><b>Wählen Sie ein Symbol aus, um die Details zu sehen.<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}