with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:417px;\" coordsize=\"475,417\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:417px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9EQPK735000Y1776FAGD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:417px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:125px;top:50px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b></b>Kabelseite der Steckanschlüsse (weiblich)<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:143px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>HFT-NAVI<br>MIC+ (GRN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:118px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>HFT-<br>NAVI<br>MIC−<br>(RED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:214px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>HFT-NAVI<br>MIC+ (GRN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:324px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>HFT-NAVI<br>MIC− (RED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:371px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>NAVIGATIONSEINHEIT, STECKER C (16P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:388px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b></b>Kabelseite der Steckanschlüsse (weiblich)<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76px;top:18px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>HFT-STEUERGERÄT, <br>28P-STECKER<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}