with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:475px;\" coordsize=\"950,475\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:475px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9ERP000000000000EBG902.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:475px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:12px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>Sicherungs-/Relaiskasten unter dem Armaturenbrett, Zündanlage<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:920px;top:19px;font-weight:normal;font-size:8.82pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:19px;font-weight:normal;font-size:8.82pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:352px;top:275px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Innenverbindung)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:343px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>IG2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:105px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:218px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ANLASSER (3-D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:358px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:271px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:334px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:326px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133px;top:315px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>AUS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:334px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120px;top:306px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ZÜNDSCHALTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284px;top:391px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:257px;top:391px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:399px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ANLASSERSCHALTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:371px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Nr. 8 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:376px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117px;top:76px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:241px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:252px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>AUDIOGERÄT (16−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MULTIFUNKTIONSCONTROLLER (16−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:244px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:252px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:262px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>NAVIGATIONSDISPLAY (17−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:259px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>NAVIGATIONSEINHEIT (17−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:370px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:154px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:194px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G403<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:174px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:154px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:388px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:280px;top:388px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:175px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:39px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:811px;top:39px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:814px;top:39px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SICHERUNGS−/RELAISKASTEN IM MOTORRAUM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:814px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SICHERUNGS-/RELAISKASTEN UNTER DEM ARMATURENBRETT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:811px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:271px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:114px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:193px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:193px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:376px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:155px;top:233px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Nr. 35 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:233px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:238px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:409px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270px;top:152px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:213px;top:174px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:213px;top:136px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:136px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270px;top:114px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:174px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:114px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:361px;top:391px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:218px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:178px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:154px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ECM (4−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:218px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:243px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:215px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:235px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:215px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:239px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:238px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:213px;top:218px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:278px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU (13−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:266px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>STEUERGERÄT DER FREISPRECHEINRICHTUNG (17−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:244px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ZIGARETTENANZÜNDERRELAIS (11−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:259px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:266px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:241px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELAIS HINTERE ZUSATZSTROMBUCHSE (11−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELAIS VORDERE ZUBEHÖRSTROMBUCHSE (11−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:262px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:327px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:307px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:331px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:303px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:323px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:303px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:328px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:213px;top:307px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:271px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:391px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ECM (4−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:361px;top:114px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:114px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ECM (4−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:109px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 23 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:109px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:331px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:330px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:337px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SCHALTER FÜR ELEKTRISCH VERSTELLBARE AUSSENSPIEGEL (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:330px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SICHERUNGS-/RELAISKASTEN IM MOTORRAUM (1-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:333px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:326px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Nr. 36 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:326px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:337px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:344px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HEIZUNGSSTEUERGERÄT / KLIMAREGLEREINHEIT (12−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:333px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HEIZUNGSRELAIS ELEKTRISCH VERSTELLBARE AUSSENSPIEGEL (10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:340px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:340px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SITZHEIZUNGSSCHALTER (11−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:344px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:362px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Nr. 37 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:361px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:352px;top:363px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Innenverbindung)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:286px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:366px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:391px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:347px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HVAC-UNTERANZEIGE (12−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:347px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665px;top:243px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:131px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SCHEINWERFERHÖHENVERSTELLSCHALTER (ohne HID) (7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:128px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>STEUEREINHEIT DER AUTOMATISCHEN SCHEINWERFERHÖHENVERSTELLUNG (mit HID) (7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SENSOR DER AUTOMATISCHEN FAHRLICHTSTEUERUNG/REGENSENSOR (7−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:156px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TEMPERATURREGELSCHALTER BEIFAHRERSEITE (12−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:146px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FENSTERHEBER-HAUPTSCHALTER (9−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665px;top:167px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:162px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Nr. 2 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:149px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SCHALTERBELEUCHTUNG FÜR ELEKTRISCH VERSTELLBARE AUSSENSPIEGEL (10−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:135px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RECHTER SCHEINWERFERHÖHENVERSTELLMOTOR (ohne HID) (7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:138px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LINKER SCHEINWERFERHÖHENVERSTELLMOTOR (ohne HID) (7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:125px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Nr. 1 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665px;top:130px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665px;top:205px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:200px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Nr. 3 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:393px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU (IG1 WIPER 2) (13−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654px;top:390px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Innenverbindung)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:389px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Nr. 38 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:356px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SRS-EINHEIT (VB) (15−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665px;top:356px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:351px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Nr. 11 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:313px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Nr. 10 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:663px;top:318px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:238px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Nr. 4 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:124px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:128px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:131px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:138px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:135px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:149px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:153px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:146px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:169px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:165px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:162px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:200px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:244px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:241px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:241px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>VSA-STEUERGERÄT (14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>EPS-STEUERGERÄT (14−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:244px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GIERRATEN-/QUERBESCHLEUNIGUNGSSENSOR (14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:237px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:280px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SRS-EINHEIT (VA) (15−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665px;top:280px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Nr. 9 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:275px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:323px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RÜCKFAHRSCHEINWERFERSCHALTER (8−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:334px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU (13−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:316px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INSTRUMENTENSTEUERMODUL (DREHZAHLMESSER) (5−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:320px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INSTRUMENTENSTEUERMODUL (GESCHWINDIGKEITSMESSER) (7−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:316px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:320px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:327px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:323px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:585px;top:313px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:585px;top:350px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:585px;top:388px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:210px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MAF-SENSOR / IAT-SENSOR (4−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:203px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ELD (1−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:203px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:210px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:214px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BREMSPEDALSTELLUNGSSCHALTER (8−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:214px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LICHTMASCHINE (3−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:153px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>AUTOMATISCH ABBLENDENDER INNENSPIEGEL(11−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:156px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:330px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:330px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>STEUERGERÄT EINPARK- und RÜCKFAHRSENSOREN (10−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:334px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:327px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>EINPARK-/RÜCKFAHRSENSOR-AUSSCHALTER (10−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:169px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>STEUERGERÄT FÜR WEGFAHRSPERRE UND SCHLÜSSELLOSES TÜRÖFFNUNGSSYSTEM (10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:165px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ECM (4−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:366px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU (DAY LT) (Modell KS) (13−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:369px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:369px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TAGFAHRLICHTRELAIS (13−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108px;top:90px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:114px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p1_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:154px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>41<br></b></nobr>");
write("</p>");
write("<p id=\"p1_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:218px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>42<br></b></nobr>");
write("</p>");
write("<p id=\"p1_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:243px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>43<br></b></nobr>");
write("</p>");
write("<p id=\"p1_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:278px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>44<br></b></nobr>");
write("</p>");
write("<p id=\"p1_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:332px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>45<br></b></nobr>");
write("</p>");
write("<p id=\"p1_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:367px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>46<br></b></nobr>");
write("</p>");
write("<p id=\"p1_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:391px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>47<br></b></nobr>");
write("</p>");
write("<p id=\"p1_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:130px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>48<br></b></nobr>");
write("</p>");
write("<p id=\"p1_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:168px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>49<br></b></nobr>");
write("</p>");
write("<p id=\"p1_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:205px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p1_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:243px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>51<br></b></nobr>");
write("</p>");
write("<p id=\"p1_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:281px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>52<br></b></nobr>");
write("</p>");
write("<p id=\"p1_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:318px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>53<br></b></nobr>");
write("</p>");
write("<p id=\"p1_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:356px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>54<br></b></nobr>");
write("</p>");
write("<p id=\"p1_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:394px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>55<br></b></nobr>");
write("</p>");
write("<p id=\"p1_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:100px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ANLASSER-TRENNRELAIS 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:102px;top:73px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SICHERUNG Nr. 2 (ZÜNDUNG) (50 A) <br><br><br>(1−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324px;top:143px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SICHERHEITSRELAIS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:163px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ANLASSER-TRENNRELAIS 2 <br></b></nobr>");
write("</p>");
write("<p id=\"p1_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ACC-TRENNRELAIS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:295px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TRENNRELAIS <br>IG2<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}