with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:475px;\" coordsize=\"950,475\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:475px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9EQP000000000000EBG907.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:475px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:19px;font-weight:normal;font-size:8.82pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:920px;top:19px;font-weight:normal;font-size:8.82pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:12px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>Instrumentensteuermodul (Drehzahlmesser), Tempomat<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:52px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:100px;top:169px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DREHZAHLMESSER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302px;top:113px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:113px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:256px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:98px;top:242px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:242px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111px;top:256px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111px;top:119px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WARNSUMMER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111px;top:146px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111px;top:139px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111px;top:131px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:199px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:199px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:100px;top:226px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>124 Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:144px;top:256px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:149px;top:242px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302px;top:242px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:256px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:289px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:282px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:317px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU (15−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:196px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HAUPTSCHALTKREIS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:280px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:314px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:321px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:339px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SRS-EINHEIT (17−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111px;top:153px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:306px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:332px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:317px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:113px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INSTRUMENTENSTEUERMODUL (DREHZAHLMESSER)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:179px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:321px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:306px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:310px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:339px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:94px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:94px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111px;top:124px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:266px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:299px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:242px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:371px;top:242px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:296px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:147px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:390px;top:256px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:256px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:52px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:294px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:298px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:301px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495px;top:155px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5 V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:179px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:595px;top:179px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688px;top:179px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:448px;top:242px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:433px;top:242px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544px;top:323px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:489px;top:323px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:378px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:378px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:378px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:547px;top:414px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:183px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LCD-STEUERUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:641px;top:179px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443px;top:256px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:426px;top:256px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:250px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:785px;top:250px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:772px;top:242px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790px;top:242px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:752px;top:242px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:759px;top:196px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HAUPTSCHALTKREIS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722px;top:168px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:811px;top:130px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:811px;top:230px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560px;top:250px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642px;top:351px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEUCHTEN-<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586px;top:438px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G403<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659px;top:414px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:692px;top:414px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:414px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:414px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:676px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:585px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:662px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:683px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:662px;top:251px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:697px;top:250px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812px;top:41px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:41px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821px;top:41px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SICHERUNGS−/RELAISKASTEN IM MOTORRAUM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821px;top:45px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SICHERUNGS-/RELAISKASTEN UNTER DEM ARMATURENBRETT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:45px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812px;top:45px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812px;top:48px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:48px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:52px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812px;top:52px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812px;top:55px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:55px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821px;top:59px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Motor R18A2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821px;top:62px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Motor L13Z1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:59px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812px;top:59px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821px;top:52px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Mit Einparkhilfe<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:655px;top:378px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:686px;top:378px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:378px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:585px;top:378px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:323px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:323px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:323px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665px;top:251px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HUPENRELAIS (13−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU (15−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638px;top:250px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:309px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:62px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812px;top:62px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812px;top:66px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:66px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821px;top:66px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Mit Alarmanlage<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821px;top:69px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Ohne Alarmanlage<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:69px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812px;top:69px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821px;top:48px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Mit i-SHIFT-System<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:79px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:79px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Andere Datenübertragungsleitung<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CAN-Leitung<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:549px;top:261px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>72<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:626px;top:261px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>72<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677px;top:261px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>101<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:549px;top:425px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>85<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:626px;top:425px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>85<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:199px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UART<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>82<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>83<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>98<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298px;top:270px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>84<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298px;top:66px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>49<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:66px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:299px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:331px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:103px;top:339px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821px;top:55px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Motor K20Z4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:305px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:82px;top:284px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:82px;top:288px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:82px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:52px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SICHERUNG <br>Nr. 16 (15 A)<br>(1−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303px;top:177px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HELLIGKEITS-<br>REGELKREIS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:132px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FESTSTELLBREMSEN-<br>WARNSUMMER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:139px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SICHERHEITSGURTWARNSUMMER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:146px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SCHLÜSSEL<br>WARNSUMMER−SCHALTKREIS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:212px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>F−CAN-<br>SENDER/<br>EMPFÄNGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:212px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>B−CAN-<br>SENDER/<br>EMPFÄNGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:289px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>STEUERGERÄT VON WEGFAHRSPERRE <br>UND SCHLÜSSELLOSEM TÜRÖFFNUNGSSYSTEM (12−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278px;top:279px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INSTRUMENTENSTEUERMODUL <br>(GESCHWINDIGKEITSMESSER) (9−A)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:176px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>10 V-<br>STABILISIERUNGSSCHALTKREIS <br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FERNLICHTANZEIGELEUCHTE (LED)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:314px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>VSA-STEUERGERÄT<br>(16-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:294px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DATENÜBERTRAGUNGSSTECKER <br>(4−D) <br>(6−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:153px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LICHTWARNSUMMER <br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:306px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HEIZUNGSSTEUERGERÄT / KLIMAREGLEREINHEIT (14−C)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:243px;top:151px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BELEUCHTUNGSREGLER UND <br>DIMMERSCHALTKREIS FÜR LCD <br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:351px;top:160px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ALARMANLAGEN-ANZEIGELEUCHTE (LED) <br> <br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329px;top:176px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLINKSTROMKREIS DER <br>ALARMANLAGENANZEIGE <br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:332px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>EPS-STEUERGERÄT (16−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:282px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SENSOR DER AUTOMATISCHEN <br>BELEUCHTUNGSREGELUNG / REGENSENSOR (11−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:164px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>KRAFTSTOFFANZEIGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:321px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>STEUERGERÄT DER FREISPRECHEINRICHTUNG (19−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:306px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GETRIEBESTEUERGERÄT (TCM) (16−A)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:321px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GIERRATEN-/<br>QUERBESCHLEUNIGUNGSSENSOR (16−C)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:125px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WARNSUMMER VSA AUS-SCHALTER <br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:268px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>KRAFTSTOFFVORRATGEBER <br><br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399px;top:262px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TANKEINHEIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:296px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>STEUERGERÄT FÜR EINPARKHILFE-/RÜCKFAHRSENSOR  <br>(12−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:183px;top:167px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WARNSUMMER <br>(FÜR <br>PARKSENSOR)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:52px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SICHERUNG <br>Nr. 10 (7,5 A) <br>(3−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488px;top:173px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5 V <br>STEUER <br>SCHALTKREIS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:477px;top:165px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>EIN/AUS <br>5 V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:167px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MULTI-INFORMATIONSANZEIGE<br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:144px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WEGFAHRSPERREN-ANZEIGELEUCHTE (LED) <br> <br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522px;top:151px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BELEUCHTUNGSSTEUERUNG UND <br>DIMMERSCHALTKREIS <br>FÜR ZEIGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BELEUCHTUNGSSTEUERUNG UND <br>DIMMERSCHALTKREIS <br>FÜR ANZEIGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:662px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BELEUCHTUNGSSTEUERUNG UND <br>DIMMERSCHALTKREIS <br>FÜR ILM-KODIERER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:212px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UMSCHALTER FÜR <br>KM/H- UND MPH-ANZEIGE <br> <br></b></nobr>");
write("</p>");
write("<p id=\"p1_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:233px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HELLIGKEITSREGLER FÜR <br>ARMATURENBRETTBELEUCHTUNG<br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:214px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ILLUMI <br>(Beleuchtung) <br>(−)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544px;top:218px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ILLUMI <br>(Beleuchtung) <br>(+)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540px;top:251px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SICHERUNG <br>Nr. 14 (7,5 A) (3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:355px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INFO-<br>SCHALTER<br> <br></b></nobr>");
write("</p>");
write("<p id=\"p1_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:524px;top:364px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WAHL-/<br>RÜCKSTELLSCHALTER <br> <br></b></nobr>");
write("</p>");
write("<p id=\"p1_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:524px;top:434px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HELLIGKEITSREGLER FÜR <br>ARMATURENBRETTBELEUCHTUNG <br>(8−B)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:339px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WAHL-/RÜCKSTELL-/<br>INFORMATIONSSCHALTER <br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:616px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BELEUCHTUNGSREGELUNG UND <br>DIMMERSCHALTKREIS <br>FÜR LCD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717px;top:152px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ANZEIGEN-<br>DIMMERSCHALTKREIS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:755px;top:171px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TEMPOMATANZEIGE<br><br><br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:785px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TEMPOMAT-<br>HAUPTANZEIGE (LED) <br> <br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ABSCHALT-ANZEIGE FÜR <br>SEITENAIRBAG (LED) <br> <br> <br></b></nobr>");
write("</p>");
write("<p id=\"p1_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715px;top:178px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ANZEIGEN <br>(7−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:592px;top:363px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TEMPOMAT-<br>HAUPTSCHALTER<br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:334px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>{EINSTELLEN/ <br>}VERZÖGERUNG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:395px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>KABELROLLE <br></b></nobr>");
write("</p>");
write("<p id=\"p1_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698px;top:351px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RES/<br>ACCEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:678px;top:351px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ABBRUCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:712px;top:346px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TEMPOMAT-KOMBISCHALTER<br><br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:610px;top:435px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HELLIGKEITSREGLER FÜR <br>ARMATURENBRETTBELEUCHTUNG <br>(8−B)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>KABELROLLE <br></b></nobr>");
write("</p>");
write("<p id=\"p1_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:618px;top:251px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SICHERUNG <br>Nr. 14 (7,5 A) (3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:310px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SCHALTSTEUERGERÄT (16−A)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p1_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:280px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ECM <br>(4−D) <br>(5−D) <br>(6−D)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}