with(document) {
write("<v:group id=\"group4\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1023px;\" coordsize=\"950,1023\">");
write("<v:rect id=\"rect4\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1023px;\">");
write("<img id=\"img4\" name=\"PrtImgId\" src=\"../img/SMR9EQ1A20300000000DBGD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1023px;border-color:#ffffff\">");
write("<p id=\"p4_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:53px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>EINSPRITZVENTIL Nr. 4 (1)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p4_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498px;top:216px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>LICHTMASCHINE<br>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:218px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ÖLDRUCKSCHALTER (6)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p4_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:53px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CKP-SENSOR<br>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:51px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>MOTORÖLSTANDSENSOR<br> (3)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604px;top:50px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>3P-STECKER<br>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:51px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>EINSPRITZVENTIL Nr. 3 (5)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p4_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:232px;top:215px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>KLOPF-<br>SENSOR<br>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789px;top:217px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>EGR-VENTIL<br>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:216px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>EINSPRITZVENTIL Nr. 2 (8)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p4_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:216px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>EINSPRITZVENTIL Nr. 1 (10)<br><br></b></nobr>");
write("</p>");
write("<p id=\"p4_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:361px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>HINWEIS:<br> Steckanschlüsse (männlich) (doppelter Strich): Sicht von der Anschluss-Seite<br>·Steckanschlüsse (weiblich) (einfacher Strich): Sicht von der Kabelseite<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}