with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:543px;\" coordsize=\"950,543\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:543px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9EQDE34137300000CAGD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:543px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:179px;top:62px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>INSTRUMENTENSTEUERMODUL <br>(GESCHWINDIGKEITSMESSER)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:116px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>INSTRUMENTENSTEUERMODUL <br>(DREHZAHLMESSER)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:6px;top:457px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>VSA-STEUERGERÄT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:379px;top:515px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>TCM (Kupplungsstellantrieb)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:489px;top:484px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>MOTORSTEUERGERÄT (ECM)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:500px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>GANGWECHSELSTELLANTIEB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615px;top:15px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>LENKRAD-SCHALTTASTEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:19px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>SCHALTSTEUERGERÄT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}