with(document) {
write("<v:group id=\"group6\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:927px;\" coordsize=\"950,927\">");
write("<v:rect id=\"rect6\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:927px;\">");
write("<img id=\"img6\" name=\"PrtImgId\" src=\"../img/SMR7EG0J54230100000EAPD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:927px;border-color:#ffffff\">");
write("<p id=\"p6_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:702px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:702px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p6_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:631px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:631px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p6_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:74px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p6_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:74px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:888px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>U<br></b></nobr>");
write("</p>");
write("<p id=\"p6_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:888px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Cablagem do ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p6_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:121px;top:887px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p6_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550px;top:858px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p6_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:860px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Cablagem da porta do passageiro<br></b></nobr>");
write("</p>");
write("<p id=\"p6_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:532px;top:859px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p6_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:317px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ECM (PG)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:288px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ECM (PG)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:260px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ECM (PG)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:231px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Ficha de análise de dados<br></b></nobr>");
write("</p>");
write("<p id=\"p6_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:202px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Unidade de controlo do imobilizador−sistema de <br>trancar/destrancar portas sem chave<br></b></nobr>");
write("</p>");
write("<p id=\"p6_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:260px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:288px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:317px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:317px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:316px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p6_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:316px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>U<br></b></nobr>");
write("</p>");
write("<p id=\"p6_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:288px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>U<br></b></nobr>");
write("</p>");
write("<p id=\"p6_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:288px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p6_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:288px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:260px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:259px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p6_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:259px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>U<br></b></nobr>");
write("</p>");
write("<p id=\"p6_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:231px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:231px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p6_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:202px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p6_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:202px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418px;top:202px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p6_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:449px;top:202px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p6_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320px;top:859px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p6_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:73px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p6_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p6_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:595px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:595px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p6_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:595px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Relé do isqueiro<br></b></nobr>");
write("</p>");
write("<p id=\"p6_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:610px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Relé da tomada de alimentação para acessórios<br></b></nobr>");
write("</p>");
write("<p id=\"p6_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:52px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Actuador da super fechadura do passageiro<br></b></nobr>");
write("</p>");
write("<p id=\"p6_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:860px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Cablagem do interruptor combinado<br></b></nobr>");
write("</p>");
write("<p id=\"p6_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:858px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p6_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:574px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Unidade de visualização da navegação<br></b></nobr>");
write("</p>");
write("<p id=\"p6_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:131px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Motor do vidro eléctrico do passageiro<br></b></nobr>");
write("</p>");
write("<p id=\"p6_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:445px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Módulo de controlo do indicador (Conta-rotações)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:445px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:445px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p6_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:531px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:531px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p6_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:474px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p6_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:474px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:74px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:691px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Tomada da caixa de fusíveis/relés)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:702px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p6_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:631px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p6_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:211px;top:631px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:417px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Unidade de controlo do nivelamento dos faróis<br></b></nobr>");
write("</p>");
write("<p id=\"p6_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:416px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p6_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:417px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:738px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p6_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:502px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Unidade do visor secundário áudio HVAC<br></b></nobr>");
write("</p>");
write("<p id=\"p6_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:606px;top:530px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Unidade de controlo do aquecedor/unidade de controlo da climatização<br></b></nobr>");
write("</p>");
write("<p id=\"p6_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:560px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Indicador de interface<br></b></nobr>");
write("</p>");
write("<p id=\"p6_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:502px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:502px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p6_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:559px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p6_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:560px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:631px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Ficha de análise de dados<br></b></nobr>");
write("</p>");
write("<p id=\"p6_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:474px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Módulo de controlo do indicador (Velocímetro)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:74px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruptor do vidro eléctrico do passageiro<br></b></nobr>");
write("</p>");
write("<p id=\"p6_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:174px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Módulo de controlo do indicador (Conta-rotações)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:174px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p6_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:174px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:145px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Actuador da tranca da porta do passageiro<br></b></nobr>");
write("</p>");
write("<p id=\"p6_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:117px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Luz dos piscas de direcção esquerdos<br></b></nobr>");
write("</p>");
write("<p id=\"p6_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:102px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruptor do A/C da porta do passageiro<br></b></nobr>");
write("</p>");
write("<p id=\"p6_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:88px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Desembaciador do espelho retrovisor eléctrico esquerdo<br></b></nobr>");
write("</p>");
write("<p id=\"p6_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:388px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G502<br></b></nobr>");
write("</p>");
write("<p id=\"p6_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p6_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruptor do vidro eléctrico do passageiro<br></b></nobr>");
write("</p>");
write("<p id=\"p6_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:121px;top:858px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p6_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:860px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Cablagem do tablier<br></b></nobr>");
write("</p>");
write("<p id=\"p6_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:859px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p6_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:657px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>CAIXA DE FUSÍVEIS/<br>RELÉS SOB O TABLIER<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}