with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:559px;\" coordsize=\"950,559\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:559px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7ET0A20323400000CAPD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:559px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:383px;top:185px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ATMOSFERA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:166px;font-weight:normal;font-size:5.54pt;\">");
write("<nobr><b>TAMPÃO <br>DE ENCHIMENTO DO<br>COMBUSTÍVEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:8px;top:34px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>VÁLVULA DE <br>SEPARAÇÃO DO LÍQUIDO/VAPOR <br>DO DEPÓSITO DE COMBUSTÍVEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:183px;top:17px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>VÁLVULA DE DUAS VIAS EVAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:235px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>DEPÓSITO DO COMBUSTÍVEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:236px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>RECIPIENTE EVAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357px;top:473px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>VÁLVULA DE PURGA<br>DO RECIPIENTE EVAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:846px;top:127px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>VÁRIOS<br>SENSORES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:844px;top:343px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>Do<br>N.º 3<br>FUSÍVEL (10 A) DO<br>ALTERNADOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:708px;top:139px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:238px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:599px;top:365px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:739px;top:365px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:257px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}