with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SMR7ETRA20300000000DBPD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:29px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>FICHA DE JUNÇÃO DE 12P<br>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:30px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SENSOR FRP <br>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:29px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>VÁLVULA SOLENÓIDE<br>DE CONTROLO DA EGR<br>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:28px;top:29px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SENSOR MAP/<br>SENSOR 2 IAT <br>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:420px;top:197px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>FICHA DE 13P (9)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:363px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>FICHA DE 33P (12)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:35px;top:686px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CAIXA DE FUSÍVEIS/<br>RELÉS SOB O<br>CAPOT (H) (22)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:29px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SENSOR CMP<br>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550px;top:17px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>VÁLVULA SOLENÓIDE<br>DE CONTROLO DE<br>REFORÇO DO <br>TURBOCOMPRESSOR<br>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:170px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>VÁLVULA DE<br>CONTROLO DA PRESSÃO<br>DA RÉGUA <br>DISTRIBUIDORA (8)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:185px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SENSOR MAF/<br>SENSOR 1 IAT <br>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:197px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>FICHA DE 2P<br>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:673px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>MÓDULO DE <br>CONTROLO <br>DA RESISTÊNCIA DE <br>AQUECIMENTO (24)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:867px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SENSOR 2<br>ECT<br>(30)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:49px;top:855px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SENSOR DA VELOCIDADE<br>DO VEIO DE SAÍDA<br>(CONTRAVEIO) (29)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:685px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SENSOR DA <br>TEMPERATURA<br>DO COMBUSTÍVEL (25)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:592px;top:685px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>AQUECEDOR DO <br>COMBUSTÍVEL<br> (26)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:679px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>INTERRUPTOR DO<br>NÍVEL<br> DA ÁGUA NO FILTRO<br>DO COMBUSTÍVEL (27)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:825px;top:682px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>VÁLVULA <br>SOLENÓIDE<br>DO BLOQUEIO DA<br>MARCHA-ATRÁS (28)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:350px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>FICHA<br>DO CONTA-ROTAÇÕES<br>DE ENSAIO (14)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:700px;top:341px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CAIXA DE <br>FUSÍVEIS/RELÉS G (15)<br>SOB O<br>CAPOT <br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:851px;top:362px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ELD A <br>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:867px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SENSOR DA<br>POSIÇÃO IMRC (34)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:866px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>FICHA DE 2P<br>(33)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:179px;top:528px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CAIXA D DE FUSÍVEIS/RELÉS D<br>SOB O CAPOT (18)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:412px;top:530px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CAIXA E (19) DE FUSÍVEIS/<br>RELÉS SOB O CAPOT <br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:362px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>FICHA DE 23P (13)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:669px;top:517px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CAIXA DE <br>FUSÍVEIS/RELÉS<br>SOB O<br>CAPOT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799px;top:518px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CAIXA DE <br>FUSÍVEIS/RELÉS J (21)<br>SOB O<br>CAPOT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:463px;top:867px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SENSOR 1<br>ECT<br>(32)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:699px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>FICHA DE 10P <br> (23)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:48px;top:184px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>VÁLVULA (7) DO OBTURADOR<br>DA ADMISSÃO (ISV)<br>(com sistema DPF)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:854px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>SENSOR 1<br>EGT<br>(Com sistema DPF<br>)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:32px;top:507px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>CAIXA F (17) DE <br>FUSÍVEIS/RELÉS<br>SOB O<br>CAPOT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:1019px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>NOTA:<br>  Ficha com terminais macho (contorno duplo): vista a partir do lado do terminal<br>  Ficha com terminais fêmea (contorno simples): vista do lado dos fios<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}