with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SMR7E2PE34150300000KBPD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:608px;top:150px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PUNHO DA ALAVANCA DAS MUDANÇAS<br>8 N·m (0,8 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654px;top:360px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CORPO DA ALAVANCA DAS MUDANÇAS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514px;top:590px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CABO DAS MUDANÇAS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:723px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MOLA DO CABO DAS MUDANÇAS<br></b>Substitua.<br></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522px;top:828px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TROÇO<br></b>Substitua.<br></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:708px;top:976px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>A marca de identificação deve encontrar-se<br>na localização ilustrada<br>durante a montagem.<br></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:958px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TROÇO<br></b>Substitua.<br></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:574px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SUPORTE DO CORPO DA ALAVANCA DAS MUDANÇAS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:16px;top:56px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 x 1,25 mm<br>22 N·m<br>(2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:49px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TAMPA DA ALAVANCA DAS MUDANÇAS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:202px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 x 1,25 mm<br>22 N·m<br>(2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:777px;top:657px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CABO SELECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:748px;top:698px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 x 1,0 mm<br>9,8 N·m<br>(1,0 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:432px;top:1059px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SUPORTE DO CABO DAS MUDANÇAS<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}