with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E80A20336335001KDPD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329px;top:19px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>VÁLVULA TÉRMICA DE CONTROLO DO BYPASS<br>DO AR DA ADMISSÃO (IAB)<br></b>Aperte a válvula até 15 N·m (1,5 kgf·m) e,<br> em seguida, rode a união da válvula paralela à<br>superfície de contacto da cabeça do cilindro do colector de admissão.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:140px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>UNIÃO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187px;top:106px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>5 x 0,8 mm<br>3,4 N·m (0,35 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:107px;top:160px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SENSOR DA PRESSÃO<br>ABSOLUTA NO COLECTOR (MAP)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:11px;top:260px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>COLECTOR DA ADMISSÃO<br></b>Substitua se estiver estalado ou se<br>a superfície de contacto estiver danificada.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:461px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 x 1,25 mm<br>22 N·m<br>(2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:676px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 x 1,0 mm<br>12 N·m<br>(1,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:618px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FUNIL DO <br>COLECTOR DA ADMISSÃO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182px;top:772px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>JUNTA<br></b>Substitua.<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:107px;top:889px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CÂMARA DO COLECTOR<br>DA ADMISSÃO<br></b>Substitua se estiver estalado ou se<br>a superfície de contacto estiver<br>danificada.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:1019px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 x 1,0 mm<br>12 N·m<br>(1,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488px;top:1040px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 x 1,25 mm<br>22 N·m<br>(2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:988px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>12 x 1,25 mm<br>64 N·m<br>(6,5 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:975px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 x 1,25 mm<br>22 N·m<br>(2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722px;top:926px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SUPORTE<br>DO COLECTOR DA ADMISSÃO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744px;top:447px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>JUNTA<br></b>Substitua.<br></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:661px;top:723px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>JUNTA<br></b>Substitua.<br></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:739px;top:700px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CORPO DA<br>BORBOLETA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:856px;top:670px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 x 1,25 mm<br>22 N·m<br>(2,2 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:100px;top:207px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>O-RING<br></b>Substitua.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}