with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:952px; height:671px;\" coordsize=\"952,671\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:952px;height:671px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7E80D14300014711LAPD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:952px;height:671px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:28px;top:85px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>ANILHA DE AFINAÇÃO B <br>DA PASTILHA INTERIOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:60px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>INDICADOR DE DESGASTE<br></b>Instale a pastilha interior com<br>o respectivo indicador de <br>desgaste voltado para cima.<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:290px;top:136px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>ANILHA DEAFINAÇÃO A DA PASTILHA EXTERIOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:278px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>ANILHA DE AFINAÇÃO A <br>DA PASTILHA INTERIOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:210px;top:322px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>PASTILHAS DO TRAVÃO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526px;top:65px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>PINO DA PINÇA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:701px;top:73px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>FOLE DA CAVILHA<br></b>Substitua.<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714px;top:211px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>12 x 1,25 mm<br>108 N·m <br>(11,0 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:862px;top:338px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>SUPORTE<br>DA PINÇA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:409px;top:301px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>PINO A DA PINÇA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:364px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>PARAFUSO DE PURGA<br>9 N m<br> (0,9 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:416px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>CORPO <br>DA PINÇA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601px;top:516px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>FIXADORES DAS PASTILHAS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:520px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>PISTÃO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:31px;top:417px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>TUBO FLEXÍVEL DO TRAVÃO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:24px;top:507px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>PARAFUSO BANJO<br>34 N·m<br>(3,5 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:466px;top:435px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>VEDANTE DO PISTÃO <br></b>Substitua.<br></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:61px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>: Massa lubrificante de silicone<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:89px;top:573px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>ANILHAS DE<br>VEDAÇÃO<br></b>Substitua.<br></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170px;top:612px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>8 x 1,0 mm<br>33 N·m <br>(3,4 kgf·m)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:631px;top:569px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>FOLE DO PISTÃO<br></b>Substitua.<br></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:26px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>: Massa Lubrificante de Borracha<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428px;top:174px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>PINO B DA PINÇA<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}