with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR7ES0J36200000000BBPD28.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:123px;top:55px;font-weight:normal;font-size:8.97pt;\">");
write("<nobr><b>Ligações do Sistema Navi<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:56px;font-weight:normal;font-size:8.33pt;\">");
write("<nobr><b>Retorno<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:226px;font-weight:normal;font-size:8.33pt;\">");
write("<nobr><b>Diagrama de <br>Saída<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:100px;font-weight:normal;font-size:8.33pt;\">");
write("<nobr><b>BOM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156px;top:151px;font-weight:normal;font-size:8.97pt;\">");
write("<nobr><b>Unidade de <br>Controlo da <br>Navegação<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:199px;font-weight:normal;font-size:4.55pt;\">");
write("<nobr><b>TRASEIRA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135px;top:105px;font-weight:normal;font-size:6.15pt;\">");
write("<nobr><b>Climatização<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65px;top:148px;font-weight:normal;font-size:6.15pt;\">");
write("<nobr><b>Antena GPS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:189px;font-weight:normal;font-size:6.15pt;\">");
write("<nobr><b>Visor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:237px;font-weight:normal;font-size:6.15pt;\">");
write("<nobr><b>Rádio<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}