with(document) {
write("<v:group id=\"group4\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:995px;\" coordsize=\"950,995\">");
write("<v:rect id=\"rect4\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:995px;\">");
write("<img id=\"img4\" name=\"PrtImgId\" src=\"../img/SMR8EN0J54230100000EAPD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:995px;border-color:#ffffff\">");
write("<p id=\"p4_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:781px;top:31px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>* : Sistema i-SHIFT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:600px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Relé do inibidor*<br></b></nobr>");
write("</p>");
write("<p id=\"p4_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:99px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357px;top:99px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:950px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p4_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:157px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p4_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:948px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:950px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Cablagem do piso<br></b></nobr>");
write("</p>");
write("<p id=\"p4_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:528px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruptor do VSA DESLIGADO<br></b></nobr>");
write("</p>");
write("<p id=\"p4_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:478px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruptor da chave da ignição<br></b></nobr>");
write("</p>");
write("<p id=\"p4_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:693px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Unidade SRS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:950px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p4_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:442px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G402<br></b></nobr>");
write("</p>");
write("<p id=\"p4_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:392px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:392px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:392px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Unidade de controlo EPS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:314px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Motor do lava-faróis<br></b></nobr>");
write("</p>");
write("<p id=\"p4_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:314px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:314px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:128px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:114px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:99px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529px;top:88px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Tomada da caixa de fusíveis/relés)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:785px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G404<br></b></nobr>");
write("</p>");
write("<p id=\"p4_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:657px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Unidade SRS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:728px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p4_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:728px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:693px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p4_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:693px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:728px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Ficha de sinal (MES) de desmemorização<br></b></nobr>");
write("</p>");
write("<p id=\"p4_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:657px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p4_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:657px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:464px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Enrolador de Cabo<br></b></nobr>");
write("</p>");
write("<p id=\"p4_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:464px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p4_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:464px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:642px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G403<br></b></nobr>");
write("</p>");
write("<p id=\"p4_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:550px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruptor do motor de arranque<br></b></nobr>");
write("</p>");
write("<p id=\"p4_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:500px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:500px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p4_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:550px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p4_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:550px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:585px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Relé do inibidor<br></b></nobr>");
write("</p>");
write("<p id=\"p4_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:585px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:585px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p4_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:282px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruptor do capot (Com segurança)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:242px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruptor do nível do fluído dos travões<br></b></nobr>");
write("</p>");
write("<p id=\"p4_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:192px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Unidade de controlo do lava-faróis<br></b></nobr>");
write("</p>");
write("<p id=\"p4_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688px;top:157px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G651<br></b></nobr>");
write("</p>");
write("<p id=\"p4_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:242px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:242px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:371px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p4_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:192px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:543px;top:192px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:99px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:99px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:543px;top:157px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:950px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Cablagem do interruptor combinado<br></b></nobr>");
write("</p>");
write("<p id=\"p4_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:338px;top:948px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:948px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:950px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Cablagem do compartimento do motor<br></b></nobr>");
write("</p>");
write("<p id=\"p4_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:113px;top:950px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:56px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>CAIXA DE FUSÍVEIS/<br>RELÉS SOB O TABLIER<br></b></nobr>");
write("</p>");
write("<p id=\"p4_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:256px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruptor da posição do pedal da embraiagem <br>(Com controlo da velocidade de cruzeiro)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:499px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Interruptor de nivelamento do farol <br>(Sem HID)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}