with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:831px;\" coordsize=\"950,831\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:831px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9EQPD52100000000CAPD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:831px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:421px;top:556px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>UNIDADE DE CONTROLO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:669px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>UNIDADE MODULADORA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:607px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>UNIDADE DE CONTROLO<br>-MODULADOR DO VSA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499px;top:609px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Sinal da pressão<br>do travão<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:609px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>· Controlo do solenóide<br>· Controlo do motor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:784px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Comunicação através do F-CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:123px;top:74px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>INTERRUPTOR <br>VSA <br>DESLIGADO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:211px;top:71px;font-weight:normal;font-size:5.14pt;\">");
write("<nobr><b>INTERRUPTOR <br>DO TRAVÃO <br>DE <br>ESTACIONAMENTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:70px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>INTERRUPTOR <br>DO NÍVEL <br>DO FLUÍDO <br>DOS TRAVÕES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722px;top:328px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SENSOR DA RODA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:265px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>· Pedido de controlo do binário do motor<br>· Sinal de modo de controlo<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:225px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>· Activar/desactivar controlo VSA<br>· Sinal do ângulo de abertura da borboleta<br>· Sinal das rotações do motor<br>· Sinal da posição do interruptor <br>   do pedal do travão<br>· Sinal de verificação de serviço <br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:356px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Sinal de impulso<br>da rotação da roda<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:190px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646px;top:63px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>INTERRUPTOR <br>DA <br>POSIÇÃO <br>DO PEDAL <br>DOS TRAVÕES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:184px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>MÓDULO DE CONTROLO <br>DO INDICADOR (CONTA-ROTAÇÕES)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:378px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SENSOR DO ÂNGULO <br>DE DIRECÇÃO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246px;top:224px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>· Sinal do interruptor VSA desligado<br>· Sinal do interruptor do travão de estacionamento<br>· Sinal do interruptor do nível do fluido dos travões <br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:286px;top:330px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>· Sinal da taxa de guinada<br>· Sinal da aceleração lateral/longitudinal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:420px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Sinal do ângulo de direcção<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:239px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Sinal de accionamento <br>do indicador<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270px;top:266px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SENSOR DA <br>ACELERAÇÃO<br>LATERAL/<br>LONGITUDINAL-TAXA <br>DE GUINADA<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}