with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1119px;\" coordsize=\"950,1119\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1119px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9EQPJ10300000000DAPD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1119px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:420px;top:191px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>UNIDADE DO VISOR SECUNDÁRIO HVAC ÁUDIO (Sem navegação)<br><a href=\"javascript:CtsProc('0','000000000000112','i000')\"></b>Entradas e Saídas da Ficha,</a><br> no Manual de Oficina, Refª de Peça 62SMR00B<br><a href=\"javascript:CtsProc('0','000000000000113','i000')\">Remoção/Instalação,</a><br> no Manual de Oficina, Refª de Peça 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:104px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>UNIDADE DO VISOR SECUNDÁRIO HVAC ÁUDIO (Com navegação)<br><a href=\"javascript:CtsProc('0','000000000000112','i000')\"></b>Entradas e Saídas da Ficha,</a><br> no Manual de Oficina, Refª de Peça 62SMR00B<br><a href=\"javascript:CtsProc('0','000000000000113','i000')\">Remoção/Instalação,</a><br> no Manual de Oficina, Refª de Peça 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:479px;top:346px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TWEETER DIREITO<br><a href=\"javascript:CtsProc('0','000000000000114','iR03')\"></b>Substituição,</a><br> no Manual de Oficina, Refª de Peça 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INTERRUPTOR DE CONTROLO REMOTO DO ÁUDIO<br><a href=\"javascript:CtsProc('0','000000000000109','i000')\"></b>Ensaio,</a><br> no Manual de Oficina, Refª de Peça 62SMR00B<br><a href=\"javascript:CtsProc('0','000000000000110','i000')\">Substituição,</a><br> no Manual de Oficina, Refª de Peça 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:426px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ALTIFALANTE DIANTEIRO DIREITO<br><a href=\"javascript:CtsProc('0','000000000000114','i000')\"></b>Substituição,</a><br> no Manual de Oficina, Refª de Peça 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:639px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ALTIFALANTE TRASEIRO DIREITO<br><a href=\"javascript:CtsProc('0','000000000000114','i000')\"></b>Substituição,<br></a><br> no Manual de Oficina,<br> Refª de Peça 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702px;top:922px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MÓDULO DA ANTENA<br><a href=\"javascript:CtsProc('0','000000000000117','i000')\"></b>Substituição,</a><br> no Manual de Oficina,<br> Refª de Peça 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:626px;top:1003px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CABO DA ANTENA DA PORTA DA BAGAGEIRA<br>(AM/FM)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:277px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>UNIDADE ÁUDIO<br><a href=\"javascript:CtsProc('0','000000000003624','i000')\"></b>Entradas e Saídas da Ficha,</a><br><a href=\"javascript:CtsProc('0','000000000000111','i000')\">Remoção/Instalação,</a><br> no Manual de Oficina, Refª de Peça 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:1003px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CABO DA ANTENA<br>(AM/FM)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:1047px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ALTIFALANTE TRASEIRO ESQUERDO<br><a href=\"javascript:CtsProc('0','000000000000114','i000')\"></b>Substituição,</a><br> no Manual de Oficina, Refª de Peça 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65px;top:822px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ALTIFALANTE DA PORTA <br>ESQUERDA<br><a href=\"javascript:CtsProc('0','000000000000114','i000')\"></b>Substituição,<br></a><br> no Manual de Oficina,<br> Refª de Peça 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:915px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TWEETER ESQUERDO<br><a href=\"javascript:CtsProc('0','000000000000114','iR03')\"></b>Substituição,</a><br> no Manual de Oficina,<br> Refª de Peça 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:731px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ANTENA DO VIDRO<br>(AM/FM)<br><a href=\"javascript:CtsProc('0','000000000000116','i000')\"></b>Reparação,</a><br> no Manual de Oficina,<br> Refª de Peça 62SMR00B<br></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:400px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CABO SECUNDÁRIO DA ANTENA (AM/FM)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157px;top:970px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>UNIDADE DE ADAPTADOR USB<br><a href=\"javascript:CtsProc('0','000000000003627','i000')\"></b>Entradas e Saídas da Ficha,<br></a><br><a href=\"javascript:CtsProc('0','000000000003628','i000')\">Substituição,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:481px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FICHA DE USB<br><a href=\"javascript:CtsProc('0','000000000003629','i000')\"></b>Substituição,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:682px;top:583px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CABO SECUNDÁRIO USB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:521px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FICHA AUXILIAR<br><a href=\"javascript:CtsProc('0','000000000003625','i000')\"></b>Entradas e Saídas da Ficha,</a><br><a href=\"javascript:CtsProc('0','000000000003626','i000')\">Substituição,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:50px;top:378px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ECM<br>(Impulso de velocidade do veículo)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:1105px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>O modelo LHD é ilustrado, o modelo RHD é similar.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}