with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:927px;\" coordsize=\"950,927\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:927px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9EQPJ36314300000CAPD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:927px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:283px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:272px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>UNIDADE SRS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:272px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:260px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:260px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>FICHA DE ANÁLISE DE DADOS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:220px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>CAIXA DE FUSÍVEIS/RELÉS SOB O TABLIER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:613px;top:270px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(B−CAN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:63px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(F−CAN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:86px;top:103px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:793px;top:282px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:132px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174px;top:74px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:34px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MÓDULO DE CONTROLO DO INDICADOR (CONTA-ROTAÇÕES)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:294px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>UNIDADE DE CONTROLO EPS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:294px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:283px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>UNIDADE DE CONTROLO−MODULADOR DO VSA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:317px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:306px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MÓDULO DE CONTROLO DA TRANSMISSÃO (TCM)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:306px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:329px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SENSOR DA ACELERAÇÃO LATERAL−TAXA DE GUINADA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:329px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:318px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MÓDULO DE CONTROLO DAS MUDANÇAS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499px;top:89px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>UNIDADE <br>RECEPTORA-<br>EMISSORA F−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:502px;top:177px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>UNIDADE <br>RECEPTORA-<br>EMISSORA B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737px;top:369px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>UNIDADE DE CONTROLO <br>DO SISTEMA DE <br>TRANCAR/DESTRANCAR <br>PORTAS <br>SEM CHAVE − <br> IMOBILIZADOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740px;top:491px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>UNIDADE DE CONTROLO <br>DO AQUECEDOR/ <br>UNIDADE DE CONTROLO <br>DA CLIMATIZAÇÃO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740px;top:726px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>ILUMINAÇÃO <br>AUTOMÁTICA/ <br>SENSOR DA CHUVA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:739px;top:606px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>UNIDADE DE <br>CONTROLO DE <br>TELEFONE <br>MÃOS-LIVRES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736px;top:835px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>UNIDADE DE CONTROLO <br>DO SENSOR <br>DE ESTACIONAMENTO e <br>MARCHA-ATRÁS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:835px;top:36px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Linha CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:825px;top:36px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}