with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:475px;\" coordsize=\"950,475\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:475px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9EQP000000000000EBP903.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:475px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:41px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:41px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:41px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CAIXA DE−FUSÍVEIS/RELÉS SOB O CAPOT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:45px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CAIXA DE FUSÍVEIS/RELÉS SOB O TABLIER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:44px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:45px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:48px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:48px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:55px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>M/T<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:59px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Com sistema i−SHIFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:52px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:52px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:55px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:55px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:66px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Motor R18A2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:69px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Motor L13Z1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:59px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:59px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:48px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Com interruptor de inércia<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:52px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Sem interruptor de inércia<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:62px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:62px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:66px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:66px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714px;top:392px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ALTERNADOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:295px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:295px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:861px;top:295px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:887px;top:295px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>IG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:887px;top:286px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:879px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:776px;top:269px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:383px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RECTIFICADOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823px;top:303px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>REGULADOR DA VOLTAGEM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:860px;top:286px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:286px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:286px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:781px;top:286px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798px;top:269px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:851px;top:269px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:825px;top:269px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:793px;top:232px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:882px;top:263px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:897px;top:232px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:88px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743px;top:124px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:124px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:157px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:741px;top:105px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:157px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SOLENÓIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:750px;top:202px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MOTOR DE ARRANQUE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:105px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:68px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746px;top:68px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:777px;top:252px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>74<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804px;top:247px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>79<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:830px;top:247px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>80<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:857px;top:252px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>75<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:883px;top:247px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>46<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:748px;top:58px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:748px;top:62px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808px;top:239px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ECM (4-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:822px;top:239px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:73px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Com super fechadura<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:76px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Com HID<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:80px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Sem HID<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:69px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:69px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823px;top:73px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:73px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:76px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823px;top:76px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:827px;top:239px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(5−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:836px;top:239px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:841px;top:239px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(6−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:849px;top:239px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:80px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823px;top:80px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:62px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Motor K20Z4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769px;top:234px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FUSÍVEL (BAT) <br>N.º 1 (100 A) <br>(1−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:876px;top:234px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FUSÍVEL N.º 3<br>(10 A) <br>(3-A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:58px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BATERIA <br>(1-A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:739px;top:51px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELÉ DE CORTE <br>DO MOTOR DE ARRANQUE 2 <br>(2−B) <br>(2−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:19px;font-weight:normal;font-size:8.82pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:920px;top:19px;font-weight:normal;font-size:8.82pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:12px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>Caixa de Fusíveis/Relés sob o Tablier, Motor de arranque. Alternador<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:241px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:76px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERRUPTOR DE REGULAÇÃO DOS FARÓIS (Sem HID) (9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:72px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UNIDADE DE CONTROLO DO NIVELAMENTO DOS FARÓIS (Com HID) (9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:87px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SENSOR DA CHUVA/ILUMINAÇÃO AUTOMÁTICA (11−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:101px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERRUPTOR DO CONTROLO DA TEMPERATURA DO PASSAGEIRO (14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:90px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERRUPTOR GERAL DOS VIDROS ELÉCTRICOS) (11−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:112px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:98px;top:107px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 2 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:94px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR DO ESPELHO RETROVISOR ELÉCTRICO (12−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:80px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MOTOR DE REGULAÇÃO DO FAROL DIREITO (Sem HID) (9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:83px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MOTOR DE REGULAÇÃO DO FAROL ESQUERDO (Sem HID) (9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:98px;top:69px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 1 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:203px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:98px;top:198px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 3 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:320px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU (IG1 WIPER 2) (15−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:183px;top:317px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Ligação interna)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:316px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 38 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:305px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UNIDADE SRS (VB) (17−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:305px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:300px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 11 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:269px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Nº 10 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:98px;top:236px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 4 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:380px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:393px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:389px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 29 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:375px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 28 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:367px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:362px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:340px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:354px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:349px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 6 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:69px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:72px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:76px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:83px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:80px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:94px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:97px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:90px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:87px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:110px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:215px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SOLENÓIDE DE BLOQUEIO DA MARCHA-ATRÁS (4−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:212px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HO2S SECUNDÁRIO (SENSOR 2) (4−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:205px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:212px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:107px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:198px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:242px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:239px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:239px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UNIDADE DE CONTROLO-MODULADOR DO VSA (16−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:246px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UNIDADE DE CONTROLO EPS (16-D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:242px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SENSOR DA ACELERAÇÃOLATERAL-TAXA DE GUINADA (16−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:235px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:258px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UNIDADE SRS (VA) (17−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:258px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:98px;top:253px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Nº 9 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:253px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:279px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERRUPTOR DA LUZ DA MARCHAATRÁS (10−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:290px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU (15−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:272px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MÓDULO DE CONTROLO DO INDICADOR (CONTA-ROTAÇÕES) (7−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MÓDULO DE CONTROLO DO INDICADOR (VELOCÍMETRO) (9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:272px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:283px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:279px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:269px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:300px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:315px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:338px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:348px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:362px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:146px;top:375px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:146px;top:388px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:354px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELÉ DA LUZ DIANTEIRA DE NEVOEIRO (10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:367px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELÉ DAS LUZES DIURNAS DE PRESENÇA (Modelo KS) (15−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:380px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELÉ DA TOMADA TRASEIRA DE ALIMENTAÇÃO PARA ACESSÓRIOS (13−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:394px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELÉ DO ISQUEIRO (13−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:414px;top:221px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Ligação interna)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:393px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 15 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:304px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 14 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:398px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:309px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:292px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FAROL ESQUERDO (MÉDIOS) (9−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:292px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:247px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 13 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:252px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:252px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FAROL ESQUERDO (MÁXIMOS) (9−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:225px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FAROL DIREITO (MÁXIMOS) (9−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:225px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:220px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 12 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:196px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU (+B H/L LO) (15−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507px;top:193px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Ligação interna)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:181px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU (+B RR FOG) (15−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507px;top:177px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Ligação interna)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:154px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU (+B H/L HI) (15−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507px;top:151px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Ligação interna)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507px;top:164px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Ligação interna)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:176px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 20 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:416px;top:154px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:149px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 18 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:167px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU (+B SMALL LT) (15−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:163px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 19 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:390px;top:152px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:470px;top:149px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:470px;top:162px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:470px;top:176px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469px;top:220px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469px;top:247px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469px;top:304px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469px;top:393px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:271px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Nº 16 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:268px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 16 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:287px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 17 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:283px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 17 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:283px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:267px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FAROL DIREITO (MÉDIOS) (9−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:375px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZ UNIDADE ÁUDIO (18−A, D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:322px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZ AMBIENTE (10-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:386px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UNIDADE DE VISUALIZAÇÃO NAVEGAÇÃO (19-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:315px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:322px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:318px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:332px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:329px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:325px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:354px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UNIDADE DE CONTROLO DO AQUECEDOR/UNIDADE DE CONTROLO DA CLIMATIZAÇÃO (14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:368px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR DO VSA DESLIGADO (16−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:336px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR DOS PISCAS DE EMERGÊNCIA (10−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:318px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR DE NIVELAMENTO DOS FARÓIS (9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:354px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:350px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:347px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:410px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:414px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:403px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:407px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:400px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:396px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:414px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELÉ DAS LUZES DIURNAS DE PRESENÇA (Modelo KS) (15−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:403px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZ DA CHAPA DA MATRÍCULA (Excepto modelo KS) (10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:400px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZ DE PRESENÇA DIANTEIRA ESQUERDA (Excepto modelo KS) (10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:396px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZ DE PRESENÇA DIANTEIRA DIREITA (Excepto modelo KS) (10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:407px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZES TRASEIRAS DIREITAS (Excepto modelo KS) (10−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:410px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZES TRASEIRAS ESQUERDAS (Excepto modelo KS) (10−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:414px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Ligação interna)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:414px;top:272px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Ligação interna)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:414px;top:306px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Ligação interna)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:215px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:219px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SENSOR MAF/SENSOR IAT (4−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:201px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ELD (1−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:201px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:219px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:223px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>VÁLVULA DE PURGA DO RECIPIENTE EVAP (4−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:268px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Com HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:271px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Sem HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_250\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:283px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Com HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_251\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:287px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Sem HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_252\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:271px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_253\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:286px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_254\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:468px;top:191px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_255\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:191px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Sem HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_256\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:188px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Com HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_257\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:468px;top:187px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_258\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:188px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 21 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_259\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:191px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 21 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_260\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:382px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_261\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:386px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_262\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:372px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR DO COMANDO À DISTÂNCIA DO ÁUDIO (18−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_263\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:226px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERRUPTOR DA POSIÇÃO DO PEDAL DOS TRAVÕES (10−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_264\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:222px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_265\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:407px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELÉ DA TOMADA DIANTEIRA DE ALIMENTAÇÃO PARA ACESSÓRIOS (13−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_266\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:146px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_267\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 31 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_268\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:407px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_269\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:226px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_270\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:205px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ALTERNADOR (3-D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_271\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:246px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_272\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:44px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_273\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:82px;top:44px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_274\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:41px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(2−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_275\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:82px;top:41px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_276\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:97px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ESPELHO RETROVISOR INTERIOR DE ATENUAÇÃO AUTOMÁTICA (13−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_277\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:101px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_278\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:181px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_279\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_280\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:181px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BOMBA DO COMBUSTÍVEL (4−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_281\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:147px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_282\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133px;top:181px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_283\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:147px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_284\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:155px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_285\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_286\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:142px;top:135px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_287\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88px;top:147px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_288\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:135px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_289\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:229px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_290\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:229px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MÓDULO DE CONTROLO DA TRANSMISSÃO (TCM) (16−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_291\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:294px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MÓDULO DE CONTROLO DAS MUDANÇAS (16−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_292\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:286px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_293\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:286px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UNIDADE DE CONTROLO DO SENSOR DE ESTACIONAMENTO e DA MARCHA-ATRÁS (12−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_294\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:293px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_295\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:290px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_296\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:283px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERRUPTOR PARA DESLIGAR SENSOR DA MARCHA-ATRÁS e ESTACIONAMENTO (12−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_297\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:340px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_298\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:335px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 5 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_299\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:335px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_300\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:339px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELÉ DO AQUECEDOR DO BANCO DO CONDUTOR (13−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_301\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:342px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELÉ DO AQUECEDOR DO BANCO DO PASSAGEIRO (13−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_302\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:339px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_303\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:342px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_304\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:420px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MÓDULO DE CONTROLO DAS MUDANÇAS (16−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_305\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147px;top:415px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_306\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:415px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Nº 22 (7,5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_307\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:420px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_308\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:101px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_309\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:101px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELÉS DA SUPER FECHADURA (15−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_310\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:127px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERRUPTOR DO VIDRO ELÉCTRICO DO PASSAGEIRO (11−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_311\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:127px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_312\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:123px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 30 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_313\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:114px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERRUPTOR GERAL DOS VIDROS ELÉCTRICOS (11−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_314\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507px;top:84px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(Ligação interna)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_315\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:114px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_316\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:109px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 26 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_317\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_318\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:88px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU (+B DR LOCK) (15−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_319\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:83px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 25 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_320\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:72px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_321\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469px;top:82px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_322\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469px;top:109px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_323\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469px;top:122px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_324\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MOTOR DO QUEBRA-LUZ (14−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_325\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:69px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>N.º 24 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_326\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469px;top:69px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_327\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_328\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:379px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UNIDADE DE NAVEGAÇÃO (19-A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_329\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:307px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_330\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:315px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR DE SELECÇÃO/REPOSIÇÃO/INFORMAÇÃO (7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_331\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:336px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_332\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:347px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR DO AQUECEDOR DO BANCO DO CONDUTOR (13−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_333\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:339px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_334\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:350px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR DO AQUECEDOR DO BANCO DO PASSAGEIRO DIANTEIRO (13−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_335\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:343px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_336\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:325px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZ DO PORTA-LUVAS (10-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_337\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:329px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZ DO ESPAÇO PARA OS PÉS DO CONDUTOR (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_338\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:343px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR PARA DESLIGAR SENSOR DA MARCHA-ATRÁS e ESTACIONAMENTO (12−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_339\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:379px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_340\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:368px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_341\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:361px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_342\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:357px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_343\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:339px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR DO LAVA-FARÓIS (11−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_344\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:332px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZ DO ESPAÇO PARA OS PÉS DO PASSAGEIRO DIANTEIRO (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_345\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:382px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERRUPTOR DE CONTROLO DOS COMANDOS DE VOZ (19−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_346\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:389px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_347\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:65px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_348\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:50px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>41<br></b></nobr>");
write("</p>");
write("<p id=\"p1_349\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154px;top:130px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_350\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76px;top:341px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p1_351\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:75px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>42<br></b></nobr>");
write("</p>");
write("<p id=\"p1_352\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:112px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>43<br></b></nobr>");
write("</p>");
write("<p id=\"p1_353\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>44<br></b></nobr>");
write("</p>");
write("<p id=\"p1_354\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:181px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>45<br></b></nobr>");
write("</p>");
write("<p id=\"p1_355\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:203px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>46<br></b></nobr>");
write("</p>");
write("<p id=\"p1_356\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:241px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>47<br></b></nobr>");
write("</p>");
write("<p id=\"p1_357\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:259px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>48<br></b></nobr>");
write("</p>");
write("<p id=\"p1_358\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>49<br></b></nobr>");
write("</p>");
write("<p id=\"p1_359\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:305px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p1_360\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:321px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>51<br></b></nobr>");
write("</p>");
write("<p id=\"p1_361\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:341px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>52<br></b></nobr>");
write("</p>");
write("<p id=\"p1_362\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:354px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>53<br></b></nobr>");
write("</p>");
write("<p id=\"p1_363\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:367px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>54<br></b></nobr>");
write("</p>");
write("<p id=\"p1_364\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:380px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>55<br></b></nobr>");
write("</p>");
write("<p id=\"p1_365\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:394px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>56<br></b></nobr>");
write("</p>");
write("<p id=\"p1_366\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:407px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>57<br></b></nobr>");
write("</p>");
write("<p id=\"p1_367\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:420px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>58<br></b></nobr>");
write("</p>");
write("<p id=\"p1_368\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:114px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_369\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:114px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UNIDADE DE CONTROLO DO IMOBILIZADOR−SISTEMA DE <br>DESTRANCAR/TRANCAR AS PORTAS SEM CHAVE (12−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_370\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:110px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ECM (4−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_371\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ECM (4−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_372\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_373\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296px;top:181px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_374\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298px;top:181px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(5−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_375\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306px;top:181px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_376\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:215px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_377\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:215px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(5−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_378\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:215px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_379\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:219px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_380\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303px;top:219px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(5−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_381\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311px;top:219px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_382\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:212px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_383\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:212px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(5−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_384\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:318px;top:212px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_385\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:223px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_386\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329px;top:223px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(5−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_387\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:223px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_388\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:75px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_389\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:154px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_390\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:225px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>130<br></b></nobr>");
write("</p>");
write("<p id=\"p1_391\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:252px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>129<br></b></nobr>");
write("</p>");
write("<p id=\"p1_392\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>131<br></b></nobr>");
write("</p>");
write("<p id=\"p1_393\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:310px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>132<br></b></nobr>");
write("</p>");
write("<p id=\"p1_394\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:75px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>59<br></b></nobr>");
write("</p>");
write("<p id=\"p1_395\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:88px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>60<br></b></nobr>");
write("</p>");
write("<p id=\"p1_396\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:101px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>61<br></b></nobr>");
write("</p>");
write("<p id=\"p1_397\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:114px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>62<br></b></nobr>");
write("</p>");
write("<p id=\"p1_398\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:128px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>63<br></b></nobr>");
write("</p>");
write("<p id=\"p1_399\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:154px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>64<br></b></nobr>");
write("</p>");
write("<p id=\"p1_400\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:168px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>65<br></b></nobr>");
write("</p>");
write("<p id=\"p1_401\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:181px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>66<br></b></nobr>");
write("</p>");
write("<p id=\"p1_402\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:196px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>67<br></b></nobr>");
write("</p>");
write("<p id=\"p1_403\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:225px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>68<br></b></nobr>");
write("</p>");
write("<p id=\"p1_404\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:252px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>69<br></b></nobr>");
write("</p>");
write("<p id=\"p1_405\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>70<br></b></nobr>");
write("</p>");
write("<p id=\"p1_406\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:292px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>71<br></b></nobr>");
write("</p>");
write("<p id=\"p1_407\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:310px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>72<br></b></nobr>");
write("</p>");
write("<p id=\"p1_408\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:398px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>73<br></b></nobr>");
write("</p>");
write("<p id=\"p1_409\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:101px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_410\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:627px;top:225px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_411\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633px;top:225px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_412\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643px;top:225px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_413\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:631px;top:252px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_414\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:639px;top:251px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_415\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:252px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_416\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_417\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_418\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638px;top:276px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_419\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:627px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_420\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_421\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_422\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:361px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERRUPTOR DO QUEBRA-LUZ (14−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_423\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:372px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_424\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:357px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UNIDADE DE VISUALIZAÇÃO SECUNDÁRIA HVAC (14−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_425\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:375px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_426\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:389px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERRUPTOR DE CONTROLO DO COMANDO DE VOZ−HFT (19−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_427\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:208px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SENSOR CMP A (4−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_428\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:208px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_429\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283px;top:208px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_430\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:215px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(6−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_431\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:351px;top:215px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_432\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:219px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(6−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_433\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:219px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_434\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:212px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(6−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_435\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:211px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_436\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:223px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(6−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_437\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:223px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_438\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:181px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(6−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_439\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:181px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_440\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(5−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_441\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:280px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_442\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(6−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_443\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_444\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:110px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_445\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275px;top:110px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(5−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_446\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283px;top:110px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_447\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:110px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(6−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_448\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:110px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_449\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:230px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_450\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:294px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_451\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:421px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_452\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:46px;top:338px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FUSÍVEL <br>N.º 4 (OP) (80 A) (1−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_453\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:151px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FUSÍVEL <br>N.º 2 (H/L) <br>(60 A) (1−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_454\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:308px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR SET/RESUME/CANCEL (MEMORIZAR/RETOMAR/CANCELAR) <br>DO CONTROLO DA VELOCIDADE DE CRUZEIRO (7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_455\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:223px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU<br>(15−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_456\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:164px;top:147px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELÉ PRINCIPAL 2<br>DA PGM−FI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_457\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147px;top:117px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELÉ PRINCIPAL 1 <br>DA PGM-FI <br>(1-C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_458\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:161px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERRUPTOR <br>DE INÉRCIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_459\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373px;top:70px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FUSÍVEL <br>N.º 6 (P/W) <br>(40 A) (1−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_460\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:250px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU<br>(15−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_461\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU<br>(15−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_462\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:307px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU<br>(15−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_463\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:364px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERRUPTOR S−MODE (16−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_464\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:364px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}