with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9EQP000000000000EBP108.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:23px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>Módulo de Controlo do Indicador (Conta-rotações)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:497px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:647px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:482px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:647px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:628px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:699px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:699px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>UNIDADE ÁUDIO (18−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:621px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:528px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:683px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:683px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:647px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR DOS PISCAS DE EMERGÊNCIA (10−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:676px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR DO VSA DESLIGADO (16−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:633px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:633px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:654px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:654px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:620px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:620px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583px;top:582px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:570px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:539px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:528px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:528px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:565px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:565px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:579px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:579px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:444px;top:579px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNIDADE ÁUDIO (18−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:555px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DIODO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:664px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:628px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ AMBIENTE (10-B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:258px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:458px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:224px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MÓDULO DE CONTROLO DO INDICADOR (CONTA-ROTAÇÕES) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:635px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:635px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DO ESPAÇO PARA OS PÉS DO CONDUTOR (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:656px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:676px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:676px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:664px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR DO AQUECEDOR DO BANCO <br>DO CONDUTOR (13−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:621px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR DE NIVELAMENTO DOS FARÓIS (9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:692px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:692px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR DE QUEBRA-LUZ (14-D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:556px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>102<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586px;top:609px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>85<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:609px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>88<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:656px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR DO LAVA-FARÓIS (11−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:642px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:642px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DO ESPAÇO PARA OS PÉS DO PASSAGEIRO DIANTEIRO <br>(10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:677px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:677px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR DO AQUECEDOR <br>DO BANCO DO PASSAGEIRO DIANTEIRO (13−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:697px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:697px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:690px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>INTERRUPTOR DE CONTROLO DOS COMANDOS DE VOZ (19−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:690px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:690px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:683px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>INTERRUPTOR DO COMANDO À DISTÂNCIA DO ÁUDIO (18−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:697px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>INTERRUPTOR DE CONTROLO DO COMANDO DE VOZ−HFT (19−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:334px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>CIRCUITO <br>DA AVARIA <br>SEGURA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:436px;top:268px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CIRCUITO DE <br>ACTIVAÇÃO <br>OBRIGATÓRIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:267px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CIRCUITO DE <br>DESACTIVAÇÃO <br>OBRIGATÓRIA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:311px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LÂMPADA <br>INDICADORA <br>DE MAU <br>FUNCIONAMENTO <br>(MIL) (LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:633px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR MEMORIZAR/RETOMAR/CANCELAR<br> DO CONTROLO DA VELOCIDADE DE CRUZEIRO (7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:444px;top:565px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNIDADE DE <br>VISUALIZAÇÃO SECUNDÁRIA HVAC (14−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:655px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>UNIDADE DE CONTROLO DO AQUECEDOR/<br>UNIDADE DE CONTROLO DA CLIMATIZAÇÃO (14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:619px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>LUZ DO INTERRUPTOR DE <br>SELECÇÃO/REPOSIÇÃO/INFORMAÇÃO (7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:669px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>INTERRUPTOR S−MODE (16−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:669px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:669px;font-weight:normal;font-size:3.73pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}