with(document) {
write("<v:group id=\"group11\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:465px;\" coordsize=\"475,465\">");
write("<v:rect id=\"rect11\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:465px;\">");
write("<img id=\"img11\" name=\"PrtImgId\" src=\"../img/SMR9ERPA20321000000CAPD11.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:465px;border-color:#ffffff\">");
write("<p id=\"p11_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:17px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>VELOCIDADE DO VEÍCULO<br></b></nobr>");
write("</p>");
write("<p id=\"p11_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:56px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>alta<br></b></nobr>");
write("</p>");
write("<p id=\"p11_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:161px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>alta<br></b></nobr>");
write("</p>");
write("<p id=\"p11_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:190px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>POSIÇÃO DO CARRETO<br></b></nobr>");
write("</p>");
write("<p id=\"p11_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:219px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>4ª<br></b></nobr>");
write("</p>");
write("<p id=\"p11_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:227px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>3ª<br></b></nobr>");
write("</p>");
write("<p id=\"p11_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:227px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>PARA BAIXO<br></b></nobr>");
write("</p>");
write("<p id=\"p11_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175px;top:415px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Com SIL<br></b></nobr>");
write("</p>");
write("<p id=\"p11_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175px;top:435px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>Sem SIL<br></b></nobr>");
write("</p>");
write("<p id=\"p11_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:374px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>MELHORAMENTO DA<br>ECONOMIA DE <br>COMBUSTÍVEL<br></b></nobr>");
write("</p>");
write("<p id=\"p11_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:122px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>ROTAÇÃO DO MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p11_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:330px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>alta<br></b></nobr>");
write("</p>");
write("<p id=\"p11_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:31px;top:292px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>POSIÇÃO DO PEDAL DO ACELERADOR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}