with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:815px;\" coordsize=\"950,815\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:815px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SMR9ER2A20300000000DBPD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:815px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:14px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CABLAGEM<br>DO MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:63px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:46px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:444px;top:40px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:37px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546px;top:42px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:49px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:655px;top:72px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:115px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:787px;top:186px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:832px;top:271px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:849px;top:336px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:848px;top:447px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:748px;top:614px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:691px;top:663px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566px;top:724px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:734px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:451px;top:744px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:730px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:719px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:650px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:629px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:601px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:136px;top:570px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:86px;top:481px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339px;top:770px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CABLAGEM<br>DO COMPARTIMENTO DO MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:684px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}